const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Public zyli library module. Subsystems (model, crypto, wire, ...) are
    // re-exported through src/root.zig so downstream consumers and the node
    // executable share a single import surface.
    const zyli_module = b.addModule("zyli", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
    });

    const lib = b.addLibrary(.{
        .name = "zyli",
        .root_module = zyli_module,
    });
    b.installArtifact(lib);

    // Node executable. Kept intentionally thin: it should only wire the
    // runtime, configuration, and node modes — no protocol logic.
    const exe = b.addExecutable(.{
        .name = "zyli",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zyli", .module = zyli_module },
            },
        }),
    });
    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    const run_step = b.step("run", "Run the zyli node executable");
    run_step.dependOn(&run_cmd.step);

    // Compatibility corpus module — auto-generated by `compat/fixture-gen`.
    // It lives outside `src/` so that the on-disk byte fixtures and the Zig
    // tests stay loosely coupled, but tests still need to @embedFile from
    // it. Adding it as its own module makes the corpus directory the package
    // root for those embeds.
    const corpus_module = b.createModule(.{
        .root_source_file = b.path("compat/corpus.zig"),
        .target = target,
        .optimize = optimize,
    });

    // Library unit tests. The test module re-imports `corpus` so any test
    // file in `src/` can `@import("corpus")`.
    const test_module = b.createModule(.{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "corpus", .module = corpus_module },
        },
    });
    const lib_unit_tests = b.addTest(.{ .root_module = test_module });
    const run_lib_unit_tests = b.addRunArtifact(lib_unit_tests);

    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_lib_unit_tests.step);
}
