//! P2P handshake envelope types and tests.
//!
//! Mirrors the wire shapes from `hyli_net::tcp`:
//!
//!   - `Canal(String)` — newtype for the canal label that scopes a
//!     connection (e.g. `"p2p"`, `"da"`).
//!   - `NodeConnectionData` — what a peer announces about itself during
//!     the handshake. Gets BLS-signed before going on the wire.
//!   - `Handshake` — `Hello`/`Verack`, both carrying
//!     `(Canal, SignedByValidator<NodeConnectionData>, TimestampMs)`.
//!   - `P2PTcpMessage<Data>` — the outer envelope. Either a `Handshake`
//!     or a generic `Data` payload.
//!
//! The Borsh wire layout is the contract: every fixture in
//! `compat/corpus/wire/messages/handshake_*` and `p2p_message_*` is
//! generated by the Rust fixture-gen against locally-redeclared mirrors of
//! the same types. A regression on either side fails the build before any
//! observer code runs.

const std = @import("std");
const borsh = @import("../model/borsh.zig");
const types = @import("../model/types.zig");

/// Handshake variant tags. Encoded by Borsh as a single `u8` byte:
///   0 → Hello, 1 → Verack.
pub const HandshakeKind = enum(u8) { hello, verack };

/// Build a `Handshake::Hello(...)` value with the given payload.
pub fn hello(payload: types.HandshakePayload) types.Handshake {
    return .{ .hello = payload };
}

/// Build a `Handshake::Verack(...)` value with the given payload.
pub fn verack(payload: types.HandshakePayload) types.Handshake {
    return .{ .verack = payload };
}

/// Wrap a `Handshake` value in a `P2PTcpMessage<Data>::Handshake` envelope.
/// `Data` is comptime so each call site stays aligned with the inner
/// payload type used elsewhere in the wire layer.
pub fn handshakeEnvelope(comptime Data: type, hs: types.Handshake) types.P2PTcpMessage(Data) {
    return .{ .handshake = hs };
}

/// Wrap an inner `Data` payload in a `P2PTcpMessage<Data>::Data` envelope.
pub fn dataEnvelope(comptime Data: type, payload: Data) types.P2PTcpMessage(Data) {
    return .{ .data = payload };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;
const corpus = @import("corpus");

fn sampleNodeConnectionData() types.NodeConnectionData {
    return .{
        .version = 1,
        .name = "validator-a",
        .current_height = 42,
        .p2p_public_address = "127.0.0.1:4242",
        .da_public_address = "127.0.0.1:4243",
        .start_timestamp = .{ .millis = 1_700_000_000_000 },
    };
}

fn sampleSignedNodeConnectionData() types.Signed(types.NodeConnectionData, types.ValidatorSignature) {
    return .{
        .msg = sampleNodeConnectionData(),
        .signature = .{
            .signature = .{ .bytes = &[_]u8{0xff} ** 8 },
            .validator = .{ .bytes = &[_]u8{0x01} ** 4 },
        },
    };
}

test "Handshake::Hello matches the corpus inner bytes" {
    const payload: types.HandshakePayload = .{
        .canal = .{ .name = "p2p" },
        .signed_node_connection_data = sampleSignedNodeConnectionData(),
        .timestamp = .{ .millis = 1_700_000_000_001 },
    };
    var list = try borsh.encodeAlloc(testing.allocator, types.Handshake, hello(payload));
    defer list.deinit(testing.allocator);
    try testing.expectEqualSlices(
        u8,
        corpus.wire.messages.handshake_hello_inner,
        list.items,
    );
    // Sanity: the Borsh tag for Hello must be 0.
    try testing.expectEqual(@as(u8, 0), list.items[0]);
}

test "Handshake::Verack matches the corpus inner bytes" {
    const payload: types.HandshakePayload = .{
        .canal = .{ .name = "p2p" },
        .signed_node_connection_data = sampleSignedNodeConnectionData(),
        .timestamp = .{ .millis = 1_700_000_000_002 },
    };
    var list = try borsh.encodeAlloc(testing.allocator, types.Handshake, verack(payload));
    defer list.deinit(testing.allocator);
    try testing.expectEqualSlices(
        u8,
        corpus.wire.messages.handshake_verack_inner,
        list.items,
    );
    // Sanity: the Borsh tag for Verack must be 1.
    try testing.expectEqual(@as(u8, 1), list.items[0]);
}

test "P2PTcpMessage::Handshake(Hello) matches the corpus inner bytes" {
    const Inner = []const u8;
    const M = types.P2PTcpMessage(Inner);
    const payload: types.HandshakePayload = .{
        .canal = .{ .name = "p2p" },
        .signed_node_connection_data = sampleSignedNodeConnectionData(),
        .timestamp = .{ .millis = 1_700_000_000_001 },
    };
    const value: M = handshakeEnvelope(Inner, hello(payload));
    var list = try borsh.encodeAlloc(testing.allocator, M, value);
    defer list.deinit(testing.allocator);
    try testing.expectEqualSlices(
        u8,
        corpus.wire.messages.p2p_message_handshake_hello_inner,
        list.items,
    );
    // The outer Handshake tag is 0 (first variant) and the inner Hello tag
    // is also 0 (first variant), so the prefix is `0x00 0x00`.
    try testing.expectEqual(@as(u8, 0), list.items[0]);
    try testing.expectEqual(@as(u8, 0), list.items[1]);
}

test "P2PTcpMessage::Data(Vec<u8>) matches the corpus inner bytes" {
    const Inner = []const u8;
    const M = types.P2PTcpMessage(Inner);
    const value: M = dataEnvelope(Inner, &[_]u8{ 0xaa, 0xbb, 0xcc });
    var list = try borsh.encodeAlloc(testing.allocator, M, value);
    defer list.deinit(testing.allocator);
    try testing.expectEqualSlices(
        u8,
        corpus.wire.messages.p2p_message_data_inner,
        list.items,
    );
    // Outer tag: Data is variant 1.
    try testing.expectEqual(@as(u8, 1), list.items[0]);
}

test "P2PTcpMessage::Handshake(Hello) frames cleanly through the framing layer" {
    const framing = @import("framing.zig");
    const Inner = []const u8;
    const M = types.P2PTcpMessage(Inner);
    const payload: types.HandshakePayload = .{
        .canal = .{ .name = "p2p" },
        .signed_node_connection_data = sampleSignedNodeConnectionData(),
        .timestamp = .{ .millis = 1_700_000_000_001 },
    };
    const value: M = handshakeEnvelope(Inner, hello(payload));
    var list = try borsh.encodeAlloc(testing.allocator, M, value);
    defer list.deinit(testing.allocator);
    const framed = try framing.encodeFrameAlloc(testing.allocator, list.items);
    defer testing.allocator.free(framed);
    try testing.expectEqualSlices(
        u8,
        corpus.wire.messages.p2p_message_handshake_hello_framed,
        framed,
    );
}
