//! Zig mirrors of Hyli protocol types.
//!
//! These are deliberately *minimal*: enough to make the compatibility corpus
//! tests round-trip a value through Zig's Borsh codec and check it against the
//! Rust-generated bytes. As more of the model lands, the structs will grow,
//! but the rule is unchanged — every field that exists here must be backed by
//! a fixture in `compat/corpus/`.
//!
//! Newtypes such as `Identity(String)` collapse into a single Zig field,
//! because Borsh treats a tuple struct with one field exactly the same as the
//! field itself: there is no envelope.

const std = @import("std");

/// `hyli_model::Identity` (`Identity(pub String)`).
pub const Identity = struct {
    value: []const u8,
};

/// `hyli_model::ContractName` (`ContractName(pub String)`).
pub const ContractName = struct {
    value: []const u8,
};

/// `hyli_model::ProgramId` (`ProgramId(pub Vec<u8>)`).
pub const ProgramId = struct {
    bytes: []const u8,
};

/// `hyli_model::Verifier` (`Verifier(pub String)`).
pub const Verifier = struct {
    value: []const u8,
};

/// `hyli_model::StateCommitment` (`StateCommitment(pub Vec<u8>)`).
pub const StateCommitment = struct {
    bytes: []const u8,
};

/// `hyli_model::BlockHeight` (`BlockHeight(pub u64)`).
pub const BlockHeight = struct {
    height: u64,
};

/// `hyli_model::BlobIndex` (`BlobIndex(pub usize)`).
///
/// Borsh in Rust serializes `usize` as a fixed-width `u64`. Zig has its own
/// `usize` whose width depends on the host pointer size, so we deliberately
/// use `u64` here to keep the wire format independent of the platform.
pub const BlobIndex = struct {
    index: u64,
};

/// `hyli_model::BlobData` (`BlobData(pub Vec<u8>)`).
pub const BlobData = struct {
    bytes: []const u8,
};

/// `hyli_model::Blob` from `crates/hyli-model/src/contract.rs`.
pub const Blob = struct {
    contract_name: ContractName,
    data: BlobData,
};

/// `hyli_model::TimestampMs` (`TimestampMs(pub u128)`).
pub const TimestampMs = struct {
    millis: u128,
};

/// `hyli_model::DataProposalHash` (`DataProposalHash(pub Vec<u8>)`).
pub const DataProposalHash = struct {
    bytes: []const u8,
};

/// `hyli_model::ValidatorPublicKey` (`ValidatorPublicKey(pub Vec<u8>)`).
pub const ValidatorPublicKey = struct {
    bytes: []const u8,
};

/// `hyli_model::staking::LaneId`.
pub const LaneId = struct {
    operator: ValidatorPublicKey,
    suffix: []const u8,
};

/// `hyli_model::DataProposalParent` enum. Variant order MUST match the Rust
/// declaration order — Borsh discriminants are positional.
pub const DataProposalParent = union(enum) {
    lane_root: LaneId,
    dp: DataProposalHash,
};

/// `hyli_model::ProofData` (`ProofData(pub Vec<u8>)`).
pub const ProofData = struct {
    bytes: []const u8,
};

/// `hyli_model::ProofDataHash` (`ProofDataHash(pub Vec<u8>)`).
pub const ProofDataHash = struct {
    bytes: []const u8,
};

/// `hyli_model::TxHash` (`TxHash(pub Vec<u8>)`).
pub const TxHash = struct {
    bytes: []const u8,
};

/// `hyli_model::Signature` — opaque BLS signature bytes (`Vec<u8>`).
pub const Signature = struct {
    bytes: []const u8,
};

/// `hyli_model::ValidatorSignature` — `{ signature, validator }`.
pub const ValidatorSignature = struct {
    signature: Signature,
    validator: ValidatorPublicKey,
};

/// `hyli_model::AggregateSignature`.
pub const AggregateSignature = struct {
    signature: Signature,
    validators: []const ValidatorPublicKey,
};

/// `hyli_model::Signed<T, V>` envelope. Generic over the inner message and
/// the signature wrapper. Field order matches the Rust definition exactly.
pub fn Signed(comptime Msg: type, comptime Sig: type) type {
    return struct {
        msg: Msg,
        signature: Sig,
    };
}

/// `hyli_model::ValidatorCandidacy`.
pub const ValidatorCandidacy = struct {
    peer_address: []const u8,
};

/// `hyli_model::BlobTransaction`. The `hash_cache` and `blobshash_cache`
/// fields on the Rust side are `#[borsh(skip)]` and absent from the wire,
/// so the Zig mirror only carries identity + blobs.
pub const BlobTransaction = struct {
    identity: Identity,
    blobs: []const Blob,
};

/// `hyli_model::ProofTransaction`.
pub const ProofTransaction = struct {
    contract_name: ContractName,
    program_id: ProgramId,
    verifier: Verifier,
    proof: ProofData,
};

/// `hyli_model::VerifiedProofTransaction`.
pub const VerifiedProofTransaction = struct {
    contract_name: ContractName,
    program_id: ProgramId,
    verifier: Verifier,
    proof: ?ProofData,
    proof_hash: ProofDataHash,
    /// Borsh in Rust serializes `usize` as a fixed `u64`.
    proof_size: u64,
    proven_blobs: []const BlobProofOutput,
    is_recursive: bool,
};

/// Placeholder for the `BlobProofOutput` type — Hyli definition is in
/// `verifiers.rs`. Until we need a concrete shape, we accept any byte buffer
/// so callers can keep the slice empty in fixtures that don't exercise it.
pub const BlobProofOutput = struct {
    bytes: []const u8,
};

/// `hyli_model::TransactionData` enum — Borsh discriminants follow the
/// declaration order: Blob, Proof, VerifiedProof.
pub const TransactionData = union(enum) {
    blob: BlobTransaction,
    proof: ProofTransaction,
    verified_proof: VerifiedProofTransaction,
};

/// `hyli_model::Transaction`.
pub const Transaction = struct {
    version: u32,
    transaction_data: TransactionData,
};

/// `hyli_model::LaneBytesSize` (`LaneBytesSize(pub u64)`).
pub const LaneBytesSize = struct {
    bytes: u64,
};

/// `hyli_model::ConsensusProposalHash` (`ConsensusProposalHash(pub Vec<u8>)`).
pub const ConsensusProposalHash = struct {
    bytes: []const u8,
};

/// `hyli_model::ConsensusStakingAction`. The Rust `Bond` variant boxes its
/// candidate (`Box<SignedByValidator<ValidatorCandidacy>>`); `Box` is
/// invisible on the wire so the Zig mirror just stores the inner value
/// directly.
pub const ConsensusStakingAction = union(enum) {
    bond: Signed(ValidatorCandidacy, ValidatorSignature),
    pay_fees_for_dadi: struct {
        lane_id: LaneId,
        cumul_size: LaneBytesSize,
    },
};

/// `hyli_model::Cut = Vec<(LaneId, DataProposalHash, LaneBytesSize, AggregateSignature)>`.
///
/// Borsh tuple structs encode their fields positionally with no length
/// prefix and no envelope, so a Zig struct with the same field order
/// produces identical bytes. We name the fields for readability and so
/// the consensus hash code can read them back unambiguously.
pub const CutEntry = struct {
    lane_id: LaneId,
    dp_hash: DataProposalHash,
    lane_bytes_size: LaneBytesSize,
    aggregate_signature: AggregateSignature,
};

/// `hyli_model::ConsensusProposal`. Field order matches the Rust definition
/// exactly: slot, parent_hash, cut, staking_actions, timestamp.
pub const ConsensusProposal = struct {
    slot: u64,
    parent_hash: ConsensusProposalHash,
    cut: []const CutEntry,
    staking_actions: []const ConsensusStakingAction,
    timestamp: TimestampMs,
};

/// `hyli_model::BlockHash` is a type alias for `ConsensusProposalHash`.
pub const BlockHash = ConsensusProposalHash;

/// `hyli_model::BlobHash` (`BlobHash(pub Vec<u8>)`).
pub const BlobHash = struct {
    bytes: []const u8,
};

/// One entry of a `BlobsHashes` map. Used as the underlying element of the
/// `BTreeMap<BlobIndex, BlobHash>` storage so the Zig encoder can keep the
/// map ordered without depending on a generic associative container.
pub const BlobsHashesEntry = struct {
    index: BlobIndex,
    hash: BlobHash,
};

/// `hyli_model::BlobsHashes`. Borsh encodes the underlying `BTreeMap` as a
/// `u32` length followed by `(key, value)` pairs in ascending key order.
/// We model that with a sorted slice and pin "callers must sort by index"
/// as the contract — see `borsh.zig` for the encoder.
pub const BlobsHashes = struct {
    /// Entries MUST be sorted by `index` in ascending order. The encoder
    /// asserts this on debug builds; the decoder restores the same
    /// invariant.
    hashes: []const BlobsHashesEntry,
};

/// `hyli_model::IndexedBlobs` (`IndexedBlobs(pub Vec<(BlobIndex, Blob)>)`).
/// Tuple `(BlobIndex, Blob)` encodes positionally so a Zig struct with the
/// same field order produces identical bytes.
pub const IndexedBlobEntry = struct {
    index: BlobIndex,
    blob: Blob,
};

pub const IndexedBlobs = struct {
    blobs: []const IndexedBlobEntry,
};

/// `hyli_model::TxContext` from `crates/hyli-model/src/contract.rs`.
pub const TxContext = struct {
    lane_id: LaneId,
    block_hash: BlockHash,
    block_height: BlockHeight,
    timestamp: TimestampMs,
    chain_id: u128,
};

/// `hyli_model::Calldata`. Field order matches contract.rs exactly.
pub const Calldata = struct {
    tx_hash: TxHash,
    identity: Identity,
    blobs: IndexedBlobs,
    /// Borsh in Rust serializes `usize` as a fixed `u64`.
    tx_blob_count: u64,
    index: BlobIndex,
    tx_ctx: ?TxContext,
    private_input: []const u8,
};

/// `hyli_model::TimeoutWindow` enum. Variant order: `NoTimeout`, then
/// `Timeout { hard, soft }`. Borsh discriminants are positional.
pub const TimeoutWindow = union(enum) {
    no_timeout,
    timeout: struct {
        hard_timeout: BlockHeight,
        soft_timeout: BlockHeight,
    },
};

/// `hyli_model::RegisterContractEffect` from contract.rs.
pub const RegisterContractEffect = struct {
    verifier: Verifier,
    program_id: ProgramId,
    state_commitment: StateCommitment,
    contract_name: ContractName,
    timeout_window: ?TimeoutWindow,
};

/// Helper struct for the two `OnchainEffect` variants whose payload is a
/// 2-tuple of named values. Borsh encodes a tuple positionally with no
/// envelope, so this struct is wire-equivalent to `(ContractName, ProgramId)`.
pub const ContractNameAndProgramId = struct {
    contract_name: ContractName,
    program_id: ProgramId,
};

pub const ContractNameAndTimeoutWindow = struct {
    contract_name: ContractName,
    timeout_window: TimeoutWindow,
};

/// `hyli_model::OnchainEffect` enum.
///
/// Variant order from contract.rs:
///   0. RegisterContractWithConstructor(RegisterContractEffect)
///   1. RegisterContract(RegisterContractEffect)
///   2. DeleteContract(ContractName)
///   3. UpdateContractProgramId(ContractName, ProgramId)
///   4. UpdateTimeoutWindow(ContractName, TimeoutWindow)
pub const OnchainEffect = union(enum) {
    register_contract_with_constructor: RegisterContractEffect,
    register_contract: RegisterContractEffect,
    delete_contract: ContractName,
    update_contract_program_id: ContractNameAndProgramId,
    update_timeout_window: ContractNameAndTimeoutWindow,
};

/// One `(ContractName, StateCommitment)` entry of `HyliOutput::state_reads`.
pub const StateRead = struct {
    contract_name: ContractName,
    state_commitment: StateCommitment,
};

/// `hyli_model::HyliOutput` from contract.rs.
pub const HyliOutput = struct {
    version: u32,
    initial_state: StateCommitment,
    next_state: StateCommitment,
    identity: Identity,
    index: BlobIndex,
    blobs: IndexedBlobs,
    /// Borsh in Rust serializes `usize` as a fixed `u64`.
    tx_blob_count: u64,
    tx_hash: TxHash,
    success: bool,
    state_reads: []const StateRead,
    tx_ctx: ?TxContext,
    onchain_effects: []const OnchainEffect,
    program_outputs: []const u8,
};

// ---------------------------------------------------------------------------
// Wire layer (hyli-net)
// ---------------------------------------------------------------------------

/// `hyli_net::tcp::Canal` (`Canal(pub String)`). Newtype around `String`,
/// wire-identical to a single string.
pub const Canal = struct {
    name: []const u8,
};

/// `hyli_net::tcp::NodeConnectionData`. The struct that gets BLS-signed
/// during the handshake.
pub const NodeConnectionData = struct {
    version: u16,
    name: []const u8,
    current_height: u64,
    p2p_public_address: []const u8,
    da_public_address: []const u8,
    start_timestamp: TimestampMs,
};

/// Inner payload of both `Handshake::Hello` and `Handshake::Verack`. The
/// Rust definition uses an unnamed 3-tuple; Borsh encodes tuples positionally
/// with no envelope, so a Zig struct with the same field order is
/// byte-identical on the wire.
pub const HandshakePayload = struct {
    canal: Canal,
    signed_node_connection_data: Signed(NodeConnectionData, ValidatorSignature),
    timestamp: TimestampMs,
};

/// `hyli_net::tcp::Handshake` enum. Variant order: Hello, Verack.
pub const Handshake = union(enum) {
    hello: HandshakePayload,
    verack: HandshakePayload,
};

/// `hyli_net::tcp::P2PTcpMessage<Data>` envelope. Generic over the inner
/// data payload type. Variant order: Handshake, Data.
pub fn P2PTcpMessage(comptime Data: type) type {
    return union(enum) {
        handshake: Handshake,
        data: Data,
    };
}

test "type sizes are platform-stable where it matters" {
    // BlockHeight is u64, not usize.
    try std.testing.expectEqual(@as(usize, 8), @sizeOf(u64));
    try std.testing.expectEqual(@as(usize, 16), @sizeOf(u128));
}
