//! Zig mirrors of Hyli protocol types.
//!
//! These are deliberately *minimal*: enough to make the compatibility corpus
//! tests round-trip a value through Zig's Borsh codec and check it against the
//! Rust-generated bytes. As more of the model lands, the structs will grow,
//! but the rule is unchanged — every field that exists here must be backed by
//! a fixture in `compat/corpus/`.
//!
//! Newtypes such as `Identity(String)` collapse into a single Zig field,
//! because Borsh treats a tuple struct with one field exactly the same as the
//! field itself: there is no envelope.

const std = @import("std");

/// `hyli_model::Identity` (`Identity(pub String)`).
pub const Identity = struct {
    value: []const u8,
};

/// `hyli_model::ContractName` (`ContractName(pub String)`).
pub const ContractName = struct {
    value: []const u8,
};

/// `hyli_model::ProgramId` (`ProgramId(pub Vec<u8>)`).
pub const ProgramId = struct {
    bytes: []const u8,
};

/// `hyli_model::Verifier` (`Verifier(pub String)`).
pub const Verifier = struct {
    value: []const u8,
};

/// `hyli_model::StateCommitment` (`StateCommitment(pub Vec<u8>)`).
pub const StateCommitment = struct {
    bytes: []const u8,
};

/// `hyli_model::BlockHeight` (`BlockHeight(pub u64)`).
pub const BlockHeight = struct {
    height: u64,
};

/// `hyli_model::BlobIndex` (`BlobIndex(pub usize)`).
///
/// Borsh in Rust serializes `usize` as a fixed-width `u64`. Zig has its own
/// `usize` whose width depends on the host pointer size, so we deliberately
/// use `u64` here to keep the wire format independent of the platform.
pub const BlobIndex = struct {
    index: u64,
};

/// `hyli_model::BlobData` (`BlobData(pub Vec<u8>)`).
pub const BlobData = struct {
    bytes: []const u8,
};

/// `hyli_model::Blob` from `crates/hyli-model/src/contract.rs`.
pub const Blob = struct {
    contract_name: ContractName,
    data: BlobData,
};

/// `hyli_model::TimestampMs` (`TimestampMs(pub u128)`).
pub const TimestampMs = struct {
    millis: u128,
};

/// `hyli_model::DataProposalHash` (`DataProposalHash(pub Vec<u8>)`).
pub const DataProposalHash = struct {
    bytes: []const u8,
};

/// `hyli_model::ValidatorPublicKey` (`ValidatorPublicKey(pub Vec<u8>)`).
pub const ValidatorPublicKey = struct {
    bytes: []const u8,
};

/// `hyli_model::staking::LaneId`.
pub const LaneId = struct {
    operator: ValidatorPublicKey,
    suffix: []const u8,
};

/// `hyli_model::DataProposalParent` enum. Variant order MUST match the Rust
/// declaration order — Borsh discriminants are positional.
pub const DataProposalParent = union(enum) {
    lane_root: LaneId,
    dp: DataProposalHash,
};

/// `hyli_model::ProofData` (`ProofData(pub Vec<u8>)`).
pub const ProofData = struct {
    bytes: []const u8,
};

/// `hyli_model::ProofDataHash` (`ProofDataHash(pub Vec<u8>)`).
pub const ProofDataHash = struct {
    bytes: []const u8,
};

/// `hyli_model::TxHash` (`TxHash(pub Vec<u8>)`).
pub const TxHash = struct {
    bytes: []const u8,
};

/// `hyli_model::Signature` — opaque BLS signature bytes (`Vec<u8>`).
pub const Signature = struct {
    bytes: []const u8,
};

/// `hyli_model::ValidatorSignature` — `{ signature, validator }`.
pub const ValidatorSignature = struct {
    signature: Signature,
    validator: ValidatorPublicKey,
};

/// `hyli_model::AggregateSignature`.
pub const AggregateSignature = struct {
    signature: Signature,
    validators: []const ValidatorPublicKey,
};

/// `hyli_model::Signed<T, V>` envelope. Generic over the inner message and
/// the signature wrapper. Field order matches the Rust definition exactly.
pub fn Signed(comptime Msg: type, comptime Sig: type) type {
    return struct {
        msg: Msg,
        signature: Sig,
    };
}

/// `hyli_model::ValidatorCandidacy`.
pub const ValidatorCandidacy = struct {
    peer_address: []const u8,
};

/// `hyli_model::BlobTransaction`. The `hash_cache` and `blobshash_cache`
/// fields on the Rust side are `#[borsh(skip)]` and absent from the wire,
/// so the Zig mirror only carries identity + blobs.
pub const BlobTransaction = struct {
    identity: Identity,
    blobs: []const Blob,
};

/// `hyli_model::ProofTransaction`.
pub const ProofTransaction = struct {
    contract_name: ContractName,
    program_id: ProgramId,
    verifier: Verifier,
    proof: ProofData,
};

/// `hyli_model::VerifiedProofTransaction`.
pub const VerifiedProofTransaction = struct {
    contract_name: ContractName,
    program_id: ProgramId,
    verifier: Verifier,
    proof: ?ProofData,
    proof_hash: ProofDataHash,
    /// Borsh in Rust serializes `usize` as a fixed `u64`.
    proof_size: u64,
    proven_blobs: []const BlobProofOutput,
    is_recursive: bool,
};

/// `hyli_model::BlobProofOutput` from
/// `crates/hyli-model/src/node/data_availability.rs`. Field order matches
/// the Rust definition exactly.
///
/// The Zig declaration is forward-referenced from
/// `VerifiedProofTransaction.proven_blobs`, so the full struct body lives
/// after `HyliOutput` is defined. See `BlobProofOutputBody` below.
pub const BlobProofOutput = BlobProofOutputBody;

/// `hyli_model::TransactionData` enum — Borsh discriminants follow the
/// declaration order: Blob, Proof, VerifiedProof.
pub const TransactionData = union(enum) {
    blob: BlobTransaction,
    proof: ProofTransaction,
    verified_proof: VerifiedProofTransaction,
};

/// `hyli_model::Transaction`.
pub const Transaction = struct {
    version: u32,
    transaction_data: TransactionData,
};

/// `hyli_model::LaneBytesSize` (`LaneBytesSize(pub u64)`).
pub const LaneBytesSize = struct {
    bytes: u64,
};

/// `hyli_model::ConsensusProposalHash` (`ConsensusProposalHash(pub Vec<u8>)`).
pub const ConsensusProposalHash = struct {
    bytes: []const u8,
};

/// `hyli_model::ConsensusStakingAction`. The Rust `Bond` variant boxes its
/// candidate (`Box<SignedByValidator<ValidatorCandidacy>>`); `Box` is
/// invisible on the wire so the Zig mirror just stores the inner value
/// directly.
pub const ConsensusStakingAction = union(enum) {
    bond: Signed(ValidatorCandidacy, ValidatorSignature),
    pay_fees_for_dadi: struct {
        lane_id: LaneId,
        cumul_size: LaneBytesSize,
    },
};

/// `hyli_model::Cut = Vec<(LaneId, DataProposalHash, LaneBytesSize, AggregateSignature)>`.
///
/// Borsh tuple structs encode their fields positionally with no length
/// prefix and no envelope, so a Zig struct with the same field order
/// produces identical bytes. We name the fields for readability and so
/// the consensus hash code can read them back unambiguously.
pub const CutEntry = struct {
    lane_id: LaneId,
    dp_hash: DataProposalHash,
    lane_bytes_size: LaneBytesSize,
    aggregate_signature: AggregateSignature,
};

/// `hyli_model::ConsensusProposal`. Field order matches the Rust definition
/// exactly: slot, parent_hash, cut, staking_actions, timestamp.
pub const ConsensusProposal = struct {
    slot: u64,
    parent_hash: ConsensusProposalHash,
    cut: []const CutEntry,
    staking_actions: []const ConsensusStakingAction,
    timestamp: TimestampMs,
};

/// `hyli_model::BlockHash` is a type alias for `ConsensusProposalHash`.
pub const BlockHash = ConsensusProposalHash;

/// `hyli_model::BlobHash` (`BlobHash(pub Vec<u8>)`).
pub const BlobHash = struct {
    bytes: []const u8,
};

/// One entry of a `BlobsHashes` map. Used as the underlying element of the
/// `BTreeMap<BlobIndex, BlobHash>` storage so the Zig encoder can keep the
/// map ordered without depending on a generic associative container.
pub const BlobsHashesEntry = struct {
    index: BlobIndex,
    hash: BlobHash,
};

/// `hyli_model::BlobsHashes`. Borsh encodes the underlying `BTreeMap` as a
/// `u32` length followed by `(key, value)` pairs in ascending key order.
/// We model that with a sorted slice and pin "callers must sort by index"
/// as the contract — see `borsh.zig` for the encoder.
pub const BlobsHashes = struct {
    /// Entries MUST be sorted by `index` in ascending order. The encoder
    /// asserts this on debug builds; the decoder restores the same
    /// invariant.
    hashes: []const BlobsHashesEntry,
};

/// `hyli_model::IndexedBlobs` (`IndexedBlobs(pub Vec<(BlobIndex, Blob)>)`).
/// Tuple `(BlobIndex, Blob)` encodes positionally so a Zig struct with the
/// same field order produces identical bytes.
pub const IndexedBlobEntry = struct {
    index: BlobIndex,
    blob: Blob,
};

pub const IndexedBlobs = struct {
    blobs: []const IndexedBlobEntry,
};

/// `hyli_model::TxContext` from `crates/hyli-model/src/contract.rs`.
pub const TxContext = struct {
    lane_id: LaneId,
    block_hash: BlockHash,
    block_height: BlockHeight,
    timestamp: TimestampMs,
    chain_id: u128,
};

/// `hyli_model::Calldata`. Field order matches contract.rs exactly.
pub const Calldata = struct {
    tx_hash: TxHash,
    identity: Identity,
    blobs: IndexedBlobs,
    /// Borsh in Rust serializes `usize` as a fixed `u64`.
    tx_blob_count: u64,
    index: BlobIndex,
    tx_ctx: ?TxContext,
    private_input: []const u8,
};

/// `hyli_model::TimeoutWindow` enum. Variant order: `NoTimeout`, then
/// `Timeout { hard, soft }`. Borsh discriminants are positional.
pub const TimeoutWindow = union(enum) {
    no_timeout,
    timeout: struct {
        hard_timeout: BlockHeight,
        soft_timeout: BlockHeight,
    },
};

/// `hyli_model::RegisterContractEffect` from contract.rs.
pub const RegisterContractEffect = struct {
    verifier: Verifier,
    program_id: ProgramId,
    state_commitment: StateCommitment,
    contract_name: ContractName,
    timeout_window: ?TimeoutWindow,
};

/// Helper struct for the two `OnchainEffect` variants whose payload is a
/// 2-tuple of named values. Borsh encodes a tuple positionally with no
/// envelope, so this struct is wire-equivalent to `(ContractName, ProgramId)`.
pub const ContractNameAndProgramId = struct {
    contract_name: ContractName,
    program_id: ProgramId,
};

pub const ContractNameAndTimeoutWindow = struct {
    contract_name: ContractName,
    timeout_window: TimeoutWindow,
};

/// `hyli_model::OnchainEffect` enum.
///
/// Variant order from contract.rs:
///   0. RegisterContractWithConstructor(RegisterContractEffect)
///   1. RegisterContract(RegisterContractEffect)
///   2. DeleteContract(ContractName)
///   3. UpdateContractProgramId(ContractName, ProgramId)
///   4. UpdateTimeoutWindow(ContractName, TimeoutWindow)
pub const OnchainEffect = union(enum) {
    register_contract_with_constructor: RegisterContractEffect,
    register_contract: RegisterContractEffect,
    delete_contract: ContractName,
    update_contract_program_id: ContractNameAndProgramId,
    update_timeout_window: ContractNameAndTimeoutWindow,
};

/// One `(ContractName, StateCommitment)` entry of `HyliOutput::state_reads`.
pub const StateRead = struct {
    contract_name: ContractName,
    state_commitment: StateCommitment,
};

/// `hyli_model::BlobProofOutput` body — full struct shape. See
/// `BlobProofOutput` above for the forward-reference glue.
pub const BlobProofOutputBody = struct {
    blob_tx_hash: TxHash,
    original_proof_hash: ProofDataHash,
    hyli_output: HyliOutput,
    program_id: ProgramId,
    verifier: Verifier,
};

/// `hyli_model::HyliOutput` from contract.rs.
pub const HyliOutput = struct {
    version: u32,
    initial_state: StateCommitment,
    next_state: StateCommitment,
    identity: Identity,
    index: BlobIndex,
    blobs: IndexedBlobs,
    /// Borsh in Rust serializes `usize` as a fixed `u64`.
    tx_blob_count: u64,
    tx_hash: TxHash,
    success: bool,
    state_reads: []const StateRead,
    tx_ctx: ?TxContext,
    onchain_effects: []const OnchainEffect,
    program_outputs: []const u8,
};

// ---------------------------------------------------------------------------
// Wire layer (hyli-net)
// ---------------------------------------------------------------------------

/// `hyli_net::tcp::Canal` (`Canal(pub String)`). Newtype around `String`,
/// wire-identical to a single string.
pub const Canal = struct {
    name: []const u8,
};

/// `hyli_net::tcp::NodeConnectionData`. The struct that gets BLS-signed
/// during the handshake.
pub const NodeConnectionData = struct {
    version: u16,
    name: []const u8,
    current_height: u64,
    p2p_public_address: []const u8,
    da_public_address: []const u8,
    start_timestamp: TimestampMs,
};

/// Inner payload of both `Handshake::Hello` and `Handshake::Verack`. The
/// Rust definition uses an unnamed 3-tuple; Borsh encodes tuples positionally
/// with no envelope, so a Zig struct with the same field order is
/// byte-identical on the wire.
pub const HandshakePayload = struct {
    canal: Canal,
    signed_node_connection_data: Signed(NodeConnectionData, ValidatorSignature),
    timestamp: TimestampMs,
};

/// `hyli_net::tcp::Handshake` enum. Variant order: Hello, Verack.
pub const Handshake = union(enum) {
    hello: HandshakePayload,
    verack: HandshakePayload,
};

/// `hyli_net::tcp::P2PTcpMessage<Data>` envelope. Generic over the inner
/// data payload type. Variant order: Handshake, Data.
pub fn P2PTcpMessage(comptime Data: type) type {
    return union(enum) {
        handshake: Handshake,
        data: Data,
    };
}

// ---------------------------------------------------------------------------
// Consensus network messages (mirrors of hyli/src/consensus/network.rs)
// ---------------------------------------------------------------------------

/// `Slot` is a `u64` alias on the Hyli side.
pub const Slot = u64;

/// `View` is a `u64` alias on the Hyli side.
pub const View = u64;

/// `consensus::ConsensusMarkerSerde` enum from `network.rs`.
///
/// Hyli's consensus markers (`PrepareVoteMarker`, `ConfirmAckMarker`, etc.)
/// are zero-sized structs that all serialize through this shared 4-variant
/// enum so each marker gets a distinct, single-byte tag. The byte values
/// are pinned by the upstream `marker_serialization_bytes_are_unique_and_expected`
/// test:
///
///   PrepareVote          → 0
///   ConfirmAck           → 1
///   ConsensusTimeout     → 2
///   NilConsensusTimeout  → 3
pub const ConsensusMarker = enum(u8) {
    prepare_vote,
    confirm_ack,
    consensus_timeout,
    nil_consensus_timeout,
};

/// `consensus::QuorumCertificate<T>(pub AggregateSignature, pub T)`. The
/// trailing marker byte is what makes a `PrepareQC` byte-distinct from a
/// `CommitQC` over the same `AggregateSignature` — the upstream
/// `quorum_certificate_cannot_be_reused_across_steps` test enforces that.
///
/// We model the marker as a separate field so the Zig encoder simply
/// emits the AggregateSignature followed by the marker byte; the type
/// alias `PrepareQC` etc. below pin the expected marker for each step.
pub const QuorumCertificate = struct {
    aggregate: AggregateSignature,
    marker: ConsensusMarker,
};

/// `consensus::PrepareQC = QuorumCertificate<PrepareVoteMarker>`.
pub const PrepareQC = QuorumCertificate;
/// `consensus::CommitQC = QuorumCertificate<ConfirmAckMarker>`.
pub const CommitQC = QuorumCertificate;
/// `consensus::TimeoutQC = QuorumCertificate<ConsensusTimeoutMarker>`.
pub const TimeoutQC = QuorumCertificate;
/// `consensus::NilQC = QuorumCertificate<NilConsensusTimeoutMarker>`.
pub const NilQC = QuorumCertificate;

/// Inner payload of a `PrepareVote` / `ConfirmAck` value: a tuple of
/// `(ConsensusProposalHash, marker)`. Borsh encodes 2-tuples positionally,
/// so a Zig struct with the same field order is wire-equivalent.
pub const ConsensusVotePayload = struct {
    consensus_proposal_hash: ConsensusProposalHash,
    marker: ConsensusMarker,
};

/// `consensus::PrepareVote = SignedByValidator<(ConsensusProposalHash, PrepareVoteMarker)>`.
pub const PrepareVote = Signed(ConsensusVotePayload, ValidatorSignature);

/// `consensus::ConfirmAck = SignedByValidator<(ConsensusProposalHash, ConfirmAckMarker)>`.
pub const ConfirmAck = Signed(ConsensusVotePayload, ValidatorSignature);

/// Forward-declare `ConsensusProposal`-carrying QC tuple for `TCKind` and
/// `Ticket`. Borsh encodes a 2-tuple `(QuorumCertificate, ConsensusProposal)`
/// positionally; this struct mirrors that.
pub const QcWithProposal = struct {
    quorum_certificate: QuorumCertificate,
    proposal: ConsensusProposal,
};

/// `consensus::TCKind` enum.
pub const TcKind = union(enum) {
    nil_proposal: NilQC,
    prepare_qc: QcWithProposal,
};

/// `consensus::Ticket` enum. Variant order:
///   0. Genesis
///   1. CommitQC(CommitQC)
///   2. TimeoutQC(TimeoutQC, TCKind)
///   3. ForcedCommitQC(View)
pub const Ticket = union(enum) {
    genesis,
    commit_qc: CommitQC,
    timeout_qc: TicketTimeoutPayload,
    forced_commit_qc: View,
};

/// Inner payload of `Ticket::TimeoutQC(TimeoutQC, TCKind)`. Borsh encodes
/// the tuple positionally — same trick as `ConsensusVotePayload`.
pub const TicketTimeoutPayload = struct {
    timeout_qc: TimeoutQC,
    tc_kind: TcKind,
};

/// `Prepare(ConsensusProposal, Ticket, View)` payload of
/// `ConsensusNetMessage`. Three-tuple → Zig struct.
pub const PreparePayload = struct {
    proposal: ConsensusProposal,
    ticket: Ticket,
    view: View,
};

/// `Confirm(PrepareQC, ConsensusProposalHash)` payload. Two-tuple → struct.
pub const ConfirmPayload = struct {
    prepare_qc: PrepareQC,
    consensus_proposal_hash: ConsensusProposalHash,
};

/// `Commit(CommitQC, ConsensusProposalHash)` payload.
pub const CommitPayload = struct {
    commit_qc: CommitQC,
    consensus_proposal_hash: ConsensusProposalHash,
};

/// `SyncReply((ValidatorPublicKey, ConsensusProposal, Ticket, View))` payload.
pub const SyncReplyPayload = struct {
    sender: ValidatorPublicKey,
    proposal: ConsensusProposal,
    ticket: Ticket,
    view: View,
};

/// Inner payload of the `(slot, view, cph, marker)` 4-tuple that
/// `Timeout` envelopes are signed against. Borsh encodes a 4-tuple
/// positionally with no envelope, so a Zig struct with the same field
/// order is wire-equivalent.
pub const TimeoutSignedPayload = struct {
    slot: Slot,
    view: View,
    consensus_proposal_hash: ConsensusProposalHash,
    marker: ConsensusMarker,
};

/// `consensus::TimeoutKind` enum.
pub const TimeoutKind = union(enum) {
    nil_proposal: Signed(TimeoutSignedPayload, ValidatorSignature),
    prepare_qc: QcWithProposal,
};

/// `consensus::ConsensusTimeout = (
///     SignedByValidator<(Slot, View, ConsensusProposalHash, ConsensusTimeoutMarker)>,
///     TimeoutKind,
/// )`
pub const ConsensusTimeout = struct {
    outer: Signed(TimeoutSignedPayload, ValidatorSignature),
    kind: TimeoutKind,
};

/// `TimeoutCertificate(TimeoutQC, TCKind, Slot, View)` payload of
/// `ConsensusNetMessage`.
pub const TimeoutCertificatePayload = struct {
    timeout_qc: TimeoutQC,
    tc_kind: TcKind,
    slot: Slot,
    view: View,
};

/// `consensus::ConsensusNetMessage` enum. Variant order matches
/// `network.rs` exactly.
pub const ConsensusNetMessage = union(enum) {
    prepare: PreparePayload,
    prepare_vote: PrepareVote,
    confirm: ConfirmPayload,
    confirm_ack: ConfirmAck,
    commit: CommitPayload,
    timeout: ConsensusTimeout,
    timeout_certificate: TimeoutCertificatePayload,
    validator_candidacy: Signed(ValidatorCandidacy, ValidatorSignature),
    sync_request: ConsensusProposalHash,
    sync_reply: SyncReplyPayload,
};

// ---------------------------------------------------------------------------
// Mempool network messages (mirrors of hyli/src/mempool.rs)
// ---------------------------------------------------------------------------

/// `mempool::ValidatorDAG = SignedByValidator<(DataProposalHash, LaneBytesSize)>`.
pub const ValidatorDagPayload = struct {
    data_proposal_hash: DataProposalHash,
    lane_bytes_size: LaneBytesSize,
};

pub const ValidatorDag = Signed(ValidatorDagPayload, ValidatorSignature);

/// Variant payloads of `MempoolNetMessage`. Each tuple-shaped variant is
/// modeled as a Zig struct with named fields for readability.
pub const MempoolDataProposalPayload = struct {
    lane_id: LaneId,
    data_proposal_hash: DataProposalHash,
    data_proposal: DataProposal,
    validator_dag: ValidatorDag,
};

pub const MempoolDataVotePayload = struct {
    lane_id: LaneId,
    validator_dag: ValidatorDag,
};

pub const MempoolSyncRequestPayload = struct {
    lane_id: LaneId,
    from: ?DataProposalHash,
    to: ?DataProposalHash,
};

pub const MempoolSyncReplyPayload = struct {
    lane_id: LaneId,
    metadata: []const ValidatorDag,
    data_proposal: DataProposal,
};

/// `hyli_model::DataProposal` (`crates/hyli-model/src/node/mempool.rs`).
///
/// Field order on the wire:
///   1. `parent_data_proposal_hash: DataProposalParent`
///   2. `txs: Vec<Transaction>`
///   3. `hash_cache: #[borsh(skip)]` — absent from the wire.
pub const DataProposal = struct {
    parent_data_proposal_hash: DataProposalParent,
    txs: []const Transaction,
};

/// `mempool::MempoolNetMessage` enum.
pub const MempoolNetMessage = union(enum) {
    data_proposal: MempoolDataProposalPayload,
    data_vote: MempoolDataVotePayload,
    sync_request: MempoolSyncRequestPayload,
    sync_reply: MempoolSyncReplyPayload,
};

// ---------------------------------------------------------------------------
// Block / DA stream
// ---------------------------------------------------------------------------

/// One entry of `SignedBlock::data_proposals`. Borsh encodes the
/// `(LaneId, Vec<DataProposal>)` 2-tuple positionally — same trick as
/// the `IndexedBlobs` entries.
pub const LaneDataProposals = struct {
    lane_id: LaneId,
    data_proposals: []const DataProposal,
};

/// `hyli_model::SignedBlock` from `crates/hyli-model/src/block.rs`.
///
/// Field order on the wire:
///   1. data_proposals: Vec<(LaneId, Vec<DataProposal>)>
///   2. consensus_proposal: ConsensusProposal
///   3. certificate: AggregateSignature
pub const SignedBlock = struct {
    data_proposals: []const LaneDataProposals,
    consensus_proposal: ConsensusProposal,
    certificate: AggregateSignature,
};

// ---------------------------------------------------------------------------
// Mempool dissemination events and DA stream messages
// ---------------------------------------------------------------------------

/// `hyli_model::TxId(pub DataProposalHash, pub TxHash)`. Tuple struct
/// → positional Zig struct.
pub const TxId = struct {
    data_proposal_hash: DataProposalHash,
    tx_hash: TxHash,
};

/// `hyli_model::TransactionKind` strum-discriminant of `TransactionData`.
/// Variant order matches `TransactionData`: Blob, Proof, VerifiedProof.
/// Encoded by Borsh as a single `u8`.
pub const TransactionKind = enum(u8) {
    blob,
    proof,
    verified_proof,
};

/// `hyli_model::TransactionMetadata`. Lightweight pointer the mempool
/// dissemination event uses to refer to a transaction without dragging
/// its full payload.
pub const TransactionMetadata = struct {
    version: u32,
    transaction_kind: TransactionKind,
    id: TxId,
};

/// Inner payload of `MempoolStatusEvent::WaitingDissemination`. The
/// upstream Rust definition uses a struct-like enum variant, which
/// Borsh encodes the same as a positional struct.
pub const MempoolWaitingDissemination = struct {
    parent_data_proposal_hash: DataProposalHash,
    txs: []const Transaction,
};

/// Inner payload of `MempoolStatusEvent::DataProposalCreated`.
pub const MempoolDataProposalCreated = struct {
    parent_data_proposal_hash: DataProposalHash,
    data_proposal_hash: DataProposalHash,
    txs_metadatas: []const TransactionMetadata,
};

/// `hyli_model::MempoolStatusEvent`.
pub const MempoolStatusEvent = union(enum) {
    waiting_dissemination: MempoolWaitingDissemination,
    data_proposal_created: MempoolDataProposalCreated,
};

/// `hyli_model::DataAvailabilityRequest`.
pub const DataAvailabilityRequest = union(enum) {
    stream_from_height: BlockHeight,
    block_request: BlockHeight,
};

/// `hyli_model::DataAvailabilityEvent`.
pub const DataAvailabilityEvent = union(enum) {
    signed_block: SignedBlock,
    mempool_status_event: MempoolStatusEvent,
    block_not_found: BlockHeight,
};

// ---------------------------------------------------------------------------
// Staking and indexer-side types
// ---------------------------------------------------------------------------

/// Inner payload of `StakingAction::DepositForFees { holder, amount }`.
/// Borsh encodes a struct-like enum variant the same as a positional
/// struct.
pub const StakingDepositForFees = struct {
    holder: ValidatorPublicKey,
    amount: u128,
};

/// `hyli_model::staking::RewardsClaim`. Holds a list of block heights.
/// `BlockHeight` is `pub BlockHeight(pub u64)`, so the wire form is
/// just a length-prefixed `Vec<u64>`.
pub const RewardsClaim = struct {
    block_heights: []const BlockHeight,
};

/// `hyli_model::StakingAction`. Variant order matches staking.rs:
/// Stake, Delegate, Distribute, DepositForFees.
pub const StakingAction = union(enum) {
    stake: u128,
    delegate: ValidatorPublicKey,
    distribute: RewardsClaim,
    deposit_for_fees: StakingDepositForFees,
};

/// `hyli_model::Contract`. The on-disk record for a registered
/// contract. Field order matches data_availability.rs.
pub const Contract = struct {
    name: ContractName,
    program_id: ProgramId,
    state: StateCommitment,
    verifier: Verifier,
    timeout_window: TimeoutWindow,
};

/// Inner payload of `TransactionStateEvent::NewProof`.
pub const TransactionStateEventNewProof = struct {
    blob_index: BlobIndex,
    proof_tx_hash: TxHash,
    program_output: []const u8,
};

/// `hyli_model::TransactionStateEvent`. Per-transaction lifecycle
/// events the indexer subscribes to. Variant order matches
/// data_availability.rs.
pub const TransactionStateEvent = union(enum) {
    sequenced: void,
    @"error": []const u8,
    new_proof: TransactionStateEventNewProof,
    settled: void,
    settled_as_failed: void,
    timed_out: void,
    dropped_as_duplicate: void,
};

test "type sizes are platform-stable where it matters" {
    // BlockHeight is u64, not usize.
    try std.testing.expectEqual(@as(usize, 8), @sizeOf(u64));
    try std.testing.expectEqual(@as(usize, 16), @sizeOf(u128));
}
