//! Auto-generated by `compat/fixture-gen`. Do not edit by hand.
//!
//! Each constant points at a Borsh or hash fixture under
//! `compat/corpus/`. The Zig side embeds the bytes at compile
//! time, so a missing or renamed fixture surfaces as a build
//! error long before any test runs.
//!
//! Source: hyli git revision `e41899eb582d2d25d13a97a425ec76250484d45c`.

pub const borsh = struct {
    pub const consensus = struct {
        pub const commit_qc: []const u8 = @embedFile("corpus/borsh/consensus/commit_qc.bin");
        pub const confirm_ack: []const u8 = @embedFile("corpus/borsh/consensus/confirm_ack.bin");
        pub const consensus_timeout: []const u8 = @embedFile("corpus/borsh/consensus/consensus_timeout.bin");
        pub const marker_confirm_ack: []const u8 = @embedFile("corpus/borsh/consensus/marker_confirm_ack.bin");
        pub const marker_consensus_timeout: []const u8 = @embedFile("corpus/borsh/consensus/marker_consensus_timeout.bin");
        pub const marker_nil_consensus_timeout: []const u8 = @embedFile("corpus/borsh/consensus/marker_nil_consensus_timeout.bin");
        pub const marker_prepare_vote: []const u8 = @embedFile("corpus/borsh/consensus/marker_prepare_vote.bin");
        pub const net_message_commit: []const u8 = @embedFile("corpus/borsh/consensus/net_message_commit.bin");
        pub const net_message_confirm: []const u8 = @embedFile("corpus/borsh/consensus/net_message_confirm.bin");
        pub const net_message_confirm_ack: []const u8 = @embedFile("corpus/borsh/consensus/net_message_confirm_ack.bin");
        pub const net_message_prepare: []const u8 = @embedFile("corpus/borsh/consensus/net_message_prepare.bin");
        pub const net_message_prepare_vote: []const u8 = @embedFile("corpus/borsh/consensus/net_message_prepare_vote.bin");
        pub const net_message_sync_reply: []const u8 = @embedFile("corpus/borsh/consensus/net_message_sync_reply.bin");
        pub const net_message_sync_request: []const u8 = @embedFile("corpus/borsh/consensus/net_message_sync_request.bin");
        pub const net_message_timeout: []const u8 = @embedFile("corpus/borsh/consensus/net_message_timeout.bin");
        pub const net_message_timeout_certificate: []const u8 = @embedFile("corpus/borsh/consensus/net_message_timeout_certificate.bin");
        pub const net_message_validator_candidacy: []const u8 = @embedFile("corpus/borsh/consensus/net_message_validator_candidacy.bin");
        pub const nil_qc: []const u8 = @embedFile("corpus/borsh/consensus/nil_qc.bin");
        pub const prepare_qc: []const u8 = @embedFile("corpus/borsh/consensus/prepare_qc.bin");
        pub const prepare_vote: []const u8 = @embedFile("corpus/borsh/consensus/prepare_vote.bin");
        pub const tc_kind_nil_proposal: []const u8 = @embedFile("corpus/borsh/consensus/tc_kind_nil_proposal.bin");
        pub const tc_kind_prepare_qc: []const u8 = @embedFile("corpus/borsh/consensus/tc_kind_prepare_qc.bin");
        pub const ticket_commit_qc: []const u8 = @embedFile("corpus/borsh/consensus/ticket_commit_qc.bin");
        pub const ticket_genesis: []const u8 = @embedFile("corpus/borsh/consensus/ticket_genesis.bin");
        pub const timeout_kind_nil_proposal: []const u8 = @embedFile("corpus/borsh/consensus/timeout_kind_nil_proposal.bin");
        pub const timeout_kind_prepare_qc: []const u8 = @embedFile("corpus/borsh/consensus/timeout_kind_prepare_qc.bin");
        pub const timeout_qc: []const u8 = @embedFile("corpus/borsh/consensus/timeout_qc.bin");
    };
    pub const crypto = struct {
        pub const bls_min_pk_dst: []const u8 = @embedFile("corpus/borsh/crypto/bls_min_pk_dst.bin");
        pub const signable_node_connection_data: []const u8 = @embedFile("corpus/borsh/crypto/signable_node_connection_data.bin");
        pub const signable_validator_candidacy: []const u8 = @embedFile("corpus/borsh/crypto/signable_validator_candidacy.bin");
    };
    pub const mempool = struct {
        pub const net_message_data_proposal: []const u8 = @embedFile("corpus/borsh/mempool/net_message_data_proposal.bin");
        pub const net_message_data_vote: []const u8 = @embedFile("corpus/borsh/mempool/net_message_data_vote.bin");
        pub const net_message_sync_reply: []const u8 = @embedFile("corpus/borsh/mempool/net_message_sync_reply.bin");
        pub const net_message_sync_request: []const u8 = @embedFile("corpus/borsh/mempool/net_message_sync_request.bin");
        pub const net_message_sync_request_none: []const u8 = @embedFile("corpus/borsh/mempool/net_message_sync_request_none.bin");
        pub const validator_dag: []const u8 = @embedFile("corpus/borsh/mempool/validator_dag.bin");
    };
    pub const model = struct {
        pub const aggregate_signature_2: []const u8 = @embedFile("corpus/borsh/model/aggregate_signature_2.bin");
        pub const blob_index_3: []const u8 = @embedFile("corpus/borsh/model/blob_index_3.bin");
        pub const blob_proof_output_sample: []const u8 = @embedFile("corpus/borsh/model/blob_proof_output_sample.bin");
        pub const blob_simple: []const u8 = @embedFile("corpus/borsh/model/blob_simple.bin");
        pub const blob_transaction: []const u8 = @embedFile("corpus/borsh/model/blob_transaction.bin");
        pub const blobs_hashes_empty: []const u8 = @embedFile("corpus/borsh/model/blobs_hashes_empty.bin");
        pub const blobs_hashes_two: []const u8 = @embedFile("corpus/borsh/model/blobs_hashes_two.bin");
        pub const block_height_42: []const u8 = @embedFile("corpus/borsh/model/block_height_42.bin");
        pub const calldata: []const u8 = @embedFile("corpus/borsh/model/calldata.bin");
        pub const canal_p2p: []const u8 = @embedFile("corpus/borsh/model/canal_p2p.bin");
        pub const consensus_proposal_empty: []const u8 = @embedFile("corpus/borsh/model/consensus_proposal_empty.bin");
        pub const consensus_proposal_full: []const u8 = @embedFile("corpus/borsh/model/consensus_proposal_full.bin");
        pub const consensus_staking_action_bond: []const u8 = @embedFile("corpus/borsh/model/consensus_staking_action_bond.bin");
        pub const consensus_staking_action_pay: []const u8 = @embedFile("corpus/borsh/model/consensus_staking_action_pay.bin");
        pub const contract_name_hyli: []const u8 = @embedFile("corpus/borsh/model/contract_name_hyli.bin");
        pub const contract_sample: []const u8 = @embedFile("corpus/borsh/model/contract_sample.bin");
        pub const da_event_not_found: []const u8 = @embedFile("corpus/borsh/model/da_event_not_found.bin");
        pub const da_event_signed_block: []const u8 = @embedFile("corpus/borsh/model/da_event_signed_block.bin");
        pub const da_event_status: []const u8 = @embedFile("corpus/borsh/model/da_event_status.bin");
        pub const da_request_block: []const u8 = @embedFile("corpus/borsh/model/da_request_block.bin");
        pub const da_request_stream: []const u8 = @embedFile("corpus/borsh/model/da_request_stream.bin");
        pub const data_proposal_empty: []const u8 = @embedFile("corpus/borsh/model/data_proposal_empty.bin");
        pub const data_proposal_parent_dp: []const u8 = @embedFile("corpus/borsh/model/data_proposal_parent_dp.bin");
        pub const data_proposal_parent_lane_root: []const u8 = @embedFile("corpus/borsh/model/data_proposal_parent_lane_root.bin");
        pub const hyli_output: []const u8 = @embedFile("corpus/borsh/model/hyli_output.bin");
        pub const identity_alice: []const u8 = @embedFile("corpus/borsh/model/identity_alice.bin");
        pub const lane_bytes_size_4096: []const u8 = @embedFile("corpus/borsh/model/lane_bytes_size_4096.bin");
        pub const lane_id_default: []const u8 = @embedFile("corpus/borsh/model/lane_id_default.bin");
        pub const mempool_status_event_created: []const u8 = @embedFile("corpus/borsh/model/mempool_status_event_created.bin");
        pub const mempool_status_event_waiting: []const u8 = @embedFile("corpus/borsh/model/mempool_status_event_waiting.bin");
        pub const node_connection_data: []const u8 = @embedFile("corpus/borsh/model/node_connection_data.bin");
        pub const onchain_effect_delete: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_delete.bin");
        pub const onchain_effect_register: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_register.bin");
        pub const onchain_effect_register_with_ctor: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_register_with_ctor.bin");
        pub const onchain_effect_update_program_id: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_update_program_id.bin");
        pub const onchain_effect_update_timeout_no: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_update_timeout_no.bin");
        pub const onchain_effect_update_timeout_yes: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_update_timeout_yes.bin");
        pub const program_id_4_bytes: []const u8 = @embedFile("corpus/borsh/model/program_id_4_bytes.bin");
        pub const proof_transaction: []const u8 = @embedFile("corpus/borsh/model/proof_transaction.bin");
        pub const register_contract_action: []const u8 = @embedFile("corpus/borsh/model/register_contract_action.bin");
        pub const register_contract_effect: []const u8 = @embedFile("corpus/borsh/model/register_contract_effect.bin");
        pub const signature_8_bytes: []const u8 = @embedFile("corpus/borsh/model/signature_8_bytes.bin");
        pub const signed_block_sample: []const u8 = @embedFile("corpus/borsh/model/signed_block_sample.bin");
        pub const signed_node_connection_data: []const u8 = @embedFile("corpus/borsh/model/signed_node_connection_data.bin");
        pub const signed_validator_candidacy: []const u8 = @embedFile("corpus/borsh/model/signed_validator_candidacy.bin");
        pub const staking_action_delegate: []const u8 = @embedFile("corpus/borsh/model/staking_action_delegate.bin");
        pub const staking_action_deposit_for_fees: []const u8 = @embedFile("corpus/borsh/model/staking_action_deposit_for_fees.bin");
        pub const staking_action_stake: []const u8 = @embedFile("corpus/borsh/model/staking_action_stake.bin");
        pub const state_commitment_4_bytes: []const u8 = @embedFile("corpus/borsh/model/state_commitment_4_bytes.bin");
        pub const timeout_window_default: []const u8 = @embedFile("corpus/borsh/model/timeout_window_default.bin");
        pub const timeout_window_no_timeout: []const u8 = @embedFile("corpus/borsh/model/timeout_window_no_timeout.bin");
        pub const timestamp_ms_max_u64: []const u8 = @embedFile("corpus/borsh/model/timestamp_ms_max_u64.bin");
        pub const timestamp_ms_unix_epoch: []const u8 = @embedFile("corpus/borsh/model/timestamp_ms_unix_epoch.bin");
        pub const transaction_blob: []const u8 = @embedFile("corpus/borsh/model/transaction_blob.bin");
        pub const transaction_kind_blob: []const u8 = @embedFile("corpus/borsh/model/transaction_kind_blob.bin");
        pub const transaction_kind_proof: []const u8 = @embedFile("corpus/borsh/model/transaction_kind_proof.bin");
        pub const transaction_kind_verified_proof: []const u8 = @embedFile("corpus/borsh/model/transaction_kind_verified_proof.bin");
        pub const transaction_metadata_blob: []const u8 = @embedFile("corpus/borsh/model/transaction_metadata_blob.bin");
        pub const transaction_proof: []const u8 = @embedFile("corpus/borsh/model/transaction_proof.bin");
        pub const transaction_state_event_dropped: []const u8 = @embedFile("corpus/borsh/model/transaction_state_event_dropped.bin");
        pub const transaction_state_event_error: []const u8 = @embedFile("corpus/borsh/model/transaction_state_event_error.bin");
        pub const transaction_state_event_new_proof: []const u8 = @embedFile("corpus/borsh/model/transaction_state_event_new_proof.bin");
        pub const transaction_state_event_sequenced: []const u8 = @embedFile("corpus/borsh/model/transaction_state_event_sequenced.bin");
        pub const transaction_state_event_settled: []const u8 = @embedFile("corpus/borsh/model/transaction_state_event_settled.bin");
        pub const transaction_state_event_settled_as_failed: []const u8 = @embedFile("corpus/borsh/model/transaction_state_event_settled_as_failed.bin");
        pub const transaction_state_event_timed_out: []const u8 = @embedFile("corpus/borsh/model/transaction_state_event_timed_out.bin");
        pub const tx_context: []const u8 = @embedFile("corpus/borsh/model/tx_context.bin");
        pub const tx_id_sample: []const u8 = @embedFile("corpus/borsh/model/tx_id_sample.bin");
        pub const validator_candidacy: []const u8 = @embedFile("corpus/borsh/model/validator_candidacy.bin");
        pub const validator_public_key: []const u8 = @embedFile("corpus/borsh/model/validator_public_key.bin");
        pub const validator_signature: []const u8 = @embedFile("corpus/borsh/model/validator_signature.bin");
        pub const verified_proof_transaction: []const u8 = @embedFile("corpus/borsh/model/verified_proof_transaction.bin");
        pub const verifier_risc0: []const u8 = @embedFile("corpus/borsh/model/verifier_risc0.bin");
    };
    pub const primitives = struct {
        pub const i32_neg_one: []const u8 = @embedFile("corpus/borsh/primitives/i32_neg_one.bin");
        pub const option_u32_none: []const u8 = @embedFile("corpus/borsh/primitives/option_u32_none.bin");
        pub const option_u32_some_7: []const u8 = @embedFile("corpus/borsh/primitives/option_u32_some_7.bin");
        pub const string_hello: []const u8 = @embedFile("corpus/borsh/primitives/string_hello.bin");
        pub const string_unicode: []const u8 = @embedFile("corpus/borsh/primitives/string_unicode.bin");
        pub const u128_max: []const u8 = @embedFile("corpus/borsh/primitives/u128_max.bin");
        pub const u32_0xdeadbeef: []const u8 = @embedFile("corpus/borsh/primitives/u32_0xdeadbeef.bin");
        pub const u64_one: []const u8 = @embedFile("corpus/borsh/primitives/u64_one.bin");
        pub const u8_42: []const u8 = @embedFile("corpus/borsh/primitives/u8_42.bin");
        pub const vec_u32_two: []const u8 = @embedFile("corpus/borsh/primitives/vec_u32_two.bin");
        pub const vec_u8_three: []const u8 = @embedFile("corpus/borsh/primitives/vec_u8_three.bin");
    };
};

pub const hash = struct {
    pub const model = struct {
        pub const blob_proof_output_sample: []const u8 = @embedFile("corpus/hash/model/blob_proof_output_sample.bin");
        pub const blob_simple: []const u8 = @embedFile("corpus/hash/model/blob_simple.bin");
        pub const blob_transaction: []const u8 = @embedFile("corpus/hash/model/blob_transaction.bin");
        pub const consensus_proposal_empty: []const u8 = @embedFile("corpus/hash/model/consensus_proposal_empty.bin");
        pub const consensus_proposal_full: []const u8 = @embedFile("corpus/hash/model/consensus_proposal_full.bin");
        pub const data_proposal_empty: []const u8 = @embedFile("corpus/hash/model/data_proposal_empty.bin");
        pub const hyli_output: []const u8 = @embedFile("corpus/hash/model/hyli_output.bin");
        pub const onchain_effect_delete: []const u8 = @embedFile("corpus/hash/model/onchain_effect_delete.bin");
        pub const onchain_effect_register: []const u8 = @embedFile("corpus/hash/model/onchain_effect_register.bin");
        pub const onchain_effect_register_with_ctor: []const u8 = @embedFile("corpus/hash/model/onchain_effect_register_with_ctor.bin");
        pub const onchain_effect_update_program_id: []const u8 = @embedFile("corpus/hash/model/onchain_effect_update_program_id.bin");
        pub const onchain_effect_update_timeout_no: []const u8 = @embedFile("corpus/hash/model/onchain_effect_update_timeout_no.bin");
        pub const onchain_effect_update_timeout_yes: []const u8 = @embedFile("corpus/hash/model/onchain_effect_update_timeout_yes.bin");
        pub const proof_data: []const u8 = @embedFile("corpus/hash/model/proof_data.bin");
        pub const proof_transaction: []const u8 = @embedFile("corpus/hash/model/proof_transaction.bin");
        pub const register_contract_action: []const u8 = @embedFile("corpus/hash/model/register_contract_action.bin");
        pub const register_contract_effect: []const u8 = @embedFile("corpus/hash/model/register_contract_effect.bin");
        pub const verified_proof_transaction: []const u8 = @embedFile("corpus/hash/model/verified_proof_transaction.bin");
    };
    pub const primitives = struct {
        pub const sha3_256_empty: []const u8 = @embedFile("corpus/hash/primitives/sha3_256_empty.bin");
    };
};

pub const wire = struct {
    pub const messages = struct {
        pub const handshake_hello_inner: []const u8 = @embedFile("corpus/wire/messages/handshake_hello_inner.bin");
        pub const handshake_verack_inner: []const u8 = @embedFile("corpus/wire/messages/handshake_verack_inner.bin");
        pub const p2p_message_data_inner: []const u8 = @embedFile("corpus/wire/messages/p2p_message_data_inner.bin");
        pub const p2p_message_handshake_hello_framed: []const u8 = @embedFile("corpus/wire/messages/p2p_message_handshake_hello_framed.bin");
        pub const p2p_message_handshake_hello_inner: []const u8 = @embedFile("corpus/wire/messages/p2p_message_handshake_hello_inner.bin");
        pub const tcp_message_data_header_framed: []const u8 = @embedFile("corpus/wire/messages/tcp_message_data_header_framed.bin");
        pub const tcp_message_data_header_inner: []const u8 = @embedFile("corpus/wire/messages/tcp_message_data_header_inner.bin");
        pub const tcp_message_data_simple_framed: []const u8 = @embedFile("corpus/wire/messages/tcp_message_data_simple_framed.bin");
        pub const tcp_message_data_simple_inner: []const u8 = @embedFile("corpus/wire/messages/tcp_message_data_simple_inner.bin");
        pub const tcp_message_ping_framed: []const u8 = @embedFile("corpus/wire/messages/tcp_message_ping_framed.bin");
        pub const tcp_message_ping_inner: []const u8 = @embedFile("corpus/wire/messages/tcp_message_ping_inner.bin");
    };
};

