//! Auto-generated by `compat/fixture-gen`. Do not edit by hand.
//!
//! Each constant points at a Borsh or hash fixture under
//! `compat/corpus/`. The Zig side embeds the bytes at compile
//! time, so a missing or renamed fixture surfaces as a build
//! error long before any test runs.
//!
//! Source: hyli git revision `e41899eb582d2d25d13a97a425ec76250484d45c`.

pub const borsh = struct {
    pub const crypto = struct {
        pub const bls_min_pk_dst: []const u8 = @embedFile("corpus/borsh/crypto/bls_min_pk_dst.bin");
        pub const signable_node_connection_data: []const u8 = @embedFile("corpus/borsh/crypto/signable_node_connection_data.bin");
        pub const signable_validator_candidacy: []const u8 = @embedFile("corpus/borsh/crypto/signable_validator_candidacy.bin");
    };
    pub const model = struct {
        pub const aggregate_signature_2: []const u8 = @embedFile("corpus/borsh/model/aggregate_signature_2.bin");
        pub const blob_index_3: []const u8 = @embedFile("corpus/borsh/model/blob_index_3.bin");
        pub const blob_simple: []const u8 = @embedFile("corpus/borsh/model/blob_simple.bin");
        pub const blob_transaction: []const u8 = @embedFile("corpus/borsh/model/blob_transaction.bin");
        pub const blobs_hashes_empty: []const u8 = @embedFile("corpus/borsh/model/blobs_hashes_empty.bin");
        pub const blobs_hashes_two: []const u8 = @embedFile("corpus/borsh/model/blobs_hashes_two.bin");
        pub const block_height_42: []const u8 = @embedFile("corpus/borsh/model/block_height_42.bin");
        pub const calldata: []const u8 = @embedFile("corpus/borsh/model/calldata.bin");
        pub const canal_p2p: []const u8 = @embedFile("corpus/borsh/model/canal_p2p.bin");
        pub const consensus_proposal_empty: []const u8 = @embedFile("corpus/borsh/model/consensus_proposal_empty.bin");
        pub const consensus_proposal_full: []const u8 = @embedFile("corpus/borsh/model/consensus_proposal_full.bin");
        pub const consensus_staking_action_bond: []const u8 = @embedFile("corpus/borsh/model/consensus_staking_action_bond.bin");
        pub const consensus_staking_action_pay: []const u8 = @embedFile("corpus/borsh/model/consensus_staking_action_pay.bin");
        pub const contract_name_hyli: []const u8 = @embedFile("corpus/borsh/model/contract_name_hyli.bin");
        pub const data_proposal_empty: []const u8 = @embedFile("corpus/borsh/model/data_proposal_empty.bin");
        pub const data_proposal_parent_dp: []const u8 = @embedFile("corpus/borsh/model/data_proposal_parent_dp.bin");
        pub const data_proposal_parent_lane_root: []const u8 = @embedFile("corpus/borsh/model/data_proposal_parent_lane_root.bin");
        pub const hyli_output: []const u8 = @embedFile("corpus/borsh/model/hyli_output.bin");
        pub const identity_alice: []const u8 = @embedFile("corpus/borsh/model/identity_alice.bin");
        pub const lane_bytes_size_4096: []const u8 = @embedFile("corpus/borsh/model/lane_bytes_size_4096.bin");
        pub const lane_id_default: []const u8 = @embedFile("corpus/borsh/model/lane_id_default.bin");
        pub const node_connection_data: []const u8 = @embedFile("corpus/borsh/model/node_connection_data.bin");
        pub const onchain_effect_delete: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_delete.bin");
        pub const onchain_effect_register: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_register.bin");
        pub const onchain_effect_register_with_ctor: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_register_with_ctor.bin");
        pub const onchain_effect_update_program_id: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_update_program_id.bin");
        pub const onchain_effect_update_timeout_no: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_update_timeout_no.bin");
        pub const onchain_effect_update_timeout_yes: []const u8 = @embedFile("corpus/borsh/model/onchain_effect_update_timeout_yes.bin");
        pub const program_id_4_bytes: []const u8 = @embedFile("corpus/borsh/model/program_id_4_bytes.bin");
        pub const proof_transaction: []const u8 = @embedFile("corpus/borsh/model/proof_transaction.bin");
        pub const register_contract_action: []const u8 = @embedFile("corpus/borsh/model/register_contract_action.bin");
        pub const register_contract_effect: []const u8 = @embedFile("corpus/borsh/model/register_contract_effect.bin");
        pub const signature_8_bytes: []const u8 = @embedFile("corpus/borsh/model/signature_8_bytes.bin");
        pub const signed_node_connection_data: []const u8 = @embedFile("corpus/borsh/model/signed_node_connection_data.bin");
        pub const signed_validator_candidacy: []const u8 = @embedFile("corpus/borsh/model/signed_validator_candidacy.bin");
        pub const state_commitment_4_bytes: []const u8 = @embedFile("corpus/borsh/model/state_commitment_4_bytes.bin");
        pub const timeout_window_default: []const u8 = @embedFile("corpus/borsh/model/timeout_window_default.bin");
        pub const timeout_window_no_timeout: []const u8 = @embedFile("corpus/borsh/model/timeout_window_no_timeout.bin");
        pub const timestamp_ms_max_u64: []const u8 = @embedFile("corpus/borsh/model/timestamp_ms_max_u64.bin");
        pub const timestamp_ms_unix_epoch: []const u8 = @embedFile("corpus/borsh/model/timestamp_ms_unix_epoch.bin");
        pub const transaction_blob: []const u8 = @embedFile("corpus/borsh/model/transaction_blob.bin");
        pub const transaction_proof: []const u8 = @embedFile("corpus/borsh/model/transaction_proof.bin");
        pub const tx_context: []const u8 = @embedFile("corpus/borsh/model/tx_context.bin");
        pub const validator_candidacy: []const u8 = @embedFile("corpus/borsh/model/validator_candidacy.bin");
        pub const validator_public_key: []const u8 = @embedFile("corpus/borsh/model/validator_public_key.bin");
        pub const validator_signature: []const u8 = @embedFile("corpus/borsh/model/validator_signature.bin");
        pub const verified_proof_transaction: []const u8 = @embedFile("corpus/borsh/model/verified_proof_transaction.bin");
        pub const verifier_risc0: []const u8 = @embedFile("corpus/borsh/model/verifier_risc0.bin");
    };
    pub const primitives = struct {
        pub const i32_neg_one: []const u8 = @embedFile("corpus/borsh/primitives/i32_neg_one.bin");
        pub const option_u32_none: []const u8 = @embedFile("corpus/borsh/primitives/option_u32_none.bin");
        pub const option_u32_some_7: []const u8 = @embedFile("corpus/borsh/primitives/option_u32_some_7.bin");
        pub const string_hello: []const u8 = @embedFile("corpus/borsh/primitives/string_hello.bin");
        pub const string_unicode: []const u8 = @embedFile("corpus/borsh/primitives/string_unicode.bin");
        pub const u128_max: []const u8 = @embedFile("corpus/borsh/primitives/u128_max.bin");
        pub const u32_0xdeadbeef: []const u8 = @embedFile("corpus/borsh/primitives/u32_0xdeadbeef.bin");
        pub const u64_one: []const u8 = @embedFile("corpus/borsh/primitives/u64_one.bin");
        pub const u8_42: []const u8 = @embedFile("corpus/borsh/primitives/u8_42.bin");
        pub const vec_u32_two: []const u8 = @embedFile("corpus/borsh/primitives/vec_u32_two.bin");
        pub const vec_u8_three: []const u8 = @embedFile("corpus/borsh/primitives/vec_u8_three.bin");
    };
};

pub const hash = struct {
    pub const model = struct {
        pub const blob_simple: []const u8 = @embedFile("corpus/hash/model/blob_simple.bin");
        pub const blob_transaction: []const u8 = @embedFile("corpus/hash/model/blob_transaction.bin");
        pub const consensus_proposal_empty: []const u8 = @embedFile("corpus/hash/model/consensus_proposal_empty.bin");
        pub const consensus_proposal_full: []const u8 = @embedFile("corpus/hash/model/consensus_proposal_full.bin");
        pub const data_proposal_empty: []const u8 = @embedFile("corpus/hash/model/data_proposal_empty.bin");
        pub const hyli_output: []const u8 = @embedFile("corpus/hash/model/hyli_output.bin");
        pub const onchain_effect_delete: []const u8 = @embedFile("corpus/hash/model/onchain_effect_delete.bin");
        pub const onchain_effect_register: []const u8 = @embedFile("corpus/hash/model/onchain_effect_register.bin");
        pub const onchain_effect_register_with_ctor: []const u8 = @embedFile("corpus/hash/model/onchain_effect_register_with_ctor.bin");
        pub const onchain_effect_update_program_id: []const u8 = @embedFile("corpus/hash/model/onchain_effect_update_program_id.bin");
        pub const onchain_effect_update_timeout_no: []const u8 = @embedFile("corpus/hash/model/onchain_effect_update_timeout_no.bin");
        pub const onchain_effect_update_timeout_yes: []const u8 = @embedFile("corpus/hash/model/onchain_effect_update_timeout_yes.bin");
        pub const proof_data: []const u8 = @embedFile("corpus/hash/model/proof_data.bin");
        pub const proof_transaction: []const u8 = @embedFile("corpus/hash/model/proof_transaction.bin");
        pub const register_contract_action: []const u8 = @embedFile("corpus/hash/model/register_contract_action.bin");
        pub const register_contract_effect: []const u8 = @embedFile("corpus/hash/model/register_contract_effect.bin");
        pub const verified_proof_transaction: []const u8 = @embedFile("corpus/hash/model/verified_proof_transaction.bin");
    };
    pub const primitives = struct {
        pub const sha3_256_empty: []const u8 = @embedFile("corpus/hash/primitives/sha3_256_empty.bin");
    };
};

pub const wire = struct {
    pub const messages = struct {
        pub const handshake_hello_inner: []const u8 = @embedFile("corpus/wire/messages/handshake_hello_inner.bin");
        pub const handshake_verack_inner: []const u8 = @embedFile("corpus/wire/messages/handshake_verack_inner.bin");
        pub const p2p_message_data_inner: []const u8 = @embedFile("corpus/wire/messages/p2p_message_data_inner.bin");
        pub const p2p_message_handshake_hello_framed: []const u8 = @embedFile("corpus/wire/messages/p2p_message_handshake_hello_framed.bin");
        pub const p2p_message_handshake_hello_inner: []const u8 = @embedFile("corpus/wire/messages/p2p_message_handshake_hello_inner.bin");
        pub const tcp_message_data_header_framed: []const u8 = @embedFile("corpus/wire/messages/tcp_message_data_header_framed.bin");
        pub const tcp_message_data_header_inner: []const u8 = @embedFile("corpus/wire/messages/tcp_message_data_header_inner.bin");
        pub const tcp_message_data_simple_framed: []const u8 = @embedFile("corpus/wire/messages/tcp_message_data_simple_framed.bin");
        pub const tcp_message_data_simple_inner: []const u8 = @embedFile("corpus/wire/messages/tcp_message_data_simple_inner.bin");
        pub const tcp_message_ping_framed: []const u8 = @embedFile("corpus/wire/messages/tcp_message_ping_framed.bin");
        pub const tcp_message_ping_inner: []const u8 = @embedFile("corpus/wire/messages/tcp_message_ping_inner.bin");
    };
};

