//! Auto-generated by `compat/fixture-gen`. Do not edit by hand.
//!
//! Each constant points at a Borsh or hash fixture under
//! `compat/corpus/`. The Zig side embeds the bytes at compile
//! time, so a missing or renamed fixture surfaces as a build
//! error long before any test runs.
//!
//! Source: hyli git revision `e41899eb582d2d25d13a97a425ec76250484d45c`.

pub const borsh = struct {
    pub const model = struct {
        pub const blob_index_3: []const u8 = @embedFile("corpus/borsh/model/blob_index_3.bin");
        pub const blob_simple: []const u8 = @embedFile("corpus/borsh/model/blob_simple.bin");
        pub const block_height_42: []const u8 = @embedFile("corpus/borsh/model/block_height_42.bin");
        pub const contract_name_hyli: []const u8 = @embedFile("corpus/borsh/model/contract_name_hyli.bin");
        pub const data_proposal_empty: []const u8 = @embedFile("corpus/borsh/model/data_proposal_empty.bin");
        pub const data_proposal_parent_dp: []const u8 = @embedFile("corpus/borsh/model/data_proposal_parent_dp.bin");
        pub const data_proposal_parent_lane_root: []const u8 = @embedFile("corpus/borsh/model/data_proposal_parent_lane_root.bin");
        pub const identity_alice: []const u8 = @embedFile("corpus/borsh/model/identity_alice.bin");
        pub const lane_id_default: []const u8 = @embedFile("corpus/borsh/model/lane_id_default.bin");
        pub const program_id_4_bytes: []const u8 = @embedFile("corpus/borsh/model/program_id_4_bytes.bin");
        pub const register_contract_action: []const u8 = @embedFile("corpus/borsh/model/register_contract_action.bin");
        pub const state_commitment_4_bytes: []const u8 = @embedFile("corpus/borsh/model/state_commitment_4_bytes.bin");
        pub const timeout_window_default: []const u8 = @embedFile("corpus/borsh/model/timeout_window_default.bin");
        pub const timeout_window_no_timeout: []const u8 = @embedFile("corpus/borsh/model/timeout_window_no_timeout.bin");
        pub const timestamp_ms_max_u64: []const u8 = @embedFile("corpus/borsh/model/timestamp_ms_max_u64.bin");
        pub const timestamp_ms_unix_epoch: []const u8 = @embedFile("corpus/borsh/model/timestamp_ms_unix_epoch.bin");
        pub const verifier_risc0: []const u8 = @embedFile("corpus/borsh/model/verifier_risc0.bin");
    };
    pub const primitives = struct {
        pub const i32_neg_one: []const u8 = @embedFile("corpus/borsh/primitives/i32_neg_one.bin");
        pub const option_u32_none: []const u8 = @embedFile("corpus/borsh/primitives/option_u32_none.bin");
        pub const option_u32_some_7: []const u8 = @embedFile("corpus/borsh/primitives/option_u32_some_7.bin");
        pub const string_hello: []const u8 = @embedFile("corpus/borsh/primitives/string_hello.bin");
        pub const string_unicode: []const u8 = @embedFile("corpus/borsh/primitives/string_unicode.bin");
        pub const u128_max: []const u8 = @embedFile("corpus/borsh/primitives/u128_max.bin");
        pub const u32_0xdeadbeef: []const u8 = @embedFile("corpus/borsh/primitives/u32_0xdeadbeef.bin");
        pub const u64_one: []const u8 = @embedFile("corpus/borsh/primitives/u64_one.bin");
        pub const u8_42: []const u8 = @embedFile("corpus/borsh/primitives/u8_42.bin");
        pub const vec_u32_two: []const u8 = @embedFile("corpus/borsh/primitives/vec_u32_two.bin");
        pub const vec_u8_three: []const u8 = @embedFile("corpus/borsh/primitives/vec_u8_three.bin");
    };
};

pub const hash = struct {
    pub const model = struct {
        pub const blob_simple: []const u8 = @embedFile("corpus/hash/model/blob_simple.bin");
        pub const data_proposal_empty: []const u8 = @embedFile("corpus/hash/model/data_proposal_empty.bin");
        pub const register_contract_action: []const u8 = @embedFile("corpus/hash/model/register_contract_action.bin");
    };
    pub const primitives = struct {
        pub const sha3_256_empty: []const u8 = @embedFile("corpus/hash/primitives/sha3_256_empty.bin");
    };
};

