//! Zyli fixture generator.
//!
//! Produces a versioned, deterministic corpus of Borsh-encoded byte vectors
//! and SHA3-256 hash digests under `../corpus/`. The Zig side embeds these
//! files at compile time and asserts byte equivalence.
//!
//! Two design rules:
//!   1. The output is a function of the source code only — no clock, no env,
//!      no RNG. Re-running must produce zero diffs.
//!   2. Every fixture name appears in `INDEX.md` with the type it represents
//!      and the upstream Hyli git revision used to generate it.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use borsh::BorshSerialize;
use hyli_model::{
    utils::TimestampMs, AggregateSignature, Blob, BlobData, BlobHash, BlobIndex,
    BlobProofOutput, BlobTransaction, BlobsHashes, BlockHeight, Calldata, ConsensusProposal,
    ConsensusProposalHash, ConsensusStakingAction, ContractName, DataAvailabilityEvent,
    DataAvailabilityRequest, DataProposal, DataProposalHash, DataProposalParent, Hashed,
    HyliOutput, Identity, IndexedBlobs, LaneBytesSize, LaneId, MempoolStatusEvent, OnchainEffect,
    ProgramId, ProofData, ProofDataHash, ProofTransaction, RegisterContractAction,
    RegisterContractEffect, Signature, Signed, SignedBlock, StateCommitment, TimeoutWindow,
    Transaction, TransactionData, TransactionKind, TransactionMetadata, TxContext, TxHash, TxId,
    ValidatorCandidacy, ValidatorPublicKey, ValidatorSignature, Verifier, VerifiedProofTransaction,
};
use sha3::Digest as _;

/// Records a single fixture's metadata for the human-readable index.
struct FixtureRecord {
    /// Path relative to `corpus/` where the bytes were written.
    relative_path: String,
    /// Rust type the fixture represents.
    rust_type: &'static str,
    /// One-sentence description of the value.
    description: String,
    /// Length of the encoded payload (handy when scanning the index).
    byte_len: usize,
}

struct Generator {
    corpus_root: PathBuf,
    records: Vec<FixtureRecord>,
}

impl Generator {
    fn new(corpus_root: PathBuf) -> Self {
        Self {
            corpus_root,
            records: Vec::new(),
        }
    }

    /// Borsh-encode `value` and write the bytes to `<corpus>/borsh/<rel>.bin`.
    fn write_borsh<T: BorshSerialize>(
        &mut self,
        rel: &str,
        rust_type: &'static str,
        description: impl Into<String>,
        value: &T,
    ) {
        let bytes = borsh::to_vec(value).expect("borsh encode");
        self.write_bytes("borsh", rel, rust_type, description.into(), bytes);
    }

    /// Write a raw SHA3-256 digest to `<corpus>/hash/<rel>.bin`.
    fn write_hash(
        &mut self,
        rel: &str,
        rust_type: &'static str,
        description: impl Into<String>,
        digest: Vec<u8>,
    ) {
        self.write_bytes("hash", rel, rust_type, description.into(), digest);
    }

    fn write_bytes(
        &mut self,
        category: &str,
        rel: &str,
        rust_type: &'static str,
        description: String,
        bytes: Vec<u8>,
    ) {
        let path = self.corpus_root.join(category).join(format!("{rel}.bin"));
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("mkdir -p corpus subdir");
        }
        fs::write(&path, &bytes).expect("write fixture");
        self.records.push(FixtureRecord {
            relative_path: format!("{category}/{rel}.bin"),
            rust_type,
            description,
            byte_len: bytes.len(),
        });
    }

    /// Write the human-readable index file. Sorted so the file is stable.
    fn write_index(&mut self, hyli_rev: &str) {
        self.records
            .sort_by(|a, b| a.relative_path.cmp(&b.relative_path));
        let mut out = String::new();
        out.push_str("# Zyli compatibility corpus\n\n");
        out.push_str(
            "Auto-generated by `compat/fixture-gen`. Do not edit by hand — \
             rerun the generator to update.\n\n",
        );
        out.push_str(&format!("Source: `hyli` git revision `{hyli_rev}`.\n\n"));
        out.push_str("| Path | Rust type | Bytes | Description |\n");
        out.push_str("|------|-----------|-------|-------------|\n");
        for rec in &self.records {
            out.push_str(&format!(
                "| `{}` | `{}` | {} | {} |\n",
                rec.relative_path, rec.rust_type, rec.byte_len, rec.description,
            ));
        }
        let path = self.corpus_root.join("INDEX.md");
        let mut f = fs::File::create(&path).expect("create INDEX.md");
        f.write_all(out.as_bytes()).expect("write INDEX.md");
    }

    /// Emit a Zig manifest at `compat/corpus.zig` that re-exports every
    /// fixture as an `@embedFile` constant.
    ///
    /// Why generate this instead of writing it by hand: keeping the manifest
    /// in lock-step with the corpus is the only way to guarantee a fixture
    /// rename or addition can never silently break a Zig test (you'd get a
    /// compile error on the next `zig build`). The manifest lives at
    /// `compat/corpus.zig` so its package root is `compat/`, which is the
    /// directory `@embedFile` is restricted to.
    fn write_zig_manifest(&self, hyli_rev: &str) {
        // The manifest path is the parent of `corpus_root`.
        let manifest_path = self
            .corpus_root
            .parent()
            .expect("corpus root has parent")
            .join("corpus.zig");

        // Build a tree of (category -> subcategory -> [(name, rel_path)]).
        // For us "category" is `borsh` or `hash`, "subcategory" is the next
        // path component (e.g. `primitives`, `model`), and `name` is the
        // file stem.
        use std::collections::BTreeMap;
        type Tree = BTreeMap<String, BTreeMap<String, Vec<(String, String)>>>;
        let mut tree: Tree = BTreeMap::new();
        for rec in &self.records {
            let parts: Vec<&str> = rec.relative_path.split('/').collect();
            if parts.len() != 3 {
                panic!("unexpected fixture path: {}", rec.relative_path);
            }
            let category = parts[0];
            let sub = parts[1];
            let stem = parts[2]
                .strip_suffix(".bin")
                .expect("fixture filename ends in .bin");
            tree.entry(category.to_string())
                .or_default()
                .entry(sub.to_string())
                .or_default()
                .push((stem.to_string(), rec.relative_path.clone()));
        }

        let mut out = String::new();
        out.push_str(
            "//! Auto-generated by `compat/fixture-gen`. Do not edit by hand.\n\
             //!\n\
             //! Each constant points at a Borsh or hash fixture under\n\
             //! `compat/corpus/`. The Zig side embeds the bytes at compile\n\
             //! time, so a missing or renamed fixture surfaces as a build\n\
             //! error long before any test runs.\n\
             //!\n",
        );
        out.push_str(&format!("//! Source: hyli git revision `{hyli_rev}`.\n\n"));
        for (category, subs) in &tree {
            out.push_str(&format!("pub const {category} = struct {{\n"));
            for (sub, items) in subs {
                out.push_str(&format!("    pub const {sub} = struct {{\n"));
                for (stem, rel_path) in items {
                    out.push_str(&format!(
                        "        pub const {stem}: []const u8 = @embedFile(\"corpus/{rel_path}\");\n",
                    ));
                }
                out.push_str("    };\n");
            }
            out.push_str("};\n\n");
        }
        fs::write(&manifest_path, out).expect("write corpus.zig");
    }
}

/// Best-effort lookup of the upstream Hyli git revision so the corpus can
/// always be traced back to a specific source. Falls back to `unknown` if the
/// repository or git binary is unavailable.
fn detect_hyli_revision() -> String {
    use std::process::Command;
    let hyli_dir = Path::new("../../../hyli");
    let output = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(hyli_dir)
        .output();
    match output {
        Ok(out) if out.status.success() => String::from_utf8_lossy(&out.stdout).trim().to_string(),
        _ => "unknown".to_string(),
    }
}

fn main() {
    // Resolve corpus root relative to the crate manifest so the binary works
    // regardless of the cwd it was launched from.
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let corpus_root = Path::new(manifest_dir).join("..").join("corpus");
    if corpus_root.exists() {
        // Wipe stale fixtures so the rerun is byte-for-byte identical.
        fs::remove_dir_all(&corpus_root).expect("clean corpus directory");
    }
    fs::create_dir_all(&corpus_root).expect("create corpus directory");

    let mut gen = Generator::new(corpus_root);

    // ---- T0 primitives -----------------------------------------------------
    gen.write_borsh(
        "primitives/u8_42",
        "u8",
        "single byte 42",
        &42u8,
    );
    gen.write_borsh(
        "primitives/u32_0xdeadbeef",
        "u32",
        "0xdeadbeef little-endian",
        &0xdeadbeef_u32,
    );
    gen.write_borsh(
        "primitives/u64_one",
        "u64",
        "u64::1 little-endian",
        &1u64,
    );
    gen.write_borsh(
        "primitives/u128_max",
        "u128",
        "u128::MAX",
        &u128::MAX,
    );
    gen.write_borsh(
        "primitives/i32_neg_one",
        "i32",
        "-1 as two's complement",
        &-1i32,
    );
    gen.write_borsh(
        "primitives/option_u32_some_7",
        "Option<u32>",
        "Some(7)",
        &Some(7u32),
    );
    gen.write_borsh(
        "primitives/option_u32_none",
        "Option<u32>",
        "None",
        &Option::<u32>::None,
    );
    gen.write_borsh(
        "primitives/string_hello",
        "String",
        "ASCII string \"hello\"",
        &"hello".to_string(),
    );
    gen.write_borsh(
        "primitives/string_unicode",
        "String",
        "UTF-8 \"héllo🦀\"",
        &"héllo🦀".to_string(),
    );
    gen.write_borsh(
        "primitives/vec_u8_three",
        "Vec<u8>",
        "[1, 2, 3]",
        &vec![1u8, 2, 3],
    );
    gen.write_borsh(
        "primitives/vec_u32_two",
        "Vec<u32>",
        "[1, 2]",
        &vec![1u32, 2u32],
    );

    // ---- T1 newtypes -------------------------------------------------------
    gen.write_borsh(
        "model/identity_alice",
        "hyli_model::Identity",
        "Identity(\"alice@hyli\")",
        &Identity("alice@hyli".to_string()),
    );
    gen.write_borsh(
        "model/contract_name_hyli",
        "hyli_model::ContractName",
        "ContractName(\"hyli\")",
        &ContractName("hyli".to_string()),
    );
    gen.write_borsh(
        "model/program_id_4_bytes",
        "hyli_model::ProgramId",
        "ProgramId([0xde,0xad,0xbe,0xef])",
        &ProgramId(vec![0xde, 0xad, 0xbe, 0xef]),
    );
    gen.write_borsh(
        "model/verifier_risc0",
        "hyli_model::Verifier",
        "Verifier(\"risc0\")",
        &Verifier("risc0".to_string()),
    );
    gen.write_borsh(
        "model/blob_index_3",
        "hyli_model::BlobIndex",
        "BlobIndex(3) — note: usize → u64 on the wire",
        &BlobIndex(3),
    );
    gen.write_borsh(
        "model/state_commitment_4_bytes",
        "hyli_model::StateCommitment",
        "StateCommitment([0,1,2,3])",
        &StateCommitment(vec![0, 1, 2, 3]),
    );
    gen.write_borsh(
        "model/block_height_42",
        "hyli_model::BlockHeight",
        "BlockHeight(42)",
        &BlockHeight(42),
    );
    gen.write_borsh(
        "model/timestamp_ms_unix_epoch",
        "hyli_model::TimestampMs",
        "TimestampMs(0) — sanity for u128 layout",
        &TimestampMs(0),
    );
    gen.write_borsh(
        "model/timestamp_ms_max_u64",
        "hyli_model::TimestampMs",
        "TimestampMs(u64::MAX as u128)",
        &TimestampMs(u64::MAX as u128),
    );
    gen.write_borsh(
        "model/timeout_window_no_timeout",
        "hyli_model::TimeoutWindow",
        "TimeoutWindow::NoTimeout",
        &TimeoutWindow::NoTimeout,
    );
    gen.write_borsh(
        "model/timeout_window_default",
        "hyli_model::TimeoutWindow",
        "TimeoutWindow::Timeout { hard=100, soft=100 }",
        &TimeoutWindow::default(),
    );
    gen.write_borsh(
        "model/lane_id_default",
        "hyli_model::LaneId",
        "LaneId::default()",
        &LaneId::default(),
    );

    // ---- T1 protocol structs ----------------------------------------------
    let blob = Blob {
        contract_name: ContractName("hyli".to_string()),
        data: BlobData(vec![0x01, 0x02, 0x03]),
    };
    gen.write_borsh(
        "model/blob_simple",
        "hyli_model::Blob",
        "Blob { contract_name=\"hyli\", data=[1,2,3] }",
        &blob,
    );
    gen.write_hash(
        "model/blob_simple",
        "hyli_model::Blob",
        "Blob::hashed for the matching borsh fixture",
        blob.hashed().0,
    );

    // RegisterContractAction with a constructor_metadata: this exercises the
    // Option<Vec<u8>> field that is `borsh(skip)`-equivalent for the hash but
    // present on the wire.
    let register = RegisterContractAction {
        verifier: Verifier("risc0".to_string()),
        program_id: ProgramId(vec![0xaa; 8]),
        state_commitment: StateCommitment(vec![0xbb; 8]),
        contract_name: ContractName("counter".to_string()),
        timeout_window: Some(TimeoutWindow::Timeout {
            hard_timeout: BlockHeight(50),
            soft_timeout: BlockHeight(100),
        }),
        constructor_metadata: Some(vec![0xcc; 4]),
    };
    gen.write_borsh(
        "model/register_contract_action",
        "hyli_model::RegisterContractAction",
        "Sample RegisterContractAction with timeout + constructor metadata",
        &register,
    );
    gen.write_hash(
        "model/register_contract_action",
        "hyli_model::RegisterContractAction",
        "RegisterContractAction::hashed (constructor_metadata excluded)",
        register.hashed().0,
    );

    // DataProposal with no transactions and a fixed parent hash. Useful as a
    // first sanity vector for the DA layer.
    let dp = DataProposal::new(DataProposalHash(b"parent".to_vec()), vec![]);
    gen.write_borsh(
        "model/data_proposal_empty",
        "hyli_model::DataProposal",
        "DataProposal::new(parent=\"parent\", txs=[])",
        &dp,
    );
    gen.write_hash(
        "model/data_proposal_empty",
        "hyli_model::DataProposal",
        "DataProposal::hashed for the empty-tx case",
        dp.hashed().0,
    );

    // SHA3-256 of the empty input — useful as a baseline for the hash module
    // before we start matching custom Hyli digest constructions.
    let empty_sha3 = sha3::Sha3_256::digest(b"").to_vec();
    gen.write_hash(
        "primitives/sha3_256_empty",
        "sha3::Sha3_256",
        "SHA3-256 of empty input",
        empty_sha3,
    );

    // Cover DataProposalParent enum variants explicitly.
    gen.write_borsh(
        "model/data_proposal_parent_lane_root",
        "hyli_model::DataProposalParent",
        "DataProposalParent::LaneRoot(LaneId::default())",
        &DataProposalParent::LaneRoot(LaneId::default()),
    );
    gen.write_borsh(
        "model/data_proposal_parent_dp",
        "hyli_model::DataProposalParent",
        "DataProposalParent::DP(\"parent\")",
        &DataProposalParent::DP(DataProposalHash(b"parent".to_vec())),
    );

    // ---- T1: Transaction family --------------------------------------------
    //
    // BlobTransaction with two blobs. Identity is `alice@hyli` so the
    // identity-validation rule (the "@<contract>" suffix must match a
    // blob's contract_name) holds. The hash_cache and blobshash_cache
    // fields are `#[borsh(skip)]` and must NOT show up in the wire bytes,
    // so the encoded length is purely identity + blobs.
    let blob_tx_blobs = vec![
        Blob {
            contract_name: ContractName("hyli".to_string()),
            data: BlobData(vec![0xaa, 0xbb]),
        },
        Blob {
            contract_name: ContractName("counter".to_string()),
            data: BlobData(vec![0x01, 0x02, 0x03, 0x04]),
        },
    ];
    let blob_tx = BlobTransaction::new("alice@hyli", blob_tx_blobs.clone());
    gen.write_borsh(
        "model/blob_transaction",
        "hyli_model::BlobTransaction",
        "BlobTransaction(alice@hyli, [Blob(hyli,…), Blob(counter,…)])",
        &blob_tx,
    );
    gen.write_hash(
        "model/blob_transaction",
        "hyli_model::BlobTransaction",
        "BlobTransaction::hashed for the matching borsh fixture",
        blob_tx.hashed().0,
    );

    // ProofTransaction sample. Note: ProofData is the raw proof bytes,
    // ProofDataHash is sha3_256 of the ProofData; the latter is what gets
    // mixed into TxHash, not the proof itself.
    let proof_data = ProofData(vec![0x42; 16]);
    let proof_tx = ProofTransaction {
        contract_name: ContractName("counter".to_string()),
        program_id: ProgramId(vec![0xde, 0xad]),
        verifier: Verifier("risc0".to_string()),
        proof: proof_data.clone(),
    };
    gen.write_borsh(
        "model/proof_transaction",
        "hyli_model::ProofTransaction",
        "ProofTransaction(counter, risc0, ProofData([0x42; 16]))",
        &proof_tx,
    );
    gen.write_hash(
        "model/proof_transaction",
        "hyli_model::ProofTransaction",
        "ProofTransaction::hashed",
        proof_tx.hashed().0,
    );
    gen.write_hash(
        "model/proof_data",
        "hyli_model::ProofData",
        "ProofData::hashed for [0x42; 16]",
        proof_data.hashed().0,
    );

    // VerifiedProofTransaction. proof = None on this fixture so we exercise
    // the Option<ProofData> = None path. The hash should be identical to
    // ProofTransaction's because both feed program_id, verifier,
    // contract_name, and proof_hash into the hasher.
    let proof_data_hash = ProofDataHash(proof_data.hashed().0.clone());
    let verified_proof_tx = VerifiedProofTransaction {
        contract_name: ContractName("counter".to_string()),
        program_id: ProgramId(vec![0xde, 0xad]),
        verifier: Verifier("risc0".to_string()),
        proof: None,
        proof_hash: proof_data_hash.clone(),
        proof_size: proof_data.0.len(),
        proven_blobs: vec![],
        is_recursive: false,
    };
    gen.write_borsh(
        "model/verified_proof_transaction",
        "hyli_model::VerifiedProofTransaction",
        "VerifiedProofTransaction(counter, proof=None, proof_size=16)",
        &verified_proof_tx,
    );
    gen.write_hash(
        "model/verified_proof_transaction",
        "hyli_model::VerifiedProofTransaction",
        "VerifiedProofTransaction::hashed",
        verified_proof_tx.hashed().0,
    );

    // Transaction wrapping a BlobTransaction — exercises the enum-tagged
    // `TransactionData` envelope. The version field should land first
    // (it's a struct field declared before transaction_data).
    let tx_blob = Transaction {
        version: 1,
        transaction_data: TransactionData::Blob(blob_tx.clone()),
    };
    gen.write_borsh(
        "model/transaction_blob",
        "hyli_model::Transaction",
        "Transaction { version=1, data=Blob(...) }",
        &tx_blob,
    );

    // Transaction wrapping a ProofTransaction.
    let tx_proof = Transaction {
        version: 1,
        transaction_data: TransactionData::Proof(proof_tx.clone()),
    };
    gen.write_borsh(
        "model/transaction_proof",
        "hyli_model::Transaction",
        "Transaction { version=1, data=Proof(...) }",
        &tx_proof,
    );

    // ---- T1: Signed envelopes ----------------------------------------------
    //
    // Signed<ValidatorCandidacy, ValidatorSignature> is the canonical
    // SignedByValidator<T> shape used for consensus messages. We pin both
    // a representative concrete payload and the standalone signature
    // newtypes so the Zig side can validate the envelope and the inner
    // crypto bytes independently.
    let validator_pubkey = ValidatorPublicKey(vec![0x01; 4]);
    gen.write_borsh(
        "model/validator_public_key",
        "hyli_model::ValidatorPublicKey",
        "ValidatorPublicKey([0x01; 4])",
        &validator_pubkey,
    );
    let signature = Signature(vec![0xff; 8]);
    gen.write_borsh(
        "model/signature_8_bytes",
        "hyli_model::Signature",
        "Signature([0xff; 8])",
        &signature,
    );
    let validator_signature = ValidatorSignature {
        signature: signature.clone(),
        validator: validator_pubkey.clone(),
    };
    gen.write_borsh(
        "model/validator_signature",
        "hyli_model::ValidatorSignature",
        "ValidatorSignature { sig=[0xff;8], validator=[0x01;4] }",
        &validator_signature,
    );
    let candidacy = ValidatorCandidacy {
        peer_address: "127.0.0.1:4242".to_string(),
    };
    gen.write_borsh(
        "model/validator_candidacy",
        "hyli_model::ValidatorCandidacy",
        "ValidatorCandidacy { peer_address=\"127.0.0.1:4242\" }",
        &candidacy,
    );
    let signed_candidacy: Signed<ValidatorCandidacy, ValidatorSignature> = Signed {
        msg: candidacy.clone(),
        signature: validator_signature.clone(),
    };
    gen.write_borsh(
        "model/signed_validator_candidacy",
        "hyli_model::Signed<ValidatorCandidacy, ValidatorSignature>",
        "SignedByValidator<ValidatorCandidacy>",
        &signed_candidacy,
    );

    // AggregateSignature exercising 2 validators. This is the wire shape used
    // for PoDA and consensus aggregate proofs.
    let agg = AggregateSignature {
        signature: Signature(vec![0xee; 12]),
        validators: vec![
            ValidatorPublicKey(vec![0x01; 4]),
            ValidatorPublicKey(vec![0x02; 4]),
        ],
    };
    gen.write_borsh(
        "model/aggregate_signature_2",
        "hyli_model::AggregateSignature",
        "AggregateSignature with 2 validators",
        &agg,
    );

    // ---- T1: Consensus -----------------------------------------------------
    //
    // ConsensusStakingAction enum, both variants individually.
    let staking_bond = ConsensusStakingAction::Bond {
        candidate: Box::new(Signed::<ValidatorCandidacy, ValidatorSignature> {
            msg: ValidatorCandidacy {
                peer_address: "127.0.0.1:4242".to_string(),
            },
            signature: validator_signature.clone(),
        }),
    };
    gen.write_borsh(
        "model/consensus_staking_action_bond",
        "hyli_model::ConsensusStakingAction",
        "ConsensusStakingAction::Bond { candidate=SignedByValidator<ValidatorCandidacy> }",
        &staking_bond,
    );

    // The Box<...> on the Bond variant must be invisible on the wire — the
    // raw and the boxed encodings should be byte-identical. We assert that
    // here at fixture-generation time so a regression in borsh would fail
    // the build before any Zig test runs.
    {
        let raw_bytes = borsh::to_vec(&Signed::<ValidatorCandidacy, ValidatorSignature> {
            msg: ValidatorCandidacy {
                peer_address: "127.0.0.1:4242".to_string(),
            },
            signature: validator_signature.clone(),
        })
        .expect("borsh raw signed");
        let boxed_bytes = borsh::to_vec(&staking_bond).expect("borsh boxed bond");
        // boxed_bytes = 1-byte enum tag (0 for Bond) ‖ raw_bytes
        assert_eq!(boxed_bytes[0], 0u8, "Bond is variant index 0");
        assert_eq!(
            &boxed_bytes[1..],
            &raw_bytes[..],
            "Box<T> should be transparent over the wire"
        );
    }

    let staking_pay = ConsensusStakingAction::PayFeesForDaDi {
        lane_id: LaneId::default(),
        cumul_size: LaneBytesSize(4096),
    };
    gen.write_borsh(
        "model/consensus_staking_action_pay",
        "hyli_model::ConsensusStakingAction",
        "ConsensusStakingAction::PayFeesForDaDi { lane=default, cumul=4096 }",
        &staking_pay,
    );

    // LaneBytesSize standalone — handy for the BLS work later when
    // hashing the same value with `to_le_bytes`.
    gen.write_borsh(
        "model/lane_bytes_size_4096",
        "hyli_model::LaneBytesSize",
        "LaneBytesSize(4096)",
        &LaneBytesSize(4096),
    );

    // Empty ConsensusProposal: zero cut entries, zero staking actions, a
    // fixed timestamp/parent. This is the simplest possible hash input,
    // and the hash construction has to skip the empty cut/staking_actions
    // loops cleanly.
    let cp_empty = ConsensusProposal {
        slot: 1,
        parent_hash: ConsensusProposalHash(b"genesis".to_vec()),
        cut: vec![],
        staking_actions: vec![],
        timestamp: TimestampMs(1234),
    };
    gen.write_borsh(
        "model/consensus_proposal_empty",
        "hyli_model::ConsensusProposal",
        "ConsensusProposal { slot=1, cut=[], actions=[], ts=1234, parent=genesis }",
        &cp_empty,
    );
    gen.write_hash(
        "model/consensus_proposal_empty",
        "hyli_model::ConsensusProposal",
        "ConsensusProposal::hashed for the empty case",
        cp_empty.hashed().0,
    );

    // Populated ConsensusProposal: one cut entry and one PayFeesForDaDi
    // staking action. The cut entry uses a non-default LaneId so the test
    // pins the raw-bytes (NOT hex) update_hasher path. The
    // LaneBytesSize and AggregateSignature on the cut entry are *not*
    // fed into the hash, but they ARE part of the borsh wire format —
    // confirming this round-trips proves both halves of the
    // hash-vs-encode split.
    let cut_lane = LaneId::with_suffix(ValidatorPublicKey(vec![0x01; 4]), "lane-a");
    let cut_dp_hash = DataProposalHash(b"dp-hash".to_vec());
    let cut_size = LaneBytesSize(8192);
    let cut_agg = AggregateSignature {
        signature: Signature(vec![0xee; 12]),
        validators: vec![ValidatorPublicKey(vec![0x01; 4])],
    };
    let cp_full = ConsensusProposal {
        slot: 7,
        parent_hash: ConsensusProposalHash(b"prev-cp".to_vec()),
        cut: vec![(
            cut_lane.clone(),
            cut_dp_hash.clone(),
            cut_size,
            cut_agg.clone(),
        )],
        staking_actions: vec![ConsensusStakingAction::PayFeesForDaDi {
            lane_id: cut_lane.clone(),
            cumul_size: LaneBytesSize(8192),
        }],
        timestamp: TimestampMs(9999),
    };
    gen.write_borsh(
        "model/consensus_proposal_full",
        "hyli_model::ConsensusProposal",
        "ConsensusProposal with one cut entry and one PayFeesForDaDi",
        &cp_full,
    );
    gen.write_hash(
        "model/consensus_proposal_full",
        "hyli_model::ConsensusProposal",
        "ConsensusProposal::hashed for the populated case",
        cp_full.hashed().0,
    );

    // ---- T1: Replay-path types --------------------------------------------
    //
    // These are the consensus-critical types that drive the state-replay
    // pipeline once an observer turns into a follower. They get fixtures
    // before any Zig replay code lands so the byte and hash shapes are
    // pinned independently.

    // BlobsHashes is a thin wrapper around `BTreeMap<BlobIndex, BlobHash>`.
    // We pin two cases: the empty map (just a `0u32` length prefix) and a
    // 2-entry map. BTreeMap iteration order in Rust is sorted by key Ord,
    // so the entries always come out in BlobIndex(0) < BlobIndex(1) order.
    let mut empty_hashes_map: BTreeMap<BlobIndex, BlobHash> = BTreeMap::new();
    let blobs_hashes_empty = BlobsHashes {
        hashes: empty_hashes_map.clone(),
    };
    gen.write_borsh(
        "model/blobs_hashes_empty",
        "hyli_model::BlobsHashes",
        "BlobsHashes { hashes: {} }",
        &blobs_hashes_empty,
    );
    empty_hashes_map.insert(BlobIndex(0), BlobHash(vec![0xaa; 4]));
    empty_hashes_map.insert(BlobIndex(1), BlobHash(vec![0xbb; 4]));
    let blobs_hashes_two = BlobsHashes {
        hashes: empty_hashes_map,
    };
    let blobs_hashes_two_bytes = borsh::to_vec(&blobs_hashes_two).expect("borsh BlobsHashes");
    // Pin the exact wire layout: u32 length=2 ‖ key0 (u64) ‖ value0 (Vec<u8>)
    // ‖ key1 (u64) ‖ value1 (Vec<u8>). BTreeMap sorts keys ascending, so the
    // order is BlobIndex(0) before BlobIndex(1).
    let mut blobs_hashes_two_expected = Vec::new();
    blobs_hashes_two_expected.extend_from_slice(&2u32.to_le_bytes());
    blobs_hashes_two_expected.extend_from_slice(&0u64.to_le_bytes()); // BlobIndex(0)
    blobs_hashes_two_expected.extend_from_slice(&4u32.to_le_bytes()); // BlobHash len
    blobs_hashes_two_expected.extend_from_slice(&[0xaa; 4]);
    blobs_hashes_two_expected.extend_from_slice(&1u64.to_le_bytes()); // BlobIndex(1)
    blobs_hashes_two_expected.extend_from_slice(&4u32.to_le_bytes()); // BlobHash len
    blobs_hashes_two_expected.extend_from_slice(&[0xbb; 4]);
    assert_eq!(
        blobs_hashes_two_bytes, blobs_hashes_two_expected,
        "BlobsHashes wire layout drifted from u32-len + sorted key/value pairs",
    );
    gen.write_borsh(
        "model/blobs_hashes_two",
        "hyli_model::BlobsHashes",
        "BlobsHashes { 0 -> [0xaa;4], 1 -> [0xbb;4] }",
        &blobs_hashes_two,
    );

    // TxContext: small wrapper that Calldata and HyliOutput can carry
    // optionally. Verbose enough that pinning it standalone is worth the
    // extra fixture.
    // BlockHash is a type alias for ConsensusProposalHash, so the
    // constructor name on the wire side is `ConsensusProposalHash(...)`.
    let tx_ctx = TxContext {
        lane_id: LaneId::default(),
        block_hash: ConsensusProposalHash(vec![0x55; 4]),
        block_height: BlockHeight(123),
        timestamp: TimestampMs(456),
        chain_id: 7,
    };
    gen.write_borsh(
        "model/tx_context",
        "hyli_model::TxContext",
        "TxContext { lane=default, block=[0x55;4], height=123, ts=456, chain_id=7 }",
        &tx_ctx,
    );

    // Calldata: passed from the application to the contract. Borsh field
    // order is the canonical contract.rs declaration order.
    let calldata_blobs = IndexedBlobs(vec![(
        BlobIndex(0),
        Blob {
            contract_name: ContractName("counter".to_string()),
            data: BlobData(vec![0x10, 0x11]),
        },
    )]);
    let calldata = Calldata {
        tx_hash: TxHash(vec![0x77; 4]),
        identity: Identity("alice@counter".to_string()),
        blobs: calldata_blobs,
        tx_blob_count: 1,
        index: BlobIndex(0),
        tx_ctx: Some(tx_ctx.clone()),
        private_input: vec![0xfe, 0xed],
    };
    gen.write_borsh(
        "model/calldata",
        "hyli_model::Calldata",
        "Calldata for tx=alice@counter with one blob and tx_ctx=Some",
        &calldata,
    );

    // RegisterContractEffect: a stripped-down RegisterContractAction. Used
    // by OnchainEffect::RegisterContract* variants. Both the borsh layout
    // and the custom hash (verifier‖program_id‖state‖name‖opt timeout) get
    // pinned.
    let register_effect = RegisterContractEffect {
        verifier: Verifier("risc0".to_string()),
        program_id: ProgramId(vec![0xaa; 8]),
        state_commitment: StateCommitment(vec![0xbb; 8]),
        contract_name: ContractName("counter".to_string()),
        timeout_window: Some(TimeoutWindow::Timeout {
            hard_timeout: BlockHeight(50),
            soft_timeout: BlockHeight(100),
        }),
    };
    gen.write_borsh(
        "model/register_contract_effect",
        "hyli_model::RegisterContractEffect",
        "RegisterContractEffect for counter w/ Some(timeout)",
        &register_effect,
    );
    gen.write_hash(
        "model/register_contract_effect",
        "hyli_model::RegisterContractEffect",
        "RegisterContractEffect::hashed",
        register_effect.hashed().0,
    );

    // OnchainEffect: enum with five variants. We pin every variant so the
    // Zig side can validate both the borsh tag order and the per-variant
    // custom hash construction in `OnchainEffect::hashed`.
    let oe_register_with_ctor =
        OnchainEffect::RegisterContractWithConstructor(register_effect.clone());
    gen.write_borsh(
        "model/onchain_effect_register_with_ctor",
        "hyli_model::OnchainEffect",
        "OnchainEffect::RegisterContractWithConstructor(...)",
        &oe_register_with_ctor,
    );
    gen.write_hash(
        "model/onchain_effect_register_with_ctor",
        "hyli_model::OnchainEffect",
        "OnchainEffect::RegisterContractWithConstructor::hashed",
        oe_register_with_ctor.hashed().0,
    );
    let oe_register = OnchainEffect::RegisterContract(register_effect.clone());
    gen.write_borsh(
        "model/onchain_effect_register",
        "hyli_model::OnchainEffect",
        "OnchainEffect::RegisterContract(...)",
        &oe_register,
    );
    gen.write_hash(
        "model/onchain_effect_register",
        "hyli_model::OnchainEffect",
        "OnchainEffect::RegisterContract::hashed",
        oe_register.hashed().0,
    );
    let oe_delete = OnchainEffect::DeleteContract(ContractName("counter".to_string()));
    gen.write_borsh(
        "model/onchain_effect_delete",
        "hyli_model::OnchainEffect",
        "OnchainEffect::DeleteContract(\"counter\")",
        &oe_delete,
    );
    gen.write_hash(
        "model/onchain_effect_delete",
        "hyli_model::OnchainEffect",
        "OnchainEffect::DeleteContract::hashed",
        oe_delete.hashed().0,
    );
    let oe_update_pid = OnchainEffect::UpdateContractProgramId(
        ContractName("counter".to_string()),
        ProgramId(vec![0xcc; 4]),
    );
    gen.write_borsh(
        "model/onchain_effect_update_program_id",
        "hyli_model::OnchainEffect",
        "OnchainEffect::UpdateContractProgramId(\"counter\", [0xcc;4])",
        &oe_update_pid,
    );
    gen.write_hash(
        "model/onchain_effect_update_program_id",
        "hyli_model::OnchainEffect",
        "OnchainEffect::UpdateContractProgramId::hashed",
        oe_update_pid.hashed().0,
    );
    let oe_update_timeout_no = OnchainEffect::UpdateTimeoutWindow(
        ContractName("counter".to_string()),
        TimeoutWindow::NoTimeout,
    );
    gen.write_borsh(
        "model/onchain_effect_update_timeout_no",
        "hyli_model::OnchainEffect",
        "OnchainEffect::UpdateTimeoutWindow(\"counter\", NoTimeout)",
        &oe_update_timeout_no,
    );
    gen.write_hash(
        "model/onchain_effect_update_timeout_no",
        "hyli_model::OnchainEffect",
        "OnchainEffect::UpdateTimeoutWindow(NoTimeout)::hashed",
        oe_update_timeout_no.hashed().0,
    );
    let oe_update_timeout_yes = OnchainEffect::UpdateTimeoutWindow(
        ContractName("counter".to_string()),
        TimeoutWindow::Timeout {
            hard_timeout: BlockHeight(100),
            soft_timeout: BlockHeight(200),
        },
    );
    gen.write_borsh(
        "model/onchain_effect_update_timeout_yes",
        "hyli_model::OnchainEffect",
        "OnchainEffect::UpdateTimeoutWindow(\"counter\", Timeout{100,200})",
        &oe_update_timeout_yes,
    );
    gen.write_hash(
        "model/onchain_effect_update_timeout_yes",
        "hyli_model::OnchainEffect",
        "OnchainEffect::UpdateTimeoutWindow(Timeout)::hashed",
        oe_update_timeout_yes.hashed().0,
    );

    // HyliOutput: the zkVM-committed payload that drives state replay.
    // Field order matches contract.rs exactly. The custom hash construction
    // is pinned separately so the Zig side can implement it field-by-field
    // (it is NOT sha3_256(borsh(self))).
    let hyli_output = HyliOutput {
        version: 1,
        initial_state: StateCommitment(vec![0x10, 0x11, 0x12, 0x13]),
        next_state: StateCommitment(vec![0x20, 0x21, 0x22, 0x23]),
        identity: Identity("alice@counter".to_string()),
        index: BlobIndex(0),
        blobs: IndexedBlobs(vec![(
            BlobIndex(0),
            Blob {
                contract_name: ContractName("counter".to_string()),
                data: BlobData(vec![0x10, 0x11]),
            },
        )]),
        tx_blob_count: 1,
        tx_hash: TxHash(vec![0x77; 4]),
        success: true,
        state_reads: vec![(
            ContractName("counter".to_string()),
            StateCommitment(vec![0x10, 0x11, 0x12, 0x13]),
        )],
        tx_ctx: Some(tx_ctx.clone()),
        onchain_effects: vec![oe_register.clone()],
        program_outputs: vec![0xab, 0xcd],
    };
    gen.write_borsh(
        "model/hyli_output",
        "hyli_model::HyliOutput",
        "HyliOutput for counter with one blob, one register effect, success=true",
        &hyli_output,
    );
    gen.write_hash(
        "model/hyli_output",
        "hyli_model::HyliOutput",
        "HyliOutput::hashed (custom field-by-field SHA3-256 over the struct)",
        hyli_output.hashed().0,
    );

    // ---- Wire framing -----------------------------------------------------
    //
    // Hyli wraps every TCP message in a default tokio-util
    // `LengthDelimitedCodec` frame: a 4-byte BIG-ENDIAN length followed
    // by `len` bytes of payload. The payload itself is one of:
    //   - `b"PING"` literal (4 bytes), or
    //   - `borsh(TcpWireData)` where `TcpWireData = { headers, payload }`
    //
    // Note that `TcpMessage::Ping` is NOT borsh-encoded as an enum variant —
    // hyli sends the raw 4 bytes "PING" and the receiver detects them by
    // string match before attempting borsh deserialization. This is the
    // wire-level quirk that the Zig framing layer has to mirror exactly.
    //
    // Both the framed bytes (with the BE length prefix) and the inner
    // bytes (without it) are emitted as fixtures so the Zig side can test
    // each layer independently.

    // Mirror of `hyli_net::tcp::TcpWireData`. The Rust definition is
    // pub(crate), so we redeclare it here. If the upstream layout ever
    // changes, the test against the existing serialize_tcp_message Rust
    // assertions below will break loudly.
    #[derive(borsh::BorshSerialize)]
    struct TcpWireData {
        headers: Vec<(String, String)>,
        payload: Vec<u8>,
    }

    fn frame(payload: &[u8]) -> Vec<u8> {
        let len: u32 = payload.len().try_into().expect("frame fits in u32");
        let mut out = Vec::with_capacity(4 + payload.len());
        out.extend_from_slice(&len.to_be_bytes());
        out.extend_from_slice(payload);
        out
    }

    // Inner bytes — TcpMessage::Ping is the literal "PING".
    gen.write_bytes(
        "wire",
        "messages/tcp_message_ping_inner",
        "[u8; 4]",
        "TcpMessage::Ping inner bytes (b\"PING\")".to_string(),
        b"PING".to_vec(),
    );
    // Framed bytes — 4-byte BE length prefix (0x00000004) + b"PING".
    gen.write_bytes(
        "wire",
        "messages/tcp_message_ping_framed",
        "[u8]",
        "Framed TcpMessage::Ping (BE length + b\"PING\")".to_string(),
        frame(b"PING"),
    );

    // Inner bytes — TcpData with empty headers and a 3-byte payload.
    // This matches the existing hyli unit test (`test_serialize_tcp_message`)
    // which asserts the bytes are [0,0,0,0, 3,0,0,0, 1,2,3]:
    //   - 4 bytes: headers Vec length = 0 (LE u32)
    //   - 4 bytes: payload Vec length = 3 (LE u32)
    //   - 3 bytes: payload [1,2,3]
    let tcp_data_simple = TcpWireData {
        headers: vec![],
        payload: vec![1, 2, 3],
    };
    let tcp_data_simple_bytes = borsh::to_vec(&tcp_data_simple).expect("borsh tcp data simple");
    assert_eq!(
        tcp_data_simple_bytes,
        vec![0, 0, 0, 0, 3, 0, 0, 0, 1, 2, 3],
        "TcpWireData layout drifted from upstream hyli expectation",
    );
    gen.write_bytes(
        "wire",
        "messages/tcp_message_data_simple_inner",
        "TcpWireData",
        "TcpData{headers=[], payload=[1,2,3]} as borsh(TcpWireData)".to_string(),
        tcp_data_simple_bytes.clone(),
    );
    gen.write_bytes(
        "wire",
        "messages/tcp_message_data_simple_framed",
        "[u8]",
        "Framed TcpData{headers=[], payload=[1,2,3]}".to_string(),
        frame(&tcp_data_simple_bytes),
    );

    // Inner bytes — TcpData with one header and a 3-byte payload.
    let tcp_data_with_header = TcpWireData {
        headers: vec![("k".to_string(), "v".to_string())],
        payload: vec![0xaa, 0xbb],
    };
    let tcp_data_with_header_bytes =
        borsh::to_vec(&tcp_data_with_header).expect("borsh tcp data header");
    gen.write_bytes(
        "wire",
        "messages/tcp_message_data_header_inner",
        "TcpWireData",
        "TcpData{headers=[(k,v)], payload=[0xaa,0xbb]}".to_string(),
        tcp_data_with_header_bytes.clone(),
    );
    gen.write_bytes(
        "wire",
        "messages/tcp_message_data_header_framed",
        "[u8]",
        "Framed TcpData{headers=[(k,v)], payload=[0xaa,0xbb]}".to_string(),
        frame(&tcp_data_with_header_bytes),
    );

    // ---- Wire: P2P envelope and handshake ---------------------------------
    //
    // Mirrors of `hyli_net::tcp::{Canal, NodeConnectionData, Handshake,
    // P2PTcpMessage}`. We don't depend on `hyli-net` directly because pulling
    // it would drag tokio, sdk, and a dozen unrelated crates into the
    // fixture-gen build. The wire layout is the contract — these local
    // declarations exist only to feed the borsh serializer.
    //
    // If upstream ever changes a field, the corresponding Zig fixture test
    // breaks at the next regeneration, which is exactly the behavior the
    // executable spec is supposed to give us.

    #[derive(borsh::BorshSerialize)]
    struct CanalLocal(String);

    #[derive(borsh::BorshSerialize)]
    struct NodeConnectionDataLocal {
        version: u16,
        name: String,
        current_height: u64,
        p2p_public_address: String,
        da_public_address: String,
        start_timestamp: TimestampMs,
    }

    #[derive(borsh::BorshSerialize)]
    enum HandshakeLocal {
        Hello(
            (
                CanalLocal,
                Signed<NodeConnectionDataLocal, ValidatorSignature>,
                TimestampMs,
            ),
        ),
        #[allow(dead_code)]
        Verack(
            (
                CanalLocal,
                Signed<NodeConnectionDataLocal, ValidatorSignature>,
                TimestampMs,
            ),
        ),
    }

    #[derive(borsh::BorshSerialize)]
    enum P2PTcpMessageLocal {
        Handshake(HandshakeLocal),
        // The Data variant carries an arbitrary payload type on the Rust
        // side. We don't need a fixture for it here — the wire shape is
        // exactly `1u8 ‖ <inner>`, and the Zig side reuses the existing
        // model fixtures as the inner payload.
        #[allow(dead_code)]
        Data(Vec<u8>),
    }

    // Single Canal fixture so the Zig side can pin "the wire form is the
    // raw String encoding".
    let canal_p2p = CanalLocal("p2p".to_string());
    gen.write_borsh(
        "model/canal_p2p",
        "hyli_net::tcp::Canal",
        "Canal(\"p2p\") — newtype around String",
        &canal_p2p,
    );

    // NodeConnectionData representative payload. Versions, addresses, and
    // a deterministic timestamp.
    let node_data = NodeConnectionDataLocal {
        version: 1,
        name: "validator-a".to_string(),
        current_height: 42,
        p2p_public_address: "127.0.0.1:4242".to_string(),
        da_public_address: "127.0.0.1:4243".to_string(),
        start_timestamp: TimestampMs(1_700_000_000_000),
    };
    gen.write_borsh(
        "model/node_connection_data",
        "hyli_net::tcp::NodeConnectionData",
        "NodeConnectionData for validator-a, height=42",
        &node_data,
    );

    // Sign-by-validator wrapper around NodeConnectionData. The signature
    // bytes are deliberately deterministic placeholders — BLS12-381 is
    // landing in zolt-arith later, and the wire layout is independent of
    // whether the bytes are a real signature.
    let signed_node_data = Signed::<NodeConnectionDataLocal, ValidatorSignature> {
        msg: NodeConnectionDataLocal {
            version: 1,
            name: "validator-a".to_string(),
            current_height: 42,
            p2p_public_address: "127.0.0.1:4242".to_string(),
            da_public_address: "127.0.0.1:4243".to_string(),
            start_timestamp: TimestampMs(1_700_000_000_000),
        },
        signature: ValidatorSignature {
            signature: Signature(vec![0xff; 8]),
            validator: ValidatorPublicKey(vec![0x01; 4]),
        },
    };
    gen.write_borsh(
        "model/signed_node_connection_data",
        "Signed<NodeConnectionData, ValidatorSignature>",
        "SignedByValidator<NodeConnectionData>",
        &signed_node_data,
    );

    // Handshake::Hello with the same payload, encoded as the inner-borsh
    // bytes (no length prefix). This is what the Hyli observer needs to
    // produce on first contact.
    let handshake_hello = HandshakeLocal::Hello((
        CanalLocal("p2p".to_string()),
        Signed::<NodeConnectionDataLocal, ValidatorSignature> {
            msg: NodeConnectionDataLocal {
                version: 1,
                name: "validator-a".to_string(),
                current_height: 42,
                p2p_public_address: "127.0.0.1:4242".to_string(),
                da_public_address: "127.0.0.1:4243".to_string(),
                start_timestamp: TimestampMs(1_700_000_000_000),
            },
            signature: ValidatorSignature {
                signature: Signature(vec![0xff; 8]),
                validator: ValidatorPublicKey(vec![0x01; 4]),
            },
        },
        TimestampMs(1_700_000_000_001),
    ));
    let handshake_hello_bytes = borsh::to_vec(&handshake_hello).expect("borsh handshake hello");
    // Pin the variant tag as 0u8 — Hello is the first declared variant.
    assert_eq!(handshake_hello_bytes[0], 0u8, "Hello should be variant tag 0");
    gen.write_bytes(
        "wire",
        "messages/handshake_hello_inner",
        "hyli_net::tcp::Handshake",
        "Handshake::Hello((Canal=\"p2p\", SignedByValidator<NodeConnectionData>, ts))".to_string(),
        handshake_hello_bytes.clone(),
    );

    // Verack with the same payload as Hello — same shape but tag=1.
    let handshake_verack = HandshakeLocal::Verack((
        CanalLocal("p2p".to_string()),
        Signed::<NodeConnectionDataLocal, ValidatorSignature> {
            msg: NodeConnectionDataLocal {
                version: 1,
                name: "validator-a".to_string(),
                current_height: 42,
                p2p_public_address: "127.0.0.1:4242".to_string(),
                da_public_address: "127.0.0.1:4243".to_string(),
                start_timestamp: TimestampMs(1_700_000_000_000),
            },
            signature: ValidatorSignature {
                signature: Signature(vec![0xff; 8]),
                validator: ValidatorPublicKey(vec![0x01; 4]),
            },
        },
        TimestampMs(1_700_000_000_002),
    ));
    let handshake_verack_bytes = borsh::to_vec(&handshake_verack).expect("borsh handshake verack");
    assert_eq!(
        handshake_verack_bytes[0], 1u8,
        "Verack should be variant tag 1"
    );
    gen.write_bytes(
        "wire",
        "messages/handshake_verack_inner",
        "hyli_net::tcp::Handshake",
        "Handshake::Verack((Canal=\"p2p\", SignedByValidator<NodeConnectionData>, ts))"
            .to_string(),
        handshake_verack_bytes,
    );

    // P2PTcpMessage::Handshake(Hello(...)) — the outer envelope. The wire
    // layout is `0u8 ‖ <handshake_hello_bytes>` because Handshake is the
    // first declared variant of P2PTcpMessage.
    let p2p_handshake_hello = P2PTcpMessageLocal::Handshake(HandshakeLocal::Hello((
        CanalLocal("p2p".to_string()),
        Signed::<NodeConnectionDataLocal, ValidatorSignature> {
            msg: NodeConnectionDataLocal {
                version: 1,
                name: "validator-a".to_string(),
                current_height: 42,
                p2p_public_address: "127.0.0.1:4242".to_string(),
                da_public_address: "127.0.0.1:4243".to_string(),
                start_timestamp: TimestampMs(1_700_000_000_000),
            },
            signature: ValidatorSignature {
                signature: Signature(vec![0xff; 8]),
                validator: ValidatorPublicKey(vec![0x01; 4]),
            },
        },
        TimestampMs(1_700_000_000_001),
    )));
    let p2p_handshake_hello_bytes =
        borsh::to_vec(&p2p_handshake_hello).expect("borsh p2p handshake hello");
    // Outer tag (Handshake) ‖ inner Handshake bytes.
    assert_eq!(p2p_handshake_hello_bytes[0], 0u8, "Handshake variant tag");
    assert_eq!(
        &p2p_handshake_hello_bytes[1..],
        &handshake_hello_bytes[..],
        "P2PTcpMessage::Handshake should be a transparent wrapper",
    );
    gen.write_bytes(
        "wire",
        "messages/p2p_message_handshake_hello_inner",
        "hyli_net::tcp::P2PTcpMessage<_>",
        "P2PTcpMessage::Handshake(Handshake::Hello((Canal, signed, ts)))".to_string(),
        p2p_handshake_hello_bytes.clone(),
    );
    gen.write_bytes(
        "wire",
        "messages/p2p_message_handshake_hello_framed",
        "[u8]",
        "Framed P2PTcpMessage::Handshake(Hello(...))".to_string(),
        frame(&p2p_handshake_hello_bytes),
    );

    // P2PTcpMessage::Data — the payload here is `[0xaa, 0xbb, 0xcc]` so the
    // expected wire form is `1u8 ‖ borsh(Vec<u8>([0xaa,0xbb,0xcc]))` =
    // `01 03 00 00 00 aa bb cc`. Pinning the simplest possible Data variant
    // is enough; the inner type is generic in Hyli and gets exercised by
    // higher-level message fixtures.
    let p2p_data = P2PTcpMessageLocal::Data(vec![0xaa, 0xbb, 0xcc]);
    let p2p_data_bytes = borsh::to_vec(&p2p_data).expect("borsh p2p data");
    assert_eq!(
        p2p_data_bytes,
        vec![1, 3, 0, 0, 0, 0xaa, 0xbb, 0xcc],
        "P2PTcpMessage::Data wire layout drifted",
    );
    gen.write_bytes(
        "wire",
        "messages/p2p_message_data_inner",
        "hyli_net::tcp::P2PTcpMessage<Vec<u8>>",
        "P2PTcpMessage::Data(Vec<u8>([0xaa,0xbb,0xcc]))".to_string(),
        p2p_data_bytes,
    );

    // ---- Consensus network messages ---------------------------------------
    //
    // Mirrors of the per-step Borsh shapes from
    // `hyli/src/consensus/network.rs`. The consensus crate is a binary, not
    // a library, so we redeclare the types locally — same approach as the
    // wire/handshake mirrors. The wire layout is the contract; if upstream
    // ever changes a field, the next regeneration breaks the matching Zig
    // tests loudly.
    //
    // Marker types in upstream Hyli use a custom Borsh derive that emits
    // them through a shared `ConsensusMarkerSerde` enum so the four single-
    // byte tags (PrepareVote=0, ConfirmAck=1, ConsensusTimeout=2,
    // NilConsensusTimeout=3) are guaranteed distinct on the wire. We
    // reproduce that with explicit `u8` constants and pin every byte.

    type ConsensusProposalHashLocal = ConsensusProposalHash;
    type SlotLocal = u64;
    type ViewLocal = u64;

    // ConsensusMarkerSerde declared explicitly so the byte values are
    // pinned. Upstream uses #[derive(BorshSerialize)] on a 4-variant enum,
    // which Borsh emits as a `u8` discriminant in declaration order.
    #[derive(borsh::BorshSerialize, Clone)]
    enum ConsensusMarkerSerdeLocal {
        PrepareVote,
        ConfirmAck,
        ConsensusTimeout,
        NilConsensusTimeout,
    }

    let prepare_vote_marker_bytes =
        borsh::to_vec(&ConsensusMarkerSerdeLocal::PrepareVote).expect("borsh PrepareVote marker");
    let confirm_ack_marker_bytes =
        borsh::to_vec(&ConsensusMarkerSerdeLocal::ConfirmAck).expect("borsh ConfirmAck marker");
    let consensus_timeout_marker_bytes = borsh::to_vec(&ConsensusMarkerSerdeLocal::ConsensusTimeout)
        .expect("borsh ConsensusTimeout marker");
    let nil_consensus_timeout_marker_bytes =
        borsh::to_vec(&ConsensusMarkerSerdeLocal::NilConsensusTimeout)
            .expect("borsh NilConsensusTimeout marker");

    // The upstream `marker_serialization_bytes_are_unique_and_expected`
    // test asserts these exact bytes — we reuse them as the contract.
    assert_eq!(prepare_vote_marker_bytes, vec![0u8]);
    assert_eq!(confirm_ack_marker_bytes, vec![1u8]);
    assert_eq!(consensus_timeout_marker_bytes, vec![2u8]);
    assert_eq!(nil_consensus_timeout_marker_bytes, vec![3u8]);

    gen.write_bytes(
        "borsh",
        "consensus/marker_prepare_vote",
        "PrepareVoteMarker",
        "PrepareVoteMarker (single byte 0)".to_string(),
        prepare_vote_marker_bytes,
    );
    gen.write_bytes(
        "borsh",
        "consensus/marker_confirm_ack",
        "ConfirmAckMarker",
        "ConfirmAckMarker (single byte 1)".to_string(),
        confirm_ack_marker_bytes,
    );
    gen.write_bytes(
        "borsh",
        "consensus/marker_consensus_timeout",
        "ConsensusTimeoutMarker",
        "ConsensusTimeoutMarker (single byte 2)".to_string(),
        consensus_timeout_marker_bytes,
    );
    gen.write_bytes(
        "borsh",
        "consensus/marker_nil_consensus_timeout",
        "NilConsensusTimeoutMarker",
        "NilConsensusTimeoutMarker (single byte 3)".to_string(),
        nil_consensus_timeout_marker_bytes,
    );

    // QuorumCertificate<T> is a tuple struct (AggregateSignature, T). The
    // marker `T` is one of the four marker bytes above, so the wire form
    // is `borsh(AggregateSignature) ‖ marker_byte`.
    #[derive(borsh::BorshSerialize)]
    struct QuorumCertificateLocal<T: borsh::BorshSerialize>(AggregateSignature, T);

    let qc_agg = AggregateSignature {
        signature: Signature(vec![0xee; 12]),
        validators: vec![
            ValidatorPublicKey(vec![0x01; 4]),
            ValidatorPublicKey(vec![0x02; 4]),
        ],
    };
    let prepare_qc =
        QuorumCertificateLocal(qc_agg.clone(), ConsensusMarkerSerdeLocal::PrepareVote);
    gen.write_borsh(
        "consensus/prepare_qc",
        "consensus::PrepareQC",
        "PrepareQC = QuorumCertificate<PrepareVoteMarker>",
        &prepare_qc,
    );
    let commit_qc = QuorumCertificateLocal(qc_agg.clone(), ConsensusMarkerSerdeLocal::ConfirmAck);
    gen.write_borsh(
        "consensus/commit_qc",
        "consensus::CommitQC",
        "CommitQC = QuorumCertificate<ConfirmAckMarker>",
        &commit_qc,
    );
    let timeout_qc =
        QuorumCertificateLocal(qc_agg.clone(), ConsensusMarkerSerdeLocal::ConsensusTimeout);
    gen.write_borsh(
        "consensus/timeout_qc",
        "consensus::TimeoutQC",
        "TimeoutQC = QuorumCertificate<ConsensusTimeoutMarker>",
        &timeout_qc,
    );
    let nil_qc = QuorumCertificateLocal(
        qc_agg.clone(),
        ConsensusMarkerSerdeLocal::NilConsensusTimeout,
    );
    gen.write_borsh(
        "consensus/nil_qc",
        "consensus::NilQC",
        "NilQC = QuorumCertificate<NilConsensusTimeoutMarker>",
        &nil_qc,
    );

    // Pin the QC mismatch invariant: the four QC types differ ONLY in the
    // trailing marker byte, so a CommitQC must be byte-distinct from a
    // PrepareQC over the same AggregateSignature. Mirrors the upstream
    // `quorum_certificate_cannot_be_reused_across_steps` test.
    let prepare_qc_bytes = borsh::to_vec(&prepare_qc).expect("borsh prepare qc");
    let commit_qc_bytes = borsh::to_vec(&commit_qc).expect("borsh commit qc");
    assert_ne!(
        prepare_qc_bytes, commit_qc_bytes,
        "PrepareQC and CommitQC must be byte-distinct (marker tag differs)",
    );
    assert_eq!(
        &prepare_qc_bytes[..prepare_qc_bytes.len() - 1],
        &commit_qc_bytes[..commit_qc_bytes.len() - 1],
        "Prepare/Commit QC payload bytes must agree except in the trailing marker byte",
    );

    // PrepareVote = SignedByValidator<(ConsensusProposalHash, PrepareVoteMarker)>.
    // The tuple `(ConsensusProposalHash, PrepareVoteMarker)` encodes
    // positionally with no envelope, so the wire is:
    //   borsh(ConsensusProposalHash) ‖ marker_byte ‖ borsh(ValidatorSignature)
    //
    // Note: the upstream type uses an unnamed 2-tuple as the inner Signed
    // payload — we redeclare it explicitly so the local mirror is
    // unambiguous.
    let cph_demo = ConsensusProposalHash(b"cp-1".to_vec());
    let validator_sig_demo = ValidatorSignature {
        signature: Signature(vec![0xff; 8]),
        validator: ValidatorPublicKey(vec![0x01; 4]),
    };
    let prepare_vote_payload = (
        cph_demo.clone(),
        ConsensusMarkerSerdeLocal::PrepareVote,
    );
    let prepare_vote = Signed::<
        (ConsensusProposalHashLocal, ConsensusMarkerSerdeLocal),
        ValidatorSignature,
    > {
        msg: prepare_vote_payload,
        signature: validator_sig_demo.clone(),
    };
    gen.write_borsh(
        "consensus/prepare_vote",
        "consensus::PrepareVote",
        "SignedByValidator<(ConsensusProposalHash, PrepareVoteMarker)>",
        &prepare_vote,
    );

    let confirm_ack_payload = (cph_demo.clone(), ConsensusMarkerSerdeLocal::ConfirmAck);
    let confirm_ack = Signed::<
        (ConsensusProposalHashLocal, ConsensusMarkerSerdeLocal),
        ValidatorSignature,
    > {
        msg: confirm_ack_payload,
        signature: validator_sig_demo.clone(),
    };
    gen.write_borsh(
        "consensus/confirm_ack",
        "consensus::ConfirmAck",
        "SignedByValidator<(ConsensusProposalHash, ConfirmAckMarker)>",
        &confirm_ack,
    );

    // Ticket enum: Genesis, CommitQC(CommitQC), TimeoutQC(TimeoutQC, TCKind),
    // ForcedCommitQC(View).
    #[derive(borsh::BorshSerialize)]
    enum TicketLocal {
        Genesis,
        CommitQC(QuorumCertificateLocal<ConsensusMarkerSerdeLocal>),
        #[allow(dead_code)]
        TimeoutQC(QuorumCertificateLocal<ConsensusMarkerSerdeLocal>, TCKindLocal),
        #[allow(dead_code)]
        ForcedCommitQC(ViewLocal),
    }

    #[derive(borsh::BorshSerialize)]
    enum TCKindLocal {
        #[allow(dead_code)]
        NilProposal(QuorumCertificateLocal<ConsensusMarkerSerdeLocal>),
        #[allow(dead_code)]
        PrepareQC((QuorumCertificateLocal<ConsensusMarkerSerdeLocal>, ConsensusProposal)),
    }

    gen.write_borsh(
        "consensus/ticket_genesis",
        "consensus::Ticket",
        "Ticket::Genesis (single byte tag)",
        &TicketLocal::Genesis,
    );
    let ticket_commit = TicketLocal::CommitQC(QuorumCertificateLocal(
        qc_agg.clone(),
        ConsensusMarkerSerdeLocal::ConfirmAck,
    ));
    gen.write_borsh(
        "consensus/ticket_commit_qc",
        "consensus::Ticket",
        "Ticket::CommitQC(commit_qc)",
        &ticket_commit,
    );

    // ConsensusNetMessage enum. We pin the simpler variants here:
    // SyncRequest, ValidatorCandidacy, PrepareVote, ConfirmAck. The more
    // complex `Prepare`, `Confirm`, `Commit`, `Timeout`, and
    // `TimeoutCertificate` variants get separate fixtures below.
    #[derive(borsh::BorshSerialize)]
    enum ConsensusNetMessageLocal {
        Prepare(ConsensusProposal, TicketLocal, ViewLocal),
        PrepareVote(
            Signed<
                (ConsensusProposalHashLocal, ConsensusMarkerSerdeLocal),
                ValidatorSignature,
            >,
        ),
        Confirm(
            QuorumCertificateLocal<ConsensusMarkerSerdeLocal>,
            ConsensusProposalHashLocal,
        ),
        ConfirmAck(
            Signed<
                (ConsensusProposalHashLocal, ConsensusMarkerSerdeLocal),
                ValidatorSignature,
            >,
        ),
        Commit(
            QuorumCertificateLocal<ConsensusMarkerSerdeLocal>,
            ConsensusProposalHashLocal,
        ),
        #[allow(dead_code)]
        Timeout(()),
        #[allow(dead_code)]
        TimeoutCertificate(
            QuorumCertificateLocal<ConsensusMarkerSerdeLocal>,
            TCKindLocal,
            SlotLocal,
            ViewLocal,
        ),
        ValidatorCandidacy(Signed<ValidatorCandidacy, ValidatorSignature>),
        SyncRequest(ConsensusProposalHashLocal),
        SyncReply(
            (
                ValidatorPublicKey,
                ConsensusProposal,
                TicketLocal,
                ViewLocal,
            ),
        ),
    }

    // Variant 0: Prepare(ConsensusProposal, Ticket, View). We reuse the
    // populated cp_full and the Genesis ticket so the byte content is
    // deterministic.
    let prepare_msg = ConsensusNetMessageLocal::Prepare(cp_full.clone(), TicketLocal::Genesis, 7);
    gen.write_borsh(
        "consensus/net_message_prepare",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::Prepare(cp_full, Ticket::Genesis, view=7)",
        &prepare_msg,
    );

    // Variant 1: PrepareVote(SignedByValidator<(cph, marker)>)
    let prepare_vote_msg = ConsensusNetMessageLocal::PrepareVote(Signed::<
        (ConsensusProposalHashLocal, ConsensusMarkerSerdeLocal),
        ValidatorSignature,
    > {
        msg: (cph_demo.clone(), ConsensusMarkerSerdeLocal::PrepareVote),
        signature: validator_sig_demo.clone(),
    });
    gen.write_borsh(
        "consensus/net_message_prepare_vote",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::PrepareVote(prepare_vote)",
        &prepare_vote_msg,
    );

    // Variant 2: Confirm(PrepareQC, ConsensusProposalHash)
    let confirm_msg = ConsensusNetMessageLocal::Confirm(
        QuorumCertificateLocal(qc_agg.clone(), ConsensusMarkerSerdeLocal::PrepareVote),
        cph_demo.clone(),
    );
    gen.write_borsh(
        "consensus/net_message_confirm",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::Confirm(prepare_qc, cph)",
        &confirm_msg,
    );

    // Variant 3: ConfirmAck(SignedByValidator<(cph, marker)>)
    let confirm_ack_msg = ConsensusNetMessageLocal::ConfirmAck(Signed::<
        (ConsensusProposalHashLocal, ConsensusMarkerSerdeLocal),
        ValidatorSignature,
    > {
        msg: (cph_demo.clone(), ConsensusMarkerSerdeLocal::ConfirmAck),
        signature: validator_sig_demo.clone(),
    });
    gen.write_borsh(
        "consensus/net_message_confirm_ack",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::ConfirmAck(confirm_ack)",
        &confirm_ack_msg,
    );

    // Variant 4: Commit(CommitQC, ConsensusProposalHash)
    let commit_msg = ConsensusNetMessageLocal::Commit(
        QuorumCertificateLocal(qc_agg.clone(), ConsensusMarkerSerdeLocal::ConfirmAck),
        cph_demo.clone(),
    );
    gen.write_borsh(
        "consensus/net_message_commit",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::Commit(commit_qc, cph)",
        &commit_msg,
    );

    // Variant 7: ValidatorCandidacy(SignedByValidator<ValidatorCandidacy>)
    let candidacy_msg = ConsensusNetMessageLocal::ValidatorCandidacy(signed_candidacy.clone());
    gen.write_borsh(
        "consensus/net_message_validator_candidacy",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::ValidatorCandidacy(signed_candidacy)",
        &candidacy_msg,
    );

    // Variant 8: SyncRequest(ConsensusProposalHash)
    let sync_request_msg = ConsensusNetMessageLocal::SyncRequest(cph_demo.clone());
    gen.write_borsh(
        "consensus/net_message_sync_request",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::SyncRequest(cph)",
        &sync_request_msg,
    );

    // Variant 9: SyncReply((ValidatorPublicKey, ConsensusProposal, Ticket, View))
    let sync_reply_msg = ConsensusNetMessageLocal::SyncReply((
        ValidatorPublicKey(vec![0x03; 4]),
        cp_empty.clone(),
        TicketLocal::Genesis,
        12,
    ));
    gen.write_borsh(
        "consensus/net_message_sync_reply",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::SyncReply((sender, cp_empty, Genesis, view=12))",
        &sync_reply_msg,
    );

    // ---- Consensus: Timeout / TimeoutCertificate --------------------------
    //
    // ConsensusTimeout = (
    //     SignedByValidator<(Slot, View, ConsensusProposalHash, ConsensusTimeoutMarker)>,
    //     TimeoutKind,
    // )
    //
    // TimeoutKind = NilProposal(SignedByValidator<(Slot, View, cph, NilConsensusTimeoutMarker)>)
    //             | PrepareQC((PrepareQC, ConsensusProposal))
    //
    // We pin both TimeoutKind variants and the two ConsensusNetMessage
    // variants that wrap them so the follower can validate the bytes
    // before any signature verification lands.

    // The signed (slot, view, cph, marker) inner payloads — declared
    // explicitly because Borsh encodes a 4-tuple positionally and we
    // want the field order pinned in source.
    type SlotViewCphMarker = (
        SlotLocal,
        ViewLocal,
        ConsensusProposalHashLocal,
        ConsensusMarkerSerdeLocal,
    );

    // Timeout::NilProposal payload — same signed envelope but with the
    // NilConsensusTimeout marker tag instead of ConsensusTimeout.
    let nil_proposal_signed_payload: SlotViewCphMarker = (
        7,
        2,
        cph_demo.clone(),
        ConsensusMarkerSerdeLocal::NilConsensusTimeout,
    );
    let nil_proposal_signed = Signed::<SlotViewCphMarker, ValidatorSignature> {
        msg: nil_proposal_signed_payload,
        signature: validator_sig_demo.clone(),
    };

    #[derive(borsh::BorshSerialize)]
    enum TimeoutKindLocal {
        NilProposal(Signed<SlotViewCphMarker, ValidatorSignature>),
        #[allow(dead_code)]
        PrepareQC((QuorumCertificateLocal<ConsensusMarkerSerdeLocal>, ConsensusProposal)),
    }

    let timeout_kind_nil = TimeoutKindLocal::NilProposal(nil_proposal_signed.clone());
    gen.write_borsh(
        "consensus/timeout_kind_nil_proposal",
        "consensus::TimeoutKind",
        "TimeoutKind::NilProposal(SignedByValidator<(slot,view,cph,NilMarker)>)",
        &timeout_kind_nil,
    );
    let timeout_kind_prepare_qc = TimeoutKindLocal::PrepareQC((
        QuorumCertificateLocal(qc_agg.clone(), ConsensusMarkerSerdeLocal::PrepareVote),
        cp_full.clone(),
    ));
    gen.write_borsh(
        "consensus/timeout_kind_prepare_qc",
        "consensus::TimeoutKind",
        "TimeoutKind::PrepareQC((PrepareQC, cp_full))",
        &timeout_kind_prepare_qc,
    );

    // ConsensusTimeout outer payload — note the outer signed message uses
    // the ConsensusTimeout marker tag (not Nil) regardless of the
    // TimeoutKind underneath.
    let consensus_timeout_outer_payload: SlotViewCphMarker = (
        7,
        2,
        cph_demo.clone(),
        ConsensusMarkerSerdeLocal::ConsensusTimeout,
    );
    let consensus_timeout_outer = Signed::<SlotViewCphMarker, ValidatorSignature> {
        msg: consensus_timeout_outer_payload,
        signature: validator_sig_demo.clone(),
    };
    let consensus_timeout_value = (consensus_timeout_outer, timeout_kind_nil);
    gen.write_borsh(
        "consensus/consensus_timeout",
        "consensus::ConsensusTimeout",
        "ConsensusTimeout = (signed_outer, TimeoutKind::NilProposal(...))",
        &consensus_timeout_value,
    );

    // ConsensusNetMessage::Timeout(ConsensusTimeout). The Timeout variant
    // is index 5 in the upstream enum, sandwiched between Commit (4) and
    // TimeoutCertificate (6). We re-emit it now that the placeholder is
    // gone.
    #[derive(borsh::BorshSerialize)]
    enum ConsensusNetMessageWithTimeout {
        #[allow(dead_code)]
        Prepare(ConsensusProposal, TicketLocal, ViewLocal),
        #[allow(dead_code)]
        PrepareVote(
            Signed<
                (ConsensusProposalHashLocal, ConsensusMarkerSerdeLocal),
                ValidatorSignature,
            >,
        ),
        #[allow(dead_code)]
        Confirm(
            QuorumCertificateLocal<ConsensusMarkerSerdeLocal>,
            ConsensusProposalHashLocal,
        ),
        #[allow(dead_code)]
        ConfirmAck(
            Signed<
                (ConsensusProposalHashLocal, ConsensusMarkerSerdeLocal),
                ValidatorSignature,
            >,
        ),
        #[allow(dead_code)]
        Commit(
            QuorumCertificateLocal<ConsensusMarkerSerdeLocal>,
            ConsensusProposalHashLocal,
        ),
        Timeout((Signed<SlotViewCphMarker, ValidatorSignature>, TimeoutKindLocal)),
        TimeoutCertificate(
            QuorumCertificateLocal<ConsensusMarkerSerdeLocal>,
            TCKindLocal,
            SlotLocal,
            ViewLocal,
        ),
        #[allow(dead_code)]
        ValidatorCandidacy(Signed<ValidatorCandidacy, ValidatorSignature>),
        #[allow(dead_code)]
        SyncRequest(ConsensusProposalHashLocal),
        #[allow(dead_code)]
        SyncReply(
            (
                ValidatorPublicKey,
                ConsensusProposal,
                TicketLocal,
                ViewLocal,
            ),
        ),
    }

    let timeout_outer_payload_again: SlotViewCphMarker = (
        7,
        2,
        cph_demo.clone(),
        ConsensusMarkerSerdeLocal::ConsensusTimeout,
    );
    let timeout_outer_again = Signed::<SlotViewCphMarker, ValidatorSignature> {
        msg: timeout_outer_payload_again,
        signature: validator_sig_demo.clone(),
    };
    let timeout_kind_nil_again = TimeoutKindLocal::NilProposal(nil_proposal_signed.clone());
    let net_msg_timeout = ConsensusNetMessageWithTimeout::Timeout((
        timeout_outer_again,
        timeout_kind_nil_again,
    ));
    gen.write_borsh(
        "consensus/net_message_timeout",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::Timeout((signed_outer, NilProposal(...)))",
        &net_msg_timeout,
    );

    // TimeoutCertificate(TimeoutQC, TCKind, Slot, View). TCKind is the
    // sibling enum of TimeoutKind for the certificate path:
    //   NilProposal(NilQC) | PrepareQC((PrepareQC, ConsensusProposal))
    let tc_kind_nil = TCKindLocal::NilProposal(QuorumCertificateLocal(
        qc_agg.clone(),
        ConsensusMarkerSerdeLocal::NilConsensusTimeout,
    ));
    gen.write_borsh(
        "consensus/tc_kind_nil_proposal",
        "consensus::TCKind",
        "TCKind::NilProposal(NilQC)",
        &tc_kind_nil,
    );
    let tc_kind_prepare_qc = TCKindLocal::PrepareQC((
        QuorumCertificateLocal(qc_agg.clone(), ConsensusMarkerSerdeLocal::PrepareVote),
        cp_full.clone(),
    ));
    gen.write_borsh(
        "consensus/tc_kind_prepare_qc",
        "consensus::TCKind",
        "TCKind::PrepareQC((PrepareQC, cp_full))",
        &tc_kind_prepare_qc,
    );

    let net_msg_timeout_certificate = ConsensusNetMessageWithTimeout::TimeoutCertificate(
        QuorumCertificateLocal(qc_agg.clone(), ConsensusMarkerSerdeLocal::ConsensusTimeout),
        TCKindLocal::NilProposal(QuorumCertificateLocal(
            qc_agg.clone(),
            ConsensusMarkerSerdeLocal::NilConsensusTimeout,
        )),
        7,
        2,
    );
    gen.write_borsh(
        "consensus/net_message_timeout_certificate",
        "consensus::ConsensusNetMessage",
        "ConsensusNetMessage::TimeoutCertificate(TimeoutQC, TCKind::NilProposal(NilQC), 7, 2)",
        &net_msg_timeout_certificate,
    );

    // ---- Mempool network messages -----------------------------------------
    //
    // Mirror of `enum MempoolNetMessage` from `hyli/src/mempool.rs`:
    //
    //   DataProposal(LaneId, DataProposalHash, DataProposal, ValidatorDAG),
    //   DataVote(LaneId, ValidatorDAG),
    //   SyncRequest(LaneId, Option<DataProposalHash>, Option<DataProposalHash>),
    //   SyncReply(LaneId, Vec<ValidatorDAG>, DataProposal),
    //
    // ValidatorDAG = SignedByValidator<(DataProposalHash, LaneBytesSize)>.

    // ValidatorDAG inner payload type. The 2-tuple has no envelope on
    // the wire — declared explicitly here for clarity.
    type ValidatorDagInner = (DataProposalHash, LaneBytesSize);
    type ValidatorDagLocal = Signed<ValidatorDagInner, ValidatorSignature>;

    let dp_demo_hash = DataProposalHash(b"dp-1".to_vec());
    let validator_dag_demo: ValidatorDagLocal = Signed::<ValidatorDagInner, ValidatorSignature> {
        msg: (dp_demo_hash.clone(), LaneBytesSize(1024)),
        signature: validator_sig_demo.clone(),
    };
    gen.write_borsh(
        "mempool/validator_dag",
        "mempool::ValidatorDAG",
        "ValidatorDAG = SignedByValidator<(DataProposalHash, LaneBytesSize)>",
        &validator_dag_demo,
    );

    let lane_demo = LaneId::with_suffix(ValidatorPublicKey(vec![0x01; 4]), "lane-a");
    let dp_demo = DataProposal::new(DataProposalHash(b"parent".to_vec()), vec![]);

    #[derive(borsh::BorshSerialize)]
    enum MempoolNetMessageLocal {
        DataProposal(LaneId, DataProposalHash, DataProposal, ValidatorDagLocal),
        DataVote(LaneId, ValidatorDagLocal),
        SyncRequest(LaneId, Option<DataProposalHash>, Option<DataProposalHash>),
        SyncReply(LaneId, Vec<ValidatorDagLocal>, DataProposal),
    }

    let mp_data_proposal = MempoolNetMessageLocal::DataProposal(
        lane_demo.clone(),
        dp_demo_hash.clone(),
        dp_demo.clone(),
        validator_dag_demo.clone(),
    );
    gen.write_borsh(
        "mempool/net_message_data_proposal",
        "mempool::MempoolNetMessage",
        "MempoolNetMessage::DataProposal(lane, dp_hash, dp_empty, ValidatorDAG)",
        &mp_data_proposal,
    );

    let mp_data_vote = MempoolNetMessageLocal::DataVote(lane_demo.clone(), validator_dag_demo.clone());
    gen.write_borsh(
        "mempool/net_message_data_vote",
        "mempool::MempoolNetMessage",
        "MempoolNetMessage::DataVote(lane, ValidatorDAG)",
        &mp_data_vote,
    );

    // SyncRequest with both bounds present (closed range).
    let mp_sync_request = MempoolNetMessageLocal::SyncRequest(
        lane_demo.clone(),
        Some(DataProposalHash(b"from".to_vec())),
        Some(DataProposalHash(b"to".to_vec())),
    );
    gen.write_borsh(
        "mempool/net_message_sync_request",
        "mempool::MempoolNetMessage",
        "MempoolNetMessage::SyncRequest(lane, Some(\"from\"), Some(\"to\"))",
        &mp_sync_request,
    );

    // SyncRequest with both bounds None (full sync).
    let mp_sync_request_none = MempoolNetMessageLocal::SyncRequest(lane_demo.clone(), None, None);
    gen.write_borsh(
        "mempool/net_message_sync_request_none",
        "mempool::MempoolNetMessage",
        "MempoolNetMessage::SyncRequest(lane, None, None) — full sync",
        &mp_sync_request_none,
    );

    let mp_sync_reply = MempoolNetMessageLocal::SyncReply(
        lane_demo.clone(),
        vec![validator_dag_demo.clone()],
        dp_demo.clone(),
    );
    gen.write_borsh(
        "mempool/net_message_sync_reply",
        "mempool::MempoolNetMessage",
        "MempoolNetMessage::SyncReply(lane, [ValidatorDAG], dp_empty)",
        &mp_sync_reply,
    );

    // ---- Replay: BlobProofOutput ------------------------------------------
    //
    // BlobProofOutput is what node_state's proof verifier produces per
    // verified blob: a small wrapper around the inner HyliOutput plus
    // the originating tx and proof bookkeeping. The custom hash mixes
    // blob_tx_hash, original_proof_hash, program_id, and the inner
    // HyliOutput::hashed digest — see data_availability.rs.
    let blob_proof_output_sample = BlobProofOutput {
        blob_tx_hash: TxHash(vec![0x77; 4]),
        original_proof_hash: ProofDataHash(proof_data.hashed().0.clone()),
        hyli_output: hyli_output.clone(),
        program_id: ProgramId(vec![0xaa; 8]),
        verifier: Verifier("risc0".to_string()),
    };
    gen.write_borsh(
        "model/blob_proof_output_sample",
        "hyli_model::BlobProofOutput",
        "BlobProofOutput wrapping the existing hyli_output sample",
        &blob_proof_output_sample,
    );
    gen.write_hash(
        "model/blob_proof_output_sample",
        "hyli_model::BlobProofOutput",
        "BlobProofOutput::hashed (blob_tx_hash ‖ original_proof_hash ‖ program_id ‖ HyliOutput::hashed)",
        blob_proof_output_sample.hashed().0,
    );

    // ---- DA: SignedBlock --------------------------------------------------
    //
    // `SignedBlock` from `crates/hyli-model/src/block.rs` is what flows
    // through the DA stream and is what node_state replays. The wire shape
    // is:
    //   - data_proposals: Vec<(LaneId, Vec<DataProposal>)>
    //   - consensus_proposal: ConsensusProposal
    //   - certificate: AggregateSignature
    //
    // We pin a small but non-trivial example: one lane with one empty
    // DataProposal, the populated cp_full proposal, and a 2-validator
    // aggregate certificate. That keeps the byte length manageable while
    // still exercising every field.
    let signed_block_sample = SignedBlock {
        data_proposals: vec![(lane_demo.clone(), vec![dp_demo.clone()])],
        consensus_proposal: cp_full.clone(),
        certificate: AggregateSignature {
            signature: Signature(vec![0xee; 12]),
            validators: vec![
                ValidatorPublicKey(vec![0x01; 4]),
                ValidatorPublicKey(vec![0x02; 4]),
            ],
        },
    };
    gen.write_borsh(
        "model/signed_block_sample",
        "hyli_model::SignedBlock",
        "SignedBlock with one lane, one empty DataProposal, cp_full, 2-validator aggregate",
        &signed_block_sample,
    );

    // ---- TransactionMetadata / TxId / TransactionKind --------------------
    //
    // The mempool dissemination events ride on top of these — pin them
    // separately so the wire layout drift surfaces independently of the
    // higher-level message tests.
    let txid_sample = TxId(DataProposalHash(b"dp-1".to_vec()), TxHash(b"tx-1".to_vec()));
    gen.write_borsh(
        "model/tx_id_sample",
        "hyli_model::TxId",
        "TxId(dp_hash=\"dp-1\", tx_hash=\"tx-1\")",
        &txid_sample,
    );

    let tx_kind_blob = TransactionKind::Blob;
    gen.write_borsh(
        "model/transaction_kind_blob",
        "hyli_model::TransactionKind",
        "TransactionKind::Blob (single byte 0)",
        &tx_kind_blob,
    );
    let tx_kind_proof = TransactionKind::Proof;
    gen.write_borsh(
        "model/transaction_kind_proof",
        "hyli_model::TransactionKind",
        "TransactionKind::Proof (single byte 1)",
        &tx_kind_proof,
    );
    let tx_kind_verified_proof = TransactionKind::VerifiedProof;
    gen.write_borsh(
        "model/transaction_kind_verified_proof",
        "hyli_model::TransactionKind",
        "TransactionKind::VerifiedProof (single byte 2)",
        &tx_kind_verified_proof,
    );

    let tx_metadata_blob = TransactionMetadata {
        version: 1,
        transaction_kind: TransactionKind::Blob,
        id: txid_sample.clone(),
    };
    gen.write_borsh(
        "model/transaction_metadata_blob",
        "hyli_model::TransactionMetadata",
        "TransactionMetadata { version=1, kind=Blob, id=(dp-1, tx-1) }",
        &tx_metadata_blob,
    );

    // ---- MempoolStatusEvent ----------------------------------------------
    //
    // The dissemination event the mempool publishes when it makes
    // progress on a tx. Both variants ride on the same wire shape, so
    // pin both.
    let mse_waiting = MempoolStatusEvent::WaitingDissemination {
        parent_data_proposal_hash: DataProposalHash(b"parent".to_vec()),
        txs: vec![],
    };
    gen.write_borsh(
        "model/mempool_status_event_waiting",
        "hyli_model::MempoolStatusEvent",
        "MempoolStatusEvent::WaitingDissemination(parent=parent, txs=[])",
        &mse_waiting,
    );

    let mse_created = MempoolStatusEvent::DataProposalCreated {
        parent_data_proposal_hash: DataProposalHash(b"parent".to_vec()),
        data_proposal_hash: DataProposalHash(b"dp-1".to_vec()),
        txs_metadatas: vec![tx_metadata_blob.clone()],
    };
    gen.write_borsh(
        "model/mempool_status_event_created",
        "hyli_model::MempoolStatusEvent",
        "MempoolStatusEvent::DataProposalCreated(parent=parent, dp=dp-1, [tx_metadata])",
        &mse_created,
    );

    // ---- DA stream messages -----------------------------------------------
    //
    // The bytes the DA listener exchanges with peers. Both variants of
    // request and all three variants of event get fixtures so the
    // observer can light up the DA path before any signature work
    // lands.
    let da_req_stream = DataAvailabilityRequest::StreamFromHeight(BlockHeight(42));
    gen.write_borsh(
        "model/da_request_stream",
        "hyli_model::DataAvailabilityRequest",
        "DataAvailabilityRequest::StreamFromHeight(42)",
        &da_req_stream,
    );
    let da_req_block = DataAvailabilityRequest::BlockRequest(BlockHeight(42));
    gen.write_borsh(
        "model/da_request_block",
        "hyli_model::DataAvailabilityRequest",
        "DataAvailabilityRequest::BlockRequest(42)",
        &da_req_block,
    );

    let da_event_signed_block = DataAvailabilityEvent::SignedBlock(signed_block_sample.clone());
    gen.write_borsh(
        "model/da_event_signed_block",
        "hyli_model::DataAvailabilityEvent",
        "DataAvailabilityEvent::SignedBlock(signed_block_sample)",
        &da_event_signed_block,
    );
    let da_event_status = DataAvailabilityEvent::MempoolStatusEvent(mse_created.clone());
    gen.write_borsh(
        "model/da_event_status",
        "hyli_model::DataAvailabilityEvent",
        "DataAvailabilityEvent::MempoolStatusEvent(...)",
        &da_event_status,
    );
    let da_event_not_found = DataAvailabilityEvent::BlockNotFound(BlockHeight(99));
    gen.write_borsh(
        "model/da_event_not_found",
        "hyli_model::DataAvailabilityEvent",
        "DataAvailabilityEvent::BlockNotFound(99)",
        &da_event_not_found,
    );

    // ---- Crypto: BLS signable payload reference ---------------------------
    //
    // For every `Signed<T, V>` value Hyli puts on the wire, the bytes that
    // get BLS-signed are *exactly* `borsh::to_vec(&msg)`. There is no
    // domain separation, no length prefix, no envelope — see
    // `crates/hyli-crypto/src/lib.rs` (`sign_msg` and `verify`).
    //
    // The DST string used by `blst::min_pk` is the only other piece of the
    // signable surface that does not appear in any borsh fixture. Pin it
    // as a corpus byte string so the future zolt-arith BLS verifier can
    // compare its constant against the upstream value at test time.
    //
    // The signable bytes themselves are already covered by the existing
    // borsh fixtures (e.g. `borsh/model/validator_candidacy.bin` is the
    // byte string fed to BLS for a `SignedByValidator<ValidatorCandidacy>`).
    // We re-emit a couple of them under the `borsh/crypto/signable_*`
    // namespace and assert byte equivalence at fixture-generation time, so
    // a future refactor that breaks the "signable == borsh(msg)" invariant
    // fails the build before any Zig test runs.

    let bls_dst: &[u8] = b"BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_";
    gen.write_bytes(
        "borsh",
        "crypto/bls_min_pk_dst",
        "&[u8]",
        "BLS12-381 min_pk DST string used by hyli-crypto::sign_msg".to_string(),
        bls_dst.to_vec(),
    );

    // Signable payload for SignedByValidator<ValidatorCandidacy> is borsh(candidacy).
    let signable_candidacy_bytes = borsh::to_vec(&candidacy).expect("borsh candidacy");
    let candidacy_borsh = std::fs::read(
        Path::new(manifest_dir)
            .join("..")
            .join("corpus")
            .join("borsh")
            .join("model")
            .join("validator_candidacy.bin"),
    )
    .expect("read existing validator_candidacy.bin fixture");
    assert_eq!(
        signable_candidacy_bytes, candidacy_borsh,
        "signable bytes for ValidatorCandidacy must equal borsh(msg)",
    );
    gen.write_bytes(
        "borsh",
        "crypto/signable_validator_candidacy",
        "ValidatorCandidacy",
        "Signable bytes for SignedByValidator<ValidatorCandidacy> = borsh(msg)".to_string(),
        signable_candidacy_bytes,
    );

    // Signable payload for SignedByValidator<NodeConnectionData>.
    let signable_node_data_bytes = borsh::to_vec(&NodeConnectionDataLocal {
        version: 1,
        name: "validator-a".to_string(),
        current_height: 42,
        p2p_public_address: "127.0.0.1:4242".to_string(),
        da_public_address: "127.0.0.1:4243".to_string(),
        start_timestamp: TimestampMs(1_700_000_000_000),
    })
    .expect("borsh node connection data");
    let node_data_borsh = std::fs::read(
        Path::new(manifest_dir)
            .join("..")
            .join("corpus")
            .join("borsh")
            .join("model")
            .join("node_connection_data.bin"),
    )
    .expect("read existing node_connection_data.bin fixture");
    assert_eq!(
        signable_node_data_bytes, node_data_borsh,
        "signable bytes for NodeConnectionData must equal borsh(msg)",
    );
    gen.write_bytes(
        "borsh",
        "crypto/signable_node_connection_data",
        "NodeConnectionData",
        "Signable bytes for SignedByValidator<NodeConnectionData> = borsh(msg)".to_string(),
        signable_node_data_bytes,
    );

    let hyli_rev = detect_hyli_revision();
    gen.write_index(&hyli_rev);
    gen.write_zig_manifest(&hyli_rev);

    println!("Wrote {} fixtures", gen.records.len());
    println!("Source hyli revision: {hyli_rev}");
}
