//! Zyli fixture generator.
//!
//! Produces a versioned, deterministic corpus of Borsh-encoded byte vectors
//! and SHA3-256 hash digests under `../corpus/`. The Zig side embeds these
//! files at compile time and asserts byte equivalence.
//!
//! Two design rules:
//!   1. The output is a function of the source code only — no clock, no env,
//!      no RNG. Re-running must produce zero diffs.
//!   2. Every fixture name appears in `INDEX.md` with the type it represents
//!      and the upstream Hyli git revision used to generate it.

use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use borsh::BorshSerialize;
use hyli_model::{
    utils::TimestampMs, AggregateSignature, Blob, BlobData, BlobIndex, BlobTransaction,
    BlockHeight, ConsensusProposal, ConsensusProposalHash, ConsensusStakingAction, ContractName,
    DataProposal, DataProposalHash, DataProposalParent, Hashed, Identity, LaneBytesSize, LaneId,
    ProgramId, ProofData, ProofDataHash, ProofTransaction, RegisterContractAction, Signature,
    Signed, StateCommitment, TimeoutWindow, Transaction, TransactionData, ValidatorCandidacy,
    ValidatorPublicKey, ValidatorSignature, Verifier, VerifiedProofTransaction,
};
use sha3::Digest as _;

/// Records a single fixture's metadata for the human-readable index.
struct FixtureRecord {
    /// Path relative to `corpus/` where the bytes were written.
    relative_path: String,
    /// Rust type the fixture represents.
    rust_type: &'static str,
    /// One-sentence description of the value.
    description: String,
    /// Length of the encoded payload (handy when scanning the index).
    byte_len: usize,
}

struct Generator {
    corpus_root: PathBuf,
    records: Vec<FixtureRecord>,
}

impl Generator {
    fn new(corpus_root: PathBuf) -> Self {
        Self {
            corpus_root,
            records: Vec::new(),
        }
    }

    /// Borsh-encode `value` and write the bytes to `<corpus>/borsh/<rel>.bin`.
    fn write_borsh<T: BorshSerialize>(
        &mut self,
        rel: &str,
        rust_type: &'static str,
        description: impl Into<String>,
        value: &T,
    ) {
        let bytes = borsh::to_vec(value).expect("borsh encode");
        self.write_bytes("borsh", rel, rust_type, description.into(), bytes);
    }

    /// Write a raw SHA3-256 digest to `<corpus>/hash/<rel>.bin`.
    fn write_hash(
        &mut self,
        rel: &str,
        rust_type: &'static str,
        description: impl Into<String>,
        digest: Vec<u8>,
    ) {
        self.write_bytes("hash", rel, rust_type, description.into(), digest);
    }

    fn write_bytes(
        &mut self,
        category: &str,
        rel: &str,
        rust_type: &'static str,
        description: String,
        bytes: Vec<u8>,
    ) {
        let path = self.corpus_root.join(category).join(format!("{rel}.bin"));
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("mkdir -p corpus subdir");
        }
        fs::write(&path, &bytes).expect("write fixture");
        self.records.push(FixtureRecord {
            relative_path: format!("{category}/{rel}.bin"),
            rust_type,
            description,
            byte_len: bytes.len(),
        });
    }

    /// Write the human-readable index file. Sorted so the file is stable.
    fn write_index(&mut self, hyli_rev: &str) {
        self.records
            .sort_by(|a, b| a.relative_path.cmp(&b.relative_path));
        let mut out = String::new();
        out.push_str("# Zyli compatibility corpus\n\n");
        out.push_str(
            "Auto-generated by `compat/fixture-gen`. Do not edit by hand — \
             rerun the generator to update.\n\n",
        );
        out.push_str(&format!("Source: `hyli` git revision `{hyli_rev}`.\n\n"));
        out.push_str("| Path | Rust type | Bytes | Description |\n");
        out.push_str("|------|-----------|-------|-------------|\n");
        for rec in &self.records {
            out.push_str(&format!(
                "| `{}` | `{}` | {} | {} |\n",
                rec.relative_path, rec.rust_type, rec.byte_len, rec.description,
            ));
        }
        let path = self.corpus_root.join("INDEX.md");
        let mut f = fs::File::create(&path).expect("create INDEX.md");
        f.write_all(out.as_bytes()).expect("write INDEX.md");
    }

    /// Emit a Zig manifest at `compat/corpus.zig` that re-exports every
    /// fixture as an `@embedFile` constant.
    ///
    /// Why generate this instead of writing it by hand: keeping the manifest
    /// in lock-step with the corpus is the only way to guarantee a fixture
    /// rename or addition can never silently break a Zig test (you'd get a
    /// compile error on the next `zig build`). The manifest lives at
    /// `compat/corpus.zig` so its package root is `compat/`, which is the
    /// directory `@embedFile` is restricted to.
    fn write_zig_manifest(&self, hyli_rev: &str) {
        // The manifest path is the parent of `corpus_root`.
        let manifest_path = self
            .corpus_root
            .parent()
            .expect("corpus root has parent")
            .join("corpus.zig");

        // Build a tree of (category -> subcategory -> [(name, rel_path)]).
        // For us "category" is `borsh` or `hash`, "subcategory" is the next
        // path component (e.g. `primitives`, `model`), and `name` is the
        // file stem.
        use std::collections::BTreeMap;
        type Tree = BTreeMap<String, BTreeMap<String, Vec<(String, String)>>>;
        let mut tree: Tree = BTreeMap::new();
        for rec in &self.records {
            let parts: Vec<&str> = rec.relative_path.split('/').collect();
            if parts.len() != 3 {
                panic!("unexpected fixture path: {}", rec.relative_path);
            }
            let category = parts[0];
            let sub = parts[1];
            let stem = parts[2]
                .strip_suffix(".bin")
                .expect("fixture filename ends in .bin");
            tree.entry(category.to_string())
                .or_default()
                .entry(sub.to_string())
                .or_default()
                .push((stem.to_string(), rec.relative_path.clone()));
        }

        let mut out = String::new();
        out.push_str(
            "//! Auto-generated by `compat/fixture-gen`. Do not edit by hand.\n\
             //!\n\
             //! Each constant points at a Borsh or hash fixture under\n\
             //! `compat/corpus/`. The Zig side embeds the bytes at compile\n\
             //! time, so a missing or renamed fixture surfaces as a build\n\
             //! error long before any test runs.\n\
             //!\n",
        );
        out.push_str(&format!("//! Source: hyli git revision `{hyli_rev}`.\n\n"));
        for (category, subs) in &tree {
            out.push_str(&format!("pub const {category} = struct {{\n"));
            for (sub, items) in subs {
                out.push_str(&format!("    pub const {sub} = struct {{\n"));
                for (stem, rel_path) in items {
                    out.push_str(&format!(
                        "        pub const {stem}: []const u8 = @embedFile(\"corpus/{rel_path}\");\n",
                    ));
                }
                out.push_str("    };\n");
            }
            out.push_str("};\n\n");
        }
        fs::write(&manifest_path, out).expect("write corpus.zig");
    }
}

/// Best-effort lookup of the upstream Hyli git revision so the corpus can
/// always be traced back to a specific source. Falls back to `unknown` if the
/// repository or git binary is unavailable.
fn detect_hyli_revision() -> String {
    use std::process::Command;
    let hyli_dir = Path::new("../../../hyli");
    let output = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(hyli_dir)
        .output();
    match output {
        Ok(out) if out.status.success() => String::from_utf8_lossy(&out.stdout).trim().to_string(),
        _ => "unknown".to_string(),
    }
}

fn main() {
    // Resolve corpus root relative to the crate manifest so the binary works
    // regardless of the cwd it was launched from.
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let corpus_root = Path::new(manifest_dir).join("..").join("corpus");
    if corpus_root.exists() {
        // Wipe stale fixtures so the rerun is byte-for-byte identical.
        fs::remove_dir_all(&corpus_root).expect("clean corpus directory");
    }
    fs::create_dir_all(&corpus_root).expect("create corpus directory");

    let mut gen = Generator::new(corpus_root);

    // ---- T0 primitives -----------------------------------------------------
    gen.write_borsh(
        "primitives/u8_42",
        "u8",
        "single byte 42",
        &42u8,
    );
    gen.write_borsh(
        "primitives/u32_0xdeadbeef",
        "u32",
        "0xdeadbeef little-endian",
        &0xdeadbeef_u32,
    );
    gen.write_borsh(
        "primitives/u64_one",
        "u64",
        "u64::1 little-endian",
        &1u64,
    );
    gen.write_borsh(
        "primitives/u128_max",
        "u128",
        "u128::MAX",
        &u128::MAX,
    );
    gen.write_borsh(
        "primitives/i32_neg_one",
        "i32",
        "-1 as two's complement",
        &-1i32,
    );
    gen.write_borsh(
        "primitives/option_u32_some_7",
        "Option<u32>",
        "Some(7)",
        &Some(7u32),
    );
    gen.write_borsh(
        "primitives/option_u32_none",
        "Option<u32>",
        "None",
        &Option::<u32>::None,
    );
    gen.write_borsh(
        "primitives/string_hello",
        "String",
        "ASCII string \"hello\"",
        &"hello".to_string(),
    );
    gen.write_borsh(
        "primitives/string_unicode",
        "String",
        "UTF-8 \"héllo🦀\"",
        &"héllo🦀".to_string(),
    );
    gen.write_borsh(
        "primitives/vec_u8_three",
        "Vec<u8>",
        "[1, 2, 3]",
        &vec![1u8, 2, 3],
    );
    gen.write_borsh(
        "primitives/vec_u32_two",
        "Vec<u32>",
        "[1, 2]",
        &vec![1u32, 2u32],
    );

    // ---- T1 newtypes -------------------------------------------------------
    gen.write_borsh(
        "model/identity_alice",
        "hyli_model::Identity",
        "Identity(\"alice@hyli\")",
        &Identity("alice@hyli".to_string()),
    );
    gen.write_borsh(
        "model/contract_name_hyli",
        "hyli_model::ContractName",
        "ContractName(\"hyli\")",
        &ContractName("hyli".to_string()),
    );
    gen.write_borsh(
        "model/program_id_4_bytes",
        "hyli_model::ProgramId",
        "ProgramId([0xde,0xad,0xbe,0xef])",
        &ProgramId(vec![0xde, 0xad, 0xbe, 0xef]),
    );
    gen.write_borsh(
        "model/verifier_risc0",
        "hyli_model::Verifier",
        "Verifier(\"risc0\")",
        &Verifier("risc0".to_string()),
    );
    gen.write_borsh(
        "model/blob_index_3",
        "hyli_model::BlobIndex",
        "BlobIndex(3) — note: usize → u64 on the wire",
        &BlobIndex(3),
    );
    gen.write_borsh(
        "model/state_commitment_4_bytes",
        "hyli_model::StateCommitment",
        "StateCommitment([0,1,2,3])",
        &StateCommitment(vec![0, 1, 2, 3]),
    );
    gen.write_borsh(
        "model/block_height_42",
        "hyli_model::BlockHeight",
        "BlockHeight(42)",
        &BlockHeight(42),
    );
    gen.write_borsh(
        "model/timestamp_ms_unix_epoch",
        "hyli_model::TimestampMs",
        "TimestampMs(0) — sanity for u128 layout",
        &TimestampMs(0),
    );
    gen.write_borsh(
        "model/timestamp_ms_max_u64",
        "hyli_model::TimestampMs",
        "TimestampMs(u64::MAX as u128)",
        &TimestampMs(u64::MAX as u128),
    );
    gen.write_borsh(
        "model/timeout_window_no_timeout",
        "hyli_model::TimeoutWindow",
        "TimeoutWindow::NoTimeout",
        &TimeoutWindow::NoTimeout,
    );
    gen.write_borsh(
        "model/timeout_window_default",
        "hyli_model::TimeoutWindow",
        "TimeoutWindow::Timeout { hard=100, soft=100 }",
        &TimeoutWindow::default(),
    );
    gen.write_borsh(
        "model/lane_id_default",
        "hyli_model::LaneId",
        "LaneId::default()",
        &LaneId::default(),
    );

    // ---- T1 protocol structs ----------------------------------------------
    let blob = Blob {
        contract_name: ContractName("hyli".to_string()),
        data: BlobData(vec![0x01, 0x02, 0x03]),
    };
    gen.write_borsh(
        "model/blob_simple",
        "hyli_model::Blob",
        "Blob { contract_name=\"hyli\", data=[1,2,3] }",
        &blob,
    );
    gen.write_hash(
        "model/blob_simple",
        "hyli_model::Blob",
        "Blob::hashed for the matching borsh fixture",
        blob.hashed().0,
    );

    // RegisterContractAction with a constructor_metadata: this exercises the
    // Option<Vec<u8>> field that is `borsh(skip)`-equivalent for the hash but
    // present on the wire.
    let register = RegisterContractAction {
        verifier: Verifier("risc0".to_string()),
        program_id: ProgramId(vec![0xaa; 8]),
        state_commitment: StateCommitment(vec![0xbb; 8]),
        contract_name: ContractName("counter".to_string()),
        timeout_window: Some(TimeoutWindow::Timeout {
            hard_timeout: BlockHeight(50),
            soft_timeout: BlockHeight(100),
        }),
        constructor_metadata: Some(vec![0xcc; 4]),
    };
    gen.write_borsh(
        "model/register_contract_action",
        "hyli_model::RegisterContractAction",
        "Sample RegisterContractAction with timeout + constructor metadata",
        &register,
    );
    gen.write_hash(
        "model/register_contract_action",
        "hyli_model::RegisterContractAction",
        "RegisterContractAction::hashed (constructor_metadata excluded)",
        register.hashed().0,
    );

    // DataProposal with no transactions and a fixed parent hash. Useful as a
    // first sanity vector for the DA layer.
    let dp = DataProposal::new(DataProposalHash(b"parent".to_vec()), vec![]);
    gen.write_borsh(
        "model/data_proposal_empty",
        "hyli_model::DataProposal",
        "DataProposal::new(parent=\"parent\", txs=[])",
        &dp,
    );
    gen.write_hash(
        "model/data_proposal_empty",
        "hyli_model::DataProposal",
        "DataProposal::hashed for the empty-tx case",
        dp.hashed().0,
    );

    // SHA3-256 of the empty input — useful as a baseline for the hash module
    // before we start matching custom Hyli digest constructions.
    let empty_sha3 = sha3::Sha3_256::digest(b"").to_vec();
    gen.write_hash(
        "primitives/sha3_256_empty",
        "sha3::Sha3_256",
        "SHA3-256 of empty input",
        empty_sha3,
    );

    // Cover DataProposalParent enum variants explicitly.
    gen.write_borsh(
        "model/data_proposal_parent_lane_root",
        "hyli_model::DataProposalParent",
        "DataProposalParent::LaneRoot(LaneId::default())",
        &DataProposalParent::LaneRoot(LaneId::default()),
    );
    gen.write_borsh(
        "model/data_proposal_parent_dp",
        "hyli_model::DataProposalParent",
        "DataProposalParent::DP(\"parent\")",
        &DataProposalParent::DP(DataProposalHash(b"parent".to_vec())),
    );

    // ---- T1: Transaction family --------------------------------------------
    //
    // BlobTransaction with two blobs. Identity is `alice@hyli` so the
    // identity-validation rule (the "@<contract>" suffix must match a
    // blob's contract_name) holds. The hash_cache and blobshash_cache
    // fields are `#[borsh(skip)]` and must NOT show up in the wire bytes,
    // so the encoded length is purely identity + blobs.
    let blob_tx_blobs = vec![
        Blob {
            contract_name: ContractName("hyli".to_string()),
            data: BlobData(vec![0xaa, 0xbb]),
        },
        Blob {
            contract_name: ContractName("counter".to_string()),
            data: BlobData(vec![0x01, 0x02, 0x03, 0x04]),
        },
    ];
    let blob_tx = BlobTransaction::new("alice@hyli", blob_tx_blobs.clone());
    gen.write_borsh(
        "model/blob_transaction",
        "hyli_model::BlobTransaction",
        "BlobTransaction(alice@hyli, [Blob(hyli,…), Blob(counter,…)])",
        &blob_tx,
    );
    gen.write_hash(
        "model/blob_transaction",
        "hyli_model::BlobTransaction",
        "BlobTransaction::hashed for the matching borsh fixture",
        blob_tx.hashed().0,
    );

    // ProofTransaction sample. Note: ProofData is the raw proof bytes,
    // ProofDataHash is sha3_256 of the ProofData; the latter is what gets
    // mixed into TxHash, not the proof itself.
    let proof_data = ProofData(vec![0x42; 16]);
    let proof_tx = ProofTransaction {
        contract_name: ContractName("counter".to_string()),
        program_id: ProgramId(vec![0xde, 0xad]),
        verifier: Verifier("risc0".to_string()),
        proof: proof_data.clone(),
    };
    gen.write_borsh(
        "model/proof_transaction",
        "hyli_model::ProofTransaction",
        "ProofTransaction(counter, risc0, ProofData([0x42; 16]))",
        &proof_tx,
    );
    gen.write_hash(
        "model/proof_transaction",
        "hyli_model::ProofTransaction",
        "ProofTransaction::hashed",
        proof_tx.hashed().0,
    );
    gen.write_hash(
        "model/proof_data",
        "hyli_model::ProofData",
        "ProofData::hashed for [0x42; 16]",
        proof_data.hashed().0,
    );

    // VerifiedProofTransaction. proof = None on this fixture so we exercise
    // the Option<ProofData> = None path. The hash should be identical to
    // ProofTransaction's because both feed program_id, verifier,
    // contract_name, and proof_hash into the hasher.
    let proof_data_hash = ProofDataHash(proof_data.hashed().0.clone());
    let verified_proof_tx = VerifiedProofTransaction {
        contract_name: ContractName("counter".to_string()),
        program_id: ProgramId(vec![0xde, 0xad]),
        verifier: Verifier("risc0".to_string()),
        proof: None,
        proof_hash: proof_data_hash.clone(),
        proof_size: proof_data.0.len(),
        proven_blobs: vec![],
        is_recursive: false,
    };
    gen.write_borsh(
        "model/verified_proof_transaction",
        "hyli_model::VerifiedProofTransaction",
        "VerifiedProofTransaction(counter, proof=None, proof_size=16)",
        &verified_proof_tx,
    );
    gen.write_hash(
        "model/verified_proof_transaction",
        "hyli_model::VerifiedProofTransaction",
        "VerifiedProofTransaction::hashed",
        verified_proof_tx.hashed().0,
    );

    // Transaction wrapping a BlobTransaction — exercises the enum-tagged
    // `TransactionData` envelope. The version field should land first
    // (it's a struct field declared before transaction_data).
    let tx_blob = Transaction {
        version: 1,
        transaction_data: TransactionData::Blob(blob_tx.clone()),
    };
    gen.write_borsh(
        "model/transaction_blob",
        "hyli_model::Transaction",
        "Transaction { version=1, data=Blob(...) }",
        &tx_blob,
    );

    // Transaction wrapping a ProofTransaction.
    let tx_proof = Transaction {
        version: 1,
        transaction_data: TransactionData::Proof(proof_tx.clone()),
    };
    gen.write_borsh(
        "model/transaction_proof",
        "hyli_model::Transaction",
        "Transaction { version=1, data=Proof(...) }",
        &tx_proof,
    );

    // ---- T1: Signed envelopes ----------------------------------------------
    //
    // Signed<ValidatorCandidacy, ValidatorSignature> is the canonical
    // SignedByValidator<T> shape used for consensus messages. We pin both
    // a representative concrete payload and the standalone signature
    // newtypes so the Zig side can validate the envelope and the inner
    // crypto bytes independently.
    let validator_pubkey = ValidatorPublicKey(vec![0x01; 4]);
    gen.write_borsh(
        "model/validator_public_key",
        "hyli_model::ValidatorPublicKey",
        "ValidatorPublicKey([0x01; 4])",
        &validator_pubkey,
    );
    let signature = Signature(vec![0xff; 8]);
    gen.write_borsh(
        "model/signature_8_bytes",
        "hyli_model::Signature",
        "Signature([0xff; 8])",
        &signature,
    );
    let validator_signature = ValidatorSignature {
        signature: signature.clone(),
        validator: validator_pubkey.clone(),
    };
    gen.write_borsh(
        "model/validator_signature",
        "hyli_model::ValidatorSignature",
        "ValidatorSignature { sig=[0xff;8], validator=[0x01;4] }",
        &validator_signature,
    );
    let candidacy = ValidatorCandidacy {
        peer_address: "127.0.0.1:4242".to_string(),
    };
    gen.write_borsh(
        "model/validator_candidacy",
        "hyli_model::ValidatorCandidacy",
        "ValidatorCandidacy { peer_address=\"127.0.0.1:4242\" }",
        &candidacy,
    );
    let signed_candidacy: Signed<ValidatorCandidacy, ValidatorSignature> = Signed {
        msg: candidacy.clone(),
        signature: validator_signature.clone(),
    };
    gen.write_borsh(
        "model/signed_validator_candidacy",
        "hyli_model::Signed<ValidatorCandidacy, ValidatorSignature>",
        "SignedByValidator<ValidatorCandidacy>",
        &signed_candidacy,
    );

    // AggregateSignature exercising 2 validators. This is the wire shape used
    // for PoDA and consensus aggregate proofs.
    let agg = AggregateSignature {
        signature: Signature(vec![0xee; 12]),
        validators: vec![
            ValidatorPublicKey(vec![0x01; 4]),
            ValidatorPublicKey(vec![0x02; 4]),
        ],
    };
    gen.write_borsh(
        "model/aggregate_signature_2",
        "hyli_model::AggregateSignature",
        "AggregateSignature with 2 validators",
        &agg,
    );

    // ---- T1: Consensus -----------------------------------------------------
    //
    // ConsensusStakingAction enum, both variants individually.
    let staking_bond = ConsensusStakingAction::Bond {
        candidate: Box::new(Signed::<ValidatorCandidacy, ValidatorSignature> {
            msg: ValidatorCandidacy {
                peer_address: "127.0.0.1:4242".to_string(),
            },
            signature: validator_signature.clone(),
        }),
    };
    gen.write_borsh(
        "model/consensus_staking_action_bond",
        "hyli_model::ConsensusStakingAction",
        "ConsensusStakingAction::Bond { candidate=SignedByValidator<ValidatorCandidacy> }",
        &staking_bond,
    );

    // The Box<...> on the Bond variant must be invisible on the wire — the
    // raw and the boxed encodings should be byte-identical. We assert that
    // here at fixture-generation time so a regression in borsh would fail
    // the build before any Zig test runs.
    {
        let raw_bytes = borsh::to_vec(&Signed::<ValidatorCandidacy, ValidatorSignature> {
            msg: ValidatorCandidacy {
                peer_address: "127.0.0.1:4242".to_string(),
            },
            signature: validator_signature.clone(),
        })
        .expect("borsh raw signed");
        let boxed_bytes = borsh::to_vec(&staking_bond).expect("borsh boxed bond");
        // boxed_bytes = 1-byte enum tag (0 for Bond) ‖ raw_bytes
        assert_eq!(boxed_bytes[0], 0u8, "Bond is variant index 0");
        assert_eq!(
            &boxed_bytes[1..],
            &raw_bytes[..],
            "Box<T> should be transparent over the wire"
        );
    }

    let staking_pay = ConsensusStakingAction::PayFeesForDaDi {
        lane_id: LaneId::default(),
        cumul_size: LaneBytesSize(4096),
    };
    gen.write_borsh(
        "model/consensus_staking_action_pay",
        "hyli_model::ConsensusStakingAction",
        "ConsensusStakingAction::PayFeesForDaDi { lane=default, cumul=4096 }",
        &staking_pay,
    );

    // LaneBytesSize standalone — handy for the BLS work later when
    // hashing the same value with `to_le_bytes`.
    gen.write_borsh(
        "model/lane_bytes_size_4096",
        "hyli_model::LaneBytesSize",
        "LaneBytesSize(4096)",
        &LaneBytesSize(4096),
    );

    // Empty ConsensusProposal: zero cut entries, zero staking actions, a
    // fixed timestamp/parent. This is the simplest possible hash input,
    // and the hash construction has to skip the empty cut/staking_actions
    // loops cleanly.
    let cp_empty = ConsensusProposal {
        slot: 1,
        parent_hash: ConsensusProposalHash(b"genesis".to_vec()),
        cut: vec![],
        staking_actions: vec![],
        timestamp: TimestampMs(1234),
    };
    gen.write_borsh(
        "model/consensus_proposal_empty",
        "hyli_model::ConsensusProposal",
        "ConsensusProposal { slot=1, cut=[], actions=[], ts=1234, parent=genesis }",
        &cp_empty,
    );
    gen.write_hash(
        "model/consensus_proposal_empty",
        "hyli_model::ConsensusProposal",
        "ConsensusProposal::hashed for the empty case",
        cp_empty.hashed().0,
    );

    // Populated ConsensusProposal: one cut entry and one PayFeesForDaDi
    // staking action. The cut entry uses a non-default LaneId so the test
    // pins the raw-bytes (NOT hex) update_hasher path. The
    // LaneBytesSize and AggregateSignature on the cut entry are *not*
    // fed into the hash, but they ARE part of the borsh wire format —
    // confirming this round-trips proves both halves of the
    // hash-vs-encode split.
    let cut_lane = LaneId::with_suffix(ValidatorPublicKey(vec![0x01; 4]), "lane-a");
    let cut_dp_hash = DataProposalHash(b"dp-hash".to_vec());
    let cut_size = LaneBytesSize(8192);
    let cut_agg = AggregateSignature {
        signature: Signature(vec![0xee; 12]),
        validators: vec![ValidatorPublicKey(vec![0x01; 4])],
    };
    let cp_full = ConsensusProposal {
        slot: 7,
        parent_hash: ConsensusProposalHash(b"prev-cp".to_vec()),
        cut: vec![(
            cut_lane.clone(),
            cut_dp_hash.clone(),
            cut_size,
            cut_agg.clone(),
        )],
        staking_actions: vec![ConsensusStakingAction::PayFeesForDaDi {
            lane_id: cut_lane.clone(),
            cumul_size: LaneBytesSize(8192),
        }],
        timestamp: TimestampMs(9999),
    };
    gen.write_borsh(
        "model/consensus_proposal_full",
        "hyli_model::ConsensusProposal",
        "ConsensusProposal with one cut entry and one PayFeesForDaDi",
        &cp_full,
    );
    gen.write_hash(
        "model/consensus_proposal_full",
        "hyli_model::ConsensusProposal",
        "ConsensusProposal::hashed for the populated case",
        cp_full.hashed().0,
    );

    // ---- Wire framing -----------------------------------------------------
    //
    // Hyli wraps every TCP message in a default tokio-util
    // `LengthDelimitedCodec` frame: a 4-byte BIG-ENDIAN length followed
    // by `len` bytes of payload. The payload itself is one of:
    //   - `b"PING"` literal (4 bytes), or
    //   - `borsh(TcpWireData)` where `TcpWireData = { headers, payload }`
    //
    // Note that `TcpMessage::Ping` is NOT borsh-encoded as an enum variant —
    // hyli sends the raw 4 bytes "PING" and the receiver detects them by
    // string match before attempting borsh deserialization. This is the
    // wire-level quirk that the Zig framing layer has to mirror exactly.
    //
    // Both the framed bytes (with the BE length prefix) and the inner
    // bytes (without it) are emitted as fixtures so the Zig side can test
    // each layer independently.

    // Mirror of `hyli_net::tcp::TcpWireData`. The Rust definition is
    // pub(crate), so we redeclare it here. If the upstream layout ever
    // changes, the test against the existing serialize_tcp_message Rust
    // assertions below will break loudly.
    #[derive(borsh::BorshSerialize)]
    struct TcpWireData {
        headers: Vec<(String, String)>,
        payload: Vec<u8>,
    }

    fn frame(payload: &[u8]) -> Vec<u8> {
        let len: u32 = payload.len().try_into().expect("frame fits in u32");
        let mut out = Vec::with_capacity(4 + payload.len());
        out.extend_from_slice(&len.to_be_bytes());
        out.extend_from_slice(payload);
        out
    }

    // Inner bytes — TcpMessage::Ping is the literal "PING".
    gen.write_bytes(
        "wire",
        "messages/tcp_message_ping_inner",
        "[u8; 4]",
        "TcpMessage::Ping inner bytes (b\"PING\")".to_string(),
        b"PING".to_vec(),
    );
    // Framed bytes — 4-byte BE length prefix (0x00000004) + b"PING".
    gen.write_bytes(
        "wire",
        "messages/tcp_message_ping_framed",
        "[u8]",
        "Framed TcpMessage::Ping (BE length + b\"PING\")".to_string(),
        frame(b"PING"),
    );

    // Inner bytes — TcpData with empty headers and a 3-byte payload.
    // This matches the existing hyli unit test (`test_serialize_tcp_message`)
    // which asserts the bytes are [0,0,0,0, 3,0,0,0, 1,2,3]:
    //   - 4 bytes: headers Vec length = 0 (LE u32)
    //   - 4 bytes: payload Vec length = 3 (LE u32)
    //   - 3 bytes: payload [1,2,3]
    let tcp_data_simple = TcpWireData {
        headers: vec![],
        payload: vec![1, 2, 3],
    };
    let tcp_data_simple_bytes = borsh::to_vec(&tcp_data_simple).expect("borsh tcp data simple");
    assert_eq!(
        tcp_data_simple_bytes,
        vec![0, 0, 0, 0, 3, 0, 0, 0, 1, 2, 3],
        "TcpWireData layout drifted from upstream hyli expectation",
    );
    gen.write_bytes(
        "wire",
        "messages/tcp_message_data_simple_inner",
        "TcpWireData",
        "TcpData{headers=[], payload=[1,2,3]} as borsh(TcpWireData)".to_string(),
        tcp_data_simple_bytes.clone(),
    );
    gen.write_bytes(
        "wire",
        "messages/tcp_message_data_simple_framed",
        "[u8]",
        "Framed TcpData{headers=[], payload=[1,2,3]}".to_string(),
        frame(&tcp_data_simple_bytes),
    );

    // Inner bytes — TcpData with one header and a 3-byte payload.
    let tcp_data_with_header = TcpWireData {
        headers: vec![("k".to_string(), "v".to_string())],
        payload: vec![0xaa, 0xbb],
    };
    let tcp_data_with_header_bytes =
        borsh::to_vec(&tcp_data_with_header).expect("borsh tcp data header");
    gen.write_bytes(
        "wire",
        "messages/tcp_message_data_header_inner",
        "TcpWireData",
        "TcpData{headers=[(k,v)], payload=[0xaa,0xbb]}".to_string(),
        tcp_data_with_header_bytes.clone(),
    );
    gen.write_bytes(
        "wire",
        "messages/tcp_message_data_header_framed",
        "[u8]",
        "Framed TcpData{headers=[(k,v)], payload=[0xaa,0xbb]}".to_string(),
        frame(&tcp_data_with_header_bytes),
    );

    let hyli_rev = detect_hyli_revision();
    gen.write_index(&hyli_rev);
    gen.write_zig_manifest(&hyli_rev);

    println!("Wrote {} fixtures", gen.records.len());
    println!("Source hyli revision: {hyli_rev}");
}
